### ISSUE TITLE
Unable to join - Mission Altis_Life.Altis read from bank.

### ISSUE THREAD

**Issue by Reck1501** [AsYetUntitled/Framework#100]
### Expected behaviour
Working properly without spam - and ability to join

### Actual behaviour
Console spammed with "Mission Altis_Life.Altis read from bank." and rpt with "Unsupported language English in stringtable".

Unable to join

### Steps to reproduce the behaviour 
1. I've got no idea - all I've done is followed the wiki and also tried several video tutorials.

### RPT and/or extDB2 logs (if applicable)
<If there are error messages in your RPT and/or extDB2 logs then you can either paste the error message(s) here or you can upload your RPT or extDB2 log file(s) to GitHub.>
<See https://community.bistudio.com/wiki/Crash_Files for where to find your Arma 3 RPT logs.>
<If your error messages are long, or you are posting a full RPT, please use paste/haste-bin!!>
RPT: http://pastebin.com/aPanvuMb
Console: http://pastebin.com/3kPDRDfe

----

Launcher version: 1.5.137506

Game version: 1.62.138470

Branch: main / beta branch not specified

**Comment by Jawshy** [comment]
Hello, @Reck1501. 

This is not an issue with the current build of the mission. The server must be incorrectly setup. If you would like to join the [ArmA RPG Life Discord server](https://discordapp.com/invite/sEcQdPn) and post in #server_setup we can help you diagnose and fix the issue. Alternatively, you can post in [server help](https://armarpglife.com/forums/forum/15-server-help/) on the ArmA RPG Life forums. Be sure to include the details you have posted here. Thanks.
