### ISSUE TITLE
Players spawn naked

### ISSUE THREAD

**Issue by setoy** [AsYetUntitled/Framework#103]
### Expected behaviour
You shouldn't spawn naked.

### Actual behaviour
Well, players spawn naked...

### Steps to reproduce the behaviour 
1. Spawn, abort mission and re-spawn

### RPT and/or extDB2 logs (if applicable)
http://hastebin.com/uhipejizib.vbs

----

Launcher version: 1.5.138489

Game version: 1.64.138497

Branch: main / beta branch not specified

Started with 1.64

**Comment by Jawshy** [comment]
Duplicate of https://github.com/AsYetUntitled/Framework/issues/81.

**Comment by tkcjesse** [comment]
Much description. Much wow.

**Comment by setoy** [comment]
Nothing more is needed to reproduce this ;)

**Comment by BoGuu** [comment]
https://github.com/AsYetUntitled/Framework/issues/104
