### ISSUE TITLE
Group Name - AsYetUntitled

### ISSUE THREAD

**Issue by sargken** [AsYetUntitled/Framework#105]
Can we get it a proper name? Restore the Wiki from the last repo that was hacked?

**Comment by trinitynet** [comment]
this is the name

**Comment by sargken** [comment]
Not the point im trying to make. If that is the name then Cool but shouldn't it be renamed to ArmARPGLIFE? or some sort.

**Comment by tkcjesse** [comment]
BoGuu is against that **shitter** name.

**Comment by Jawshy** [comment]
Could the organisation icon be changed at least? 

![AsYetUntitled](https://i.ytimg.com/vi/Dkm8Hteeh6M/maxresdefault.jpg)

**Comment by fresqo** [comment]
yes change please. who the fuck is this?

**Comment by harmdhast** [comment]
I vote for h3h3 pic. Let's rename "WePrayTheBennieGod"

**Comment by Jawshy** [comment]
[VAPE NATION](https://www.youtube.com/watch?v=Dkm8Hteeh6M)

**Comment by harmdhast** [comment]
XD

**Comment by Jawshy** [comment]
> Restore the Wiki from the last repo that was hacked?

@sargken, the wiki was restored ages ago, 

[AsYetUntitled/Framework/wiki](https://github.com/AsYetUntitled/Framework/wiki) → [ArmaLife/Framework/wiki](https://github.com/ArmaLife/Framework/wiki) → [ArmaLife/Framework/wiki/Home/_history](https://github.com/ArmaLife/Framework/wiki/Home/_history).

**Comment by harmdhast** [comment]
Shhhh... Rip wiki

**Comment by sargken** [comment]
That's not restoring it. Your are just directing them to the old repo

**Comment by Jawshy** [comment]
This repository never had a wiki. The ArmaLife/Framework had a wiki which was deleted when the repo was deleted. ArmaLife/Framework was re-created and its wiki restored.

**Comment by tkcjesse** [comment]
Which speaking of, can I get permissions back on that cock sucker. https://github.com/ArmaLife/Framework

**Comment by Jawshy** [comment]
@tkcjesse, they won't last for long. :wink:

**Comment by tkcjesse** [comment]
This is true. Nevermind.
