### ISSUE TITLE
Player gear & license wipe after relog

### ISSUE THREAD

**Issue by condolent** [AsYetUntitled/Framework#107]
Since the last update, each time a player relogs everything gets wiped; Licenses, clothes etc. But money is still there.

How can I fix this? I've seen others fix it but I have no idea how they did it

**Comment by setoy** [comment]
https://github.com/AsYetUntitled/Framework/issues/104

**Comment by Jawshy** [comment]
@condolent, as @setoy has pointed out, this issue has already been reported. Please search the existing issues before posting a new issue. If you do post a new issue then please follow the provided [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md).
