### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by ExtremeCopycat** [AsYetUntitled/Framework#113]
When i import the altislife.sql in my database i get this error: #1293 - Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

**Comment by setoy** [comment]
https://github.com/AsYetUntitled/Framework/pull/95#issuecomment-248500724

**Comment by Jawshy** [comment]
@ExtremeCopycat, see the link @setoy has provided. If you still need help then you can join the [ArmA RPG Life Discord server](https://discordapp.com/invite/sEcQdPn) and post in the \#troubleshooting channel or post in the appropriate section on the [ArmA RPG Life forums](https://armarpglife.com/forums/). 

In future please follow the provided [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md).
