### ISSUE TITLE
Weapons Dupe on Player Killed

### ISSUE THREAD

**Issue by SimZor** [AsYetUntitled/Framework#115]
### Expected behaviour
When you die, weapon disappears instantly and no one can pick it up.

### Actual behaviour
When you die, sometimes the weapon disappears after 5 seconds, and sometimes it doesn't disappear at all.

### Steps to reproduce the behaviour 
1. Kill a player that has a Primary gun in his hands..
2. Wait for it to either disappear after 5 seconds or not disappear.
3. Pick up the weapon
4. Revive player and he will get the weapon back

### [RPT]

No errors shown

----

Mission version: 4.4r3 with recent updates

Launcher version:
Game version: Both on Arma 1.62 and 1.64
Branch: master

**Comment by DarkSilencerZA** [comment]
On occasion it does happen where the weapon doesn't get deleted. It also doesn't get deleted fast enough and can be picked up within a few seconds.

**Comment by SimZor** [comment]
Exactly. @DarkSilencerZA

**Comment by tkcjesse** [comment]
Can potentially make it so take item and inventory open dont work on ground holders near dead bodies. Idk. I'll look at it some more. It's currently set to be basically as quick as possible.

**Comment by SimZor** [comment]
I tried doing this but it didn't work.

On death
´´
dead_weapon = weapon player;
´´

on Revive
´´
player addWeapon = dead_weapon;
´´

That didn't work tho.

**Comment by tkcjesse** [comment]
I mean it's already being stored in life_gear or w/e dead_gear.

**Comment by SimZor** [comment]
Why not just not put it in a groupWeaponHolder or whatever then? And just store it in a variable and then retrieve it?

**Comment by tkcjesse** [comment]
At TOD your gear is saved to an array and the weaponholder is deleted. Then when revived your gear is taken from that array. Not sure how what you're saying is really any different?

**Comment by SimZor** [comment]
I think what I'm saying is the same as you. nvm.

One thing though, maybe we can call the stripdown function and then add all the gear back?

**Comment by tkcjesse** [comment]
@SimZor .....

https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/core/functions/fn_loadDeadGear.sqf#L29-L40

**Comment by SimZor** [comment]
Ok, so that is done already :D

Then something is slowing the script down so it doesn't do it quickly enough and sometimes just doesn't call the script at all...

**Comment by harmdhast** [comment]
Maybe we can use the damageHandler and when the player took enougth damage to die delete the weapons and return the damage.

**Comment by SimZor** [comment]
It still needs to load loadDeadGear and store The weapon in a variable

**Comment by harmdhast** [comment]
You can still save the gear before deleting the weapon

**Comment by SimZor** [comment]
Anyone have any clues on this? I think this is quite a serious bug.

**Comment by harmdhast** [comment]
It has always been there. So Idk

**Comment by SimZor** [comment]
I think this is a major bug, people can abuse this and dupe weapons.

**Comment by harmdhast** [comment]
I think we understood the impact of the problem. We still need to wait for admins to tag it as a bug and wait for more feedback

**Comment by BoGuu** [comment]
Fixed in #140

**Comment by tkcjesse** [comment]
Better leave proper documentation on why it was changed.

**Comment by SimZor** [comment]
Because weapons were not disappearing or not disappearing fast enough... @tkcjesse

**Comment by tkcjesse** [comment]
................................................................. Wow. Just wow.

**Comment by SimZor** [comment]
@tkcjesse lol
