### ISSUE TITLE
Medic can join Gang bug

### ISSUE THREAD

**Issue by numpty9989** [AsYetUntitled/Framework#118]
### Expected behaviour
Nothing

### Actual behaviour
when civ request Medic to join gang its allowed

### Steps to reproduce the behaviour 
as civ make gang send invite to a Medic, they accept you can see there marker 

No PRT Error

----

4.4R3 altis

latest (cant remember version no.)

Game version: 

Branch:

**Comment by Jawshy** [comment]
No side check: Altis_Life.Altis/core/gangs/[fn_gangInvitePlayer.sqf](https://github.com/AsYetUntitled/Framework/blob/98d19e4208ec199fbf27ea9f5e5132383eab7327/Altis_Life.Altis/core/gangs/fn_gangInvitePlayer.sqf) 

`STR_GNOTF_InviteSelf` also is not present in the [stringtable.xml](url).

**Comment by setoy** [comment]
https://github.com/AsYetUntitled/Framework/blob/98d19e4208ec199fbf27ea9f5e5132383eab7327/Altis_Life.Altis/core/gangs/fn_gangInvitePlayer.sqf#L19 Could also be changed to `isEqualTo`, right?

**Comment by SimZor** [comment]
What you are looking at is your player, _unit == player.

Just put if (_unit isEqualTo independent) exitwith...

**Comment by setoy** [comment]
What about that? Would also cover cops and east :p

``
if (!(side _unit isEqualTo civilian)) exitWith {hint localize "STR_GNOTF_OnlyInviteCivilian"};
``

**Comment by SimZor** [comment]
That would do it although I think you should do "playerside _unit isEqualTo civilian" only and not side

**Comment by BoGuu** [comment]
There already is a side check, but I'll double check when I'm home

**Comment by setoy** [comment]
> There already is a side check, but I'll double check when I'm home.
Why bother the server with it when you can check client-side? :p

**Comment by BoGuu** [comment]
@setoy

Playside gives you the side of the player local to the client, you couldn't use it to remotely check the side of a remote unit.

Anyway, like I said, there is already a side check **client-side**

**Comment by setoy** [comment]
Just checked this... When using the repo's gang system, the dropdown only shows civilians to be invited anyway. So there's no way a cop or medic could be invited because they're simply not shown in the selection list.

**Comment by BoGuu** [comment]
@setoy 

As per my last comment ;)

**Comment by BoGuu** [comment]
Can this be closed?

**Comment by Jawshy** [comment]
Where is this phantom "side check client-side"?

**Comment by setoy** [comment]
[Here](https://github.com/AsYetUntitled/Framework/blob/7ca0b5b6ec42f223f27fff185e1d841a702e7c1c/Altis_Life.Altis/core/gangs/fn_gangMenu.sqf#L49)

**Comment by SimZor** [comment]
#136

**Comment by SimZor** [comment]
Tested, not a bug. Can be closed.
