### ISSUE TITLE
Clothing Textures

### ISSUE THREAD

**Issue by LaocheXe** [AsYetUntitled/Framework#121]
Hello, sorry to post this here but wanted to know about adding a bunch of different textures to one piece (rangemaster, etc).

I notice in Config_Vehicles.hpp that there is a class called LifeCfgVehicles that has the car and the different textures, why not do the same for the clothing (LifeCfgClothing) in the Config_Clothing.hpp - Or is there another way?

Sorry for being an idiot for this, just wanted to know a little bit more about the clothing.

**Comment by Emma-L** [comment]
Please join the discord: https://discord.gg/g4DkYY2 and ask your question there. As this isn't an issue on the repo I'll be closing this :)
