### ISSUE TITLE
Airfield de Tanoa Civ Air Shop Spawn

### ISSUE THREAD

**Issue by LaocheXe** [AsYetUntitled/Framework#122]
### Expected behaviour
Air Assets should spawn

### Actual behaviour
Nothing spawns

### Steps to reproduce the behaviour 
1. Go to Airfield de Tanoa (Tanoa Mission) Civilian Air Shop and try to purchase a air asset

----

Mission version:  4.5

Launcher version: 
Launcher version: 1.5.138522

Game version: 1.64.138497

Branch: main / beta branch not specified

**Comment by Jawshy** [comment]
This is a known issue. Please search before posting. 

See also https://github.com/AsYetUntitled/Framework/issues/80.
