### ISSUE TITLE
Fixed translators

### ISSUE THREAD

**Issue by danielstuart14** [AsYetUntitled/Framework#125]
I was taking a look in some translations, and they were very wrong. 

 We should set fixed translators, one for each language at least. No google translate, if there isn't any translator for the language, just don't translate it. Adding it without someone that's native speaker will make the project seems less professional.

**Comment by tkcjesse** [comment]
This is what has been happening iirc

**Comment by Emma-L** [comment]
Some people who play can't speak English, I feel like if we just cut out every translation that is not done by an native speaker then we're no longer projecting a welcoming appearance to the effected players. 

Also 'less professional'...considering this has a discord that is usually full of drama, and the drama that surrounds this mission, I wouldn't worry about a few mistranslations ruining the professionalism. 

However, as Jesse said, Jawshy is currently trying to improve the translations.

**Comment by Jawshy** [comment]
We have had some helpful people do translations in the past, but multilingual people are few and far between and typically do not have the time to amend every translation. 

I see three options for doing the translations: 

1. **Google Translate** 
  - _Pros:_ 
    - Always available to use. 
  - _Cons:_ 
    - Unreliable translation accuracy. 
2. **Volunteers** (native speakers) 
  - _Pros:_ 
    - More accurate than Google Translate. 
  - _Cons:_ 
    - Can only volunteer so much time to so many translations. 
3. **Professional translations** 
  - _Pros:_ 
    - One-to-one translation accuracy. 
  - _Cons:_ 
    - Costs money. 

Thus far we have used a mix of the first two methods. I think the ideal option for us is to continue with getting help from native speakers for translations. The challenge is finding those with the time to commit to translating the stringtable which has over 1,000 entries.

**Comment by danielstuart14** [comment]
Well, I know it is too much to ask. 
 But at least a team with at least one users for each language. They don't need to translate everything, just help with some mistakes (google translate is full of it).

I'm closing it, but, think about it.
