### ISSUE TITLE
Admin Log View (New Feature Suggestion)

### ISSUE THREAD

**Issue by BrendanTHC** [AsYetUntitled/Framework#126]
Howsit All Just A New Feature Suggestion

A parser that allows admins to see logs within the game such as kill logs money logs etc so it is easier rather than having to access the server to view them

Regards
Archangel

**Comment by BoGuu** [comment]
> A parser

What do you mean here, in what manner?

If you wanted to add this personally for your server, you could direct any of the advanced logging stuff to log in the admin RPTs, and kills too (from EVH)

Not sure about for the Framework though

**Comment by BrendanTHC** [comment]
Im talking about a display in game which displays all advanced logs in game rather than just a text based

Boguu you can message me on discord

**Comment by SimZor** [comment]
This is not really something for the framework is it?

**Comment by BoGuu** [comment]
For reasoning in the comment above, going to close this. If you want something for your own server, shouldn't be hard to do.
