### ISSUE TITLE
Error in expression - fn_houseConfig

### ISSUE THREAD

**Issue by Jawshy** [AsYetUntitled/Framework#14]
The following message was written to the client/local.rpt log file when pressing the interaction key (Windows key) over a house that can be purchased: 
```
15:33:38 Error in expression <ig;

private _price = getNumber(_config >> "price");
private _numberCrates = if >
15:33:38   Error position: <>> "price");
private _numberCrates = if >
15:33:38   Error >>: Type Array, expected Config entry
15:33:38 File mpmissions\__CUR_MP.Altis\core\config\fn_houseConfig.sqf, line 22
```

#### Relevant file(s): 
- /core/config/[fn_houseConfig.sqf](https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/core/config/fn_houseConfig.sqf)

Mission version: 4.4r3 as of https://github.com/AsYetUntitled/Framework/commit/edec73b01b453bc6b1328402a6d73e57dba3ef44.

**Comment by BoGuu** [comment]
Which house was this on?
