### ISSUE TITLE
life_fnc_terrainsort isn't server side

### ISSUE THREAD

**Issue by Jason2605** [AsYetUntitled/Framework#144]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
No errors.

### Actual behaviour
Error Undefined variable in expression: life_fnc_terrainsort

### Steps to reproduce the behaviour 
1. TerrainSort serverside

### [RPT]http://hastebin.com/uqebifogeb.css

Just need to make it ServerSide
----

Mission version: <See core/init.sqf, briefingName in mission.sqm, or changelog in briefing.sqf for your mission version.>

Launcher version: <In the Arma 3 launcher go to ⚙ OPTIONS and click the version info below to copy it to your clipboard.>

Game version: 

Branch:

**Comment by SimZor** [comment]
Wtf? This is weird...doesn't have to be on server side. When I tested this it was all fine.

**Comment by tmoitoi** [comment]
Same problem

**Comment by SimZor** [comment]
Can you guys post full RPT's? @Jason2605 @tmoitoi 

I think this can have to do with some other problem, like a input after end of file.

**Comment by Jason2605** [comment]
This was not my error, like i said on the discord, i was told to create an issue about this. Cant actually tell you anything about it. @SimZor

**Comment by SimZor** [comment]
Oh ok didn't see in Discord. @Jason2605
