### ISSUE TITLE
Voice chat doesn't work

### ISSUE THREAD

**Issue by exploadead** [AsYetUntitled/Framework#148]
### Expected behaviour
Voice should work...

### Actual behaviour
Voice doesn't work in any channel. Though the parameter disableChannels is properly configured.

### Steps to reproduce the behaviour 
1. I just took the vanilla mission 4.4r4

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB2 logs (if applicable)
There're no errors about my issue... Also i can tell that when players are trying to speak their lips are not moving... that's strange... And also at 4.4r3 voice works fine!

----

Mission version: 4.4r4

Launcher version: im not using launcher

Game version: 1.64

Branch: 138.497

**Comment by BoGuu** [comment]
4.4r4 is just 4.4r3 with the mres fix and SpyGlass/BE. So that there would be a contradiction, which leads me to believe this could be a fault on your end?

**Comment by Jawshy** [comment]
v4.4r3 (and thus also [v4.4r4](https://github.com/AsYetUntitled/Framework/releases/tag/4.4r3)) has the following in the [description.ext](https://github.com/AsYetUntitled/Framework/blob/2f93f49d475e14e06c00c91f8bc38376e7831360/Altis_Life.Altis/description.ext#L1): 

```cpp
disableChannels[]={0,1,2};
```

After v4.4r3 the [`disableChannels`](https://community.bistudio.com/wiki/Description.ext#disableChannels) syntax in _Arma 3_ was [changed](https://github.com/AsYetUntitled/Framework/commit/c7cd192d9daccb21bd160e345b677f9ba8742599). This is the [current syntax](https://github.com/AsYetUntitled/Framework/blob/c176bf37b39409a11a6418507209179266701c88/Altis_Life.Altis/description.ext#L1): 

```cpp
disableChannels[]={{0,true,true},{1,true,true},{2,true,true}};    // Disabled text and voice for global, side, and command channels. disableChannels[] = {{channelID<number>, disableChat<bool>, disableVoice<bool>}};
```

Check the above and try again, @exploadead.

**Comment by exploadead** [comment]
Realy sorry for being such dumb:) The deal was in a DisableVoN parameter in config file... It is all ok now! Thank you anyway!
