### ISSUE TITLE
Undefined variable life_preview_3D_vehicle_object

### ISSUE THREAD

**Issue by luudvkeulen** [AsYetUntitled/Framework#154]
Since I cannot commit changes I would like to inform a fix for this error.

You need to add `waitUntil {!isNil "life_preview_3D_vehicle_object"};`
Before the line `waitUntil {!isNull life_preview_3D_vehicle_object};`
In the file fn_vehicleShopInit3DPreview.sqf.

**Comment by Jawshy** [comment]
@luudvkeulen, anyone can submit a [pull request](https://help.github.com/articles/creating-a-pull-request/). Also, please follow the provided [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md). 

*Unnecessary disclaimer: Submitting a PR does not guarantee it will be merged.*

**Comment by BoGuu** [comment]
There is a reason for the issue template.
