### ISSUE TITLE
Error client log

### ISSUE THREAD

**Issue by SAYREXx** [AsYetUntitled/Framework#165]
11:42:56 Time was adjusted to keep it same as on server.
11:42:58 Error in expression <rivate ["_array"];
life_session_tries = life_session_tries + 1;
if (life_session>
11:42:58   Error position: <life_session_tries + 1;
if (life_session>
11:42:58   Error Undefined variable in expression: life_session_tries
11:42:58 File mpmissions\__CUR_MP.Altis\core\session\fn_requestReceived.sqf, line 12
11:42:58 Wrong init state
11:42:58 Attempt to override final function - bis_fnc_endmission
11:42:59 Error in expression <2\nlife_donorlevel: %3",life_adminlevel,life_coplevel,life_donorlevel]] remoteEx>
11:42:59   Error position: <life_coplevel,life_donorlevel]] remoteEx>
11:42:59   Error Undefined variable in expression: life_coplevel
11:42:59 File mpmissions\__CUR_MP.Altis\core\session\fn_requestReceived.sqf, line 29

**Comment by Jawshy** [comment]
@SAYREXx, I am going to close this issue until you edit it to follow the provided [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md). 

> \<If you are reporting a bug then you must use the provided issue template.>
