### ISSUE TITLE
[Suggestion] More realistic tazer

### ISSUE THREAD

**Issue by Repentz** [AsYetUntitled/Framework#167]
Is this where suggestions go? I hope if not feel free to move it or whatever.

I feel like the current tazing animation is a bit outdated, you just get put into an animation and float to the ground. 

I have created a rewritten version of it using a force ragdoll animation when hit, using assets from here: http://killzonekid.com/arma-scripting-tutorials-forced-ragdoll/
It also will set fatigue to 1 and damage the player to 60% so they limp.

Here is fn_tazed: http://hastebin.com/ocopugenac.bash
Here is the new file it calls to: http://hastebin.com/goxuwevuro.bash 
I placed it in core/session
I called it as a function here:  under file = "System\session"; place:
class tazeRagdoll {};

Feel free to change any credits I don't care, just thought something like this would be cool to see on servers in the future.

**Comment by Jawshy** [comment]
Thanks for the suggestion, @Repentz. This looks like a significant improvement over the current static animation. However, I do have some questions: 

1. Is there a significant impact on client performance? 

2. Would replacing [`setFatigue`](https://community.bistudio.com/wiki/setFatigue) and [`setDamage`](https://community.bistudio.com/wiki/setDamage) with [`forceWalk`](https://community.bistudio.com/wiki/forceWalk) not achieve the same effect? It would be disabled thereafter to allow normal movement.

**Comment by Repentz** [comment]
- Setdamage is to give more realism to being hurt by tazer, you or them also have the option of healing, and I haven't noticed any issues with performance, people ragdoll all over with lots of servers anti vdm scripts.

**Comment by trinitynet** [comment]
> people ragdoll all over with lots of servers anti vdm scripts.

not gunna lie... kinda wanna see that

**Comment by H0lidays** [comment]
@Repentz could you please update your code on pastebin ? hastebin codes are deleted 10days after creation :)

**Comment by Jawshy** [comment]
>@Repentz could you please upload your code on pastebin ? hastebin are deleted 10days after creation :) 

I would suggest using GitHub [Gist](https://gist.github.com/) over third-party services.

**Comment by BoGuu** [comment]
The issues are not a place for this @H0lidays - contact him over Discord etc.
