### ISSUE TITLE
Error with setPlayTime

### ISSUE THREAD

**Issue by H0lidays** [AsYetUntitled/Framework#168]
### Expected behaviour
Pushing played time to DB ?

### Actual behaviour
It's spamming my RPT, don't know if it's breaking my server but actually nothing happened.

### Steps to reproduce the behaviour 
Just wait for the server to init

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB2 logs (if applicable)
http://hastebin.com/udezonoful.tex
----

Mission version: 4.5

Launcher version: 1.5.138680

Game version: 1.64.138732

Branch: main / beta branch not specified

**Comment by H0lidays** [comment]
Definitely generating errors.
`Error in expression <[0,<null>,0]>
  Error position: <<null>,0]>
  Error Invalid number in expression
Error in expression <[0,<null>,0]>
  Error position: <<null>,0]>
  Error Invalid number in expression
Error in expression <y = call compile format ["%1", _array];
_array;>
  Error position: <_array;>
  Error Undefined variable in expression: _array
File life_server\Functions\MySQL\fn_mresToArray.sqf, line 26
Error in expression <playtime_values_request pushBack [_uid, _new];
};
[_uid,_new select 2] call TON_>
  Error position: <_new];
};
[_uid,_new select 2] call TON_>
  Error Undefined variable in expression: _new
File life_server\Functions\MySQL\fn_queryRequest.sqf, line 120
Error in expression <) isEqualTo _uid) exitWith {
_x set [1, _time_gathered];
_x set [2, time];
};
} >
  Error position: <_time_gathered];
_x set [2, time];
};
} >
  Error Undefined variable in expression: _time_gathered
File life_server\Functions\PlayTime\fn_setPlayTime.sqf, line 24
Error in expression <elect 12)] call DB_fnc_mresToArray;
if (_new isEqualType "") then {_new = call c>
  Error position: <_new isEqualType "") then {_new = call c>
  Error Undefined variable in expression: _new
File life_server\Functions\MySQL\fn_queryRequest.sqf, line 113
`
all of these errors are related with setPlayTime. generates an mresToArray error. double check'd the code, nothing special.

**Comment by baua1310** [comment]
are you using the default files?

**Comment by H0lidays** [comment]
for what ? life_server ? if, yes sir

**Comment by SimZor** [comment]
This is an issue that will happen at certain times, but not consistent. Atleast when I tested the master repo.

As to what is causing this, I don't know. Certainly something weird.

**Comment by BoGuu** [comment]
This is something I can never reproduce since I fixed the current implementation. It seems to work on all servers I am in contact with too.

If anyone wants to shed some reproduction steps (or further causes/logs), that would be good

**Comment by SimZor** [comment]
@BoGuu are you talking about the Mres fixes?

**Comment by BoGuu** [comment]
@SimZor

No, when play time was first introduced it was horribly broken. I fixed that, and I've seen no issues with it personally since

**Comment by jordanlee833** [comment]
No longer an issue as of https://github.com/AsYetUntitled/Framework/tree/fb3eaab74bceda607b99a7d9fc9b00a14dc3f5eb
