### ISSUE TITLE
House Garages dont work right

### ISSUE THREAD

**Issue by nflug** [AsYetUntitled/Framework#170]
### Expected behaviour
House Garage Spawns should work and no cars spawn into the house

### Actual behaviour
The House Garages spawns cars into houses

### Steps to reproduce the behaviour 
1. Buy a House with Garage . Park a Car in it. And park it out. EXPLODE!!!

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB2 logs (if applicable)

----

Mission version: 4.4

**Comment by BoGuu** [comment]
I tidied up your issue, the template is there so you can structure them better.

Which house was this with (classname)?

**Comment by nflug** [comment]
Sorry for that Bad English.
Its Land_House_Big_03_F in The mid of Tanoa LaRochelle

**Comment by nflug** [comment]
Its a Big Blue one with a Garage in it

**Comment by BoGuu** [comment]
Are you using the vanilla build?

**Comment by nflug** [comment]
Yes im using the newest Vanilla build

**Comment by nflug** [comment]
Its not only in that House

**Comment by Jawshy** [comment]
> Its not only in that House

@nflug, could you please specify all of the house-garage combinations that have this issue?

**Comment by nflug** [comment]
Land_Hotel_01_F 
Land_Hotel_02_F 
Land_GarageShelter_01_F 
Land_House_Big_02_F 
Land_School_01_F 
Land_House_Big_04_F 
Land_House_Big_03_F 

Try it one multiple houses. I think if the house face shows to north and you have a position, its an other Position if the house face shows to east or something like that.

**Comment by BoGuu** [comment]
That's why some positions were blacklisted, hmm.. What vehicle?

**Comment by nflug** [comment]
Every Vehicle. SUV, Hunter etc. It spawns in the House or just on the balcony and explodes

**Comment by nflug** [comment]
Lol, fixed it. It was the vehicleGarage.sqf that was broken.

**Comment by BoGuu** [comment]
Is this a problem on your end, or the Framework? If the latter, would you mind explaining?

**Comment by nflug** [comment]
Ok it isnt Fixed for me. I replaced The vehicleGarage.sqf but it Spawns at some big houses with Garages in The House lol.

**Comment by BoGuu** [comment]
For every house of those types? Which?

**Comment by nflug** [comment]
Yes you can join my Server to test it if you want

**Comment by RoguePA** [comment]
nflug these guys are gonna need a lot more info from you if they're going to help you, you're being quite vague

**Comment by nflug** [comment]
Info about what? I Said The House Types.

**Comment by nflug** [comment]
I've tested it now on the newest Vanille version and the car explodes anyway...

**Comment by BoGuu** [comment]
Need to verify this before we can do anything. When it was originally made, worked fine

**Comment by DomT602** [comment]
Due to the lack of activity and that the issue was not confirmed, this will be closed.
