### ISSUE TITLE
Tazing a cop/medic heals him

### ISSUE THREAD

**Issue by DardoTheMaster** [AsYetUntitled/Framework#171]
Just to point this out,this is a very low priority issue.

### Expected behaviour
The action gets ignored

### Actual behaviour
The tazer fully heals the target

### Steps to reproduce the behaviour 
1. Shoot a cop/medic with damage different from 0
2. He will get healed

https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/core/functions/fn_handleDamage.sqf#L43

----

Mission version: ~~Latest~~ v5.0.0 as of [a9681c7](https://github.com/AsYetUntitled/Framework/tree/a9681c74df08a9fea9614e2f528a196f636d9f30) 

Edit: Added exact mission version -- @Jawshy

**Comment by Jawshy** [comment]
I believe that this issue is as old as the mission itself. Nonetheless, thanks for the report, @DardoTheMaster.

**Comment by BlackFisch** [comment]
I already created a fix for this in my mission and would share it with you. 
In fn_survival.sqf just add this inside the for-loop:

> /* Check damage of the player unit (used for handleDamage) */
> if (damage player != _lastDamage) then {
> 	life_unitDamage = damage player;
> 	_lastDamage = life_unitDamage;
> };

and in the fn_handleDamage.sqf just replace every 
> _damage = 0; 

with 

> _damage = life_unitDamage;

should work fine :)

**Comment by SimZor** [comment]
@BlackFisch you could do a PR if you want :)

**Comment by DomT602** [comment]
Thankyou @DardoTheMaster  for reporting this. As above this issue has been sorted via #482. We appreciate your help in improving the framework!
