### ISSUE TITLE
Skill System (Configable)

### ISSUE THREAD

**Issue by DuckyDoesCode** [AsYetUntitled/Framework#174]
Just wanted peoples ideas as I will work on it myself, also whether it is actually wanted or not...

works of an XP system in which you get xp for playtime, doing different things robbing the fed, escaping jail, sending someone to jail etc

### Skill Categories
Lock-picking - (Only for civs)
Repairing
Healing
Food
Thirst
Processing
Picking
Bartering
Stamina (If Stamina Is Enabled)

**Comment by Repentz** [comment]
Sounds good

**Comment by Jawshy** [comment]
As with other suggestions for new features I do not think this belongs within this framework. It should be kept as something that server admins can add themselves if they wish to do so.

**Comment by DuckyDoesCode** [comment]
I just feel that is is something that could change the way altis life is played just like many other "NON-FRAMEWORK" things have been added in the past the whole idea is to add a base framework in which players can customize all I'm suggesting is having a base framework that has very little code and can easily be configured and turned off

**Comment by SimZor** [comment]
I agree with @Jawshy on this one. It would be way to much code just to be in there if someone were to disable it. 

One thing we got to remember aswell is that this is just a framework, it should have the bare minimum, be optimised and not be bloated with features.

**Comment by DuckyDoesCode** [comment]
Did you not just read my comment how is having a base framework of the code tooo much code.... this is a FRAMEWORK is it not? @SimZor

**Comment by SimZor** [comment]
It's a framework. A experience system would require some code which would just sit in there if disabled. Also, server owners should put in some effort themselves.

And no, did not see your comment before I made one.

**Comment by NeFShARk** [comment]
@DuckyDoesCode Sounds good 👍

**Comment by majoess** [comment]
Not for a framework. Make it yourself.

**Comment by DuckyDoesCode** [comment]
@majoess IVE SAID I'M GOING TO MAKE IT... When will people learn to read

**Comment by BoGuu** [comment]
See #111. Sorry ;)

@majoess Ok boss!

**Comment by majoess** [comment]
@DuckyDoesCode I can read. Just do not make some system like that public.
NO.UNIQUE.SERVER.ANYMORE

**Comment by DuckyDoesCode** [comment]
@majoess tell me ONE server that has a skill system like this and does not have loads of other unique features...

**Comment by imKLM** [comment]
i used to have one with only a skill system in as additional scripts, no longer around mind...

Either way chill out..
