### ISSUE TITLE
Error in stringtable

### ISSUE THREAD

**Issue by H0lidays** [AsYetUntitled/Framework#176]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
Returning names of crimes

### Actual behaviour
Not returning names of crimes

### Steps to reproduce the behaviour 
Done nothing, by default.

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB2 logs (if applicable)
No RPT

###Explanation
In stringtable, STR_Wanted_Count.
`<French>%1 chef (s) de 2%/French>`
have to be changed to
`<French>%1 chef (s) de %2</French>`

`<Italian>%1 count (s) del 2%</Italian>`
have to be changed to
`<Italian>%1 count (s) del %2</Italian>` (Thanks to @Lokiro67)

Also, if you are needing a French guy who wants to traduct stringtable, I'm free ATM :)
----

Mission version: 4.5(only tested in 4.5)

Launcher version: 1.5.138680

Game version: 1.64.138732

Branch: main / beta branch not specified

**Comment by Lokiro67** [comment]
In stringtable, STR_Wanted_Count.
<;Italian>%1 count (s) del 2%</Italian>
have to be changed to
<;Italian>%1 count (s) del %2</Italian>

;)

**Comment by H0lidays** [comment]
Missed it, thanks ! :D

**Comment by BoGuu** [comment]
We have a pull request system ;)

**Comment by Jawshy** [comment]
Thanks for the issue report and for following the issue template. This issue will be closed once pull request https://github.com/AsYetUntitled/Framework/pull/177 is merged.

**Comment by Jawshy** [comment]
> Also, if you are needing a French guy who wants to traduct stringtable, I'm free ATM :)

@H0lidays, we would certainly appreciate help with the stringtable localisations. You are welcome to check the French translations for accuracy and to submit a pull request with any fixes. 

If you need any help with working with Git and on GitHub then check out [GitHub Help](https://help.github.com/).
