### ISSUE TITLE
Repair kit and medpack not working

### ISSUE THREAD

**Issue by condolent** [AsYetUntitled/Framework#180]
Repairing cars with repair kit doesn't work and you can't revive dead players as EMS with a medpack. Heard people talking about that it's broken now? Anyone been able to fix it?

**Comment by H0lidays** [comment]
Following the issue template would be a nice beginning.

**Comment by SimZor** [comment]
Use virtual items instead

**Comment by SimZor** [comment]
This is not an issue

**Comment by Jawshy** [comment]
As stated by @SimZor, the physical [toolkit](https://community.bistudio.com/wiki/Arma_3_CfgWeapons_Items#ToolKit) and [medikit](https://community.bistudio.com/wiki/Arma_3_CfgWeapons_Items#Medikit) were replaced with the toolkit and defibrillator virtual items. See commits https://github.com/AsYetUntitled/Framework/commit/3cea84ec80efc2d523d69557b6932a46805cd174 and https://github.com/AsYetUntitled/Framework/commit/02a6ea6a55c8bd9698bc06f1046c93c268da00ad. 

Dead players waiting to be revived need to click the "request medic" button for them to be able to be revived by a medic or police officer. 

@condolent, you **need** to follow the provided [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md). It is there to help you neatly provide as much information as possible to help diagnose the issue.
