### ISSUE TITLE
[Suggestions] About the ability for civs to revive others

### ISSUE THREAD

**Issue by NeFShARk** [AsYetUntitled/Framework#188]
**Toggle Option: Ability for civs to revive others** #146

**1** - Idk if this is relevant or not, its just an idea! I think that we need a check for "online medics", if there is a certain number of medics online at the moment then the player will not be able to revive others or be revived by others! They(the dead civ and the one trying to revive him) will then receive a message saying that they need to call a medic.

Also the "minimal number of medics" for this check should be add to the config so anyone using the framework will be able to set how many medics needs to be online for this check to be disabled or enabled, just like the minimal number of cops for the players to rob the federal reserve.

I think this is important because the ability for civs to revive others could make the "medics role" somewhat irrelevant since most players that play altis life usually play with other people in groups, what i mean by this is that the civs will choose to revive each other instead of calling a medic even if there are a lot of medics online.

Of course that this feature(ability for civs to revive others) is important! It sucks when there is no medics online and someone dies and they want to be revived because they don't want to lose their gear, when this happens, usually these players keep bothering the admins about it.

**2** - I also think that if a player request a medic using the "request medic button" then he can't be revived by another civ, in others words, it's another check to prevent a player to revive another player if this player requested a medic, each one of them(the civs, the dead one and the one trying to revive him) would then receive a message saying "You can't be revived by another civ because you requested a medic" and "You can't revive this civ because he requested a medic".

\/ Another suggestion, idk, maybe this one is not valid and it would take to much to be done but anyway \/

**3** - The suggestion is that along with the medics online check, you also add a distance check, if there aren't any medics in a X distance from the target(in this case the dead civ), then another civ can revive him, if there are medics in this X distance from the target, then he needs to call a medic! Again the civs, each one of them would receive a message like "You can't revive this civ, there medics in range, he needs to call one!" and "You can't be revived by another civ because there are medics in range, call one!".

/\ I suggested this because sometimes is a pain in the ass to wait for a medic to arrive when there are medics online because they are to far from the target, altis map and tanoa are pretty big! It's even worse when you are playing on a server that doesn't allow every medic to use helicopters.

Idk, what you guys think? Maybe it's to much hehe :P Anyway these are suggestions only :P

PS: I did not use the issue template because this feature is not "in" yet, in other words, it hasn't been merged yet.

**Comment by SimZor** [comment]
If something like this decides to be implemented im up for doing all this. So if you want you can assign this to me @BoGuu @Jawshy

**Comment by NeFShARk** [comment]
As @SimZor said in the PR that i'm talking about in this Suggestion:

"allowing civs to revive players without them requesting medic could be quite abused IMO."

That is in "conflict" with my second suggestion. I've made the second suggestion because this feature could lead to medics going around the map to revive others but when they arrive at the location there is nobody to be revived because the dead civ has already been revived by another civ. 

Maybe this can be solved by adding another dialog button(like the request medic button) on the "death" screen for the civ that is dead to enable\allow others civs to revive him? Or if the civ is revived, the medics then get a new notification saying that the dead civ\civs was\were revived and the red marker that shows the medics where the civ died would then turn green and disappear after some time?

The second solution, the one about the notification and marker would also be useful for the medics between themselves, because I've notice that sometimes their communication sucks, in other words, a medic goes to the red marker and revice a civ, moments later another medic arrives at the location but there is no civ to be revived haha.

Ideas?

**Comment by NeFShARk** [comment]
No one is going to comment something about this?

Merry Christmas and Happy New year!

**Comment by BoGuu** [comment]
Merged already #146

**Comment by NeFShARk** [comment]
#146 was merged but these suggestions are still valid, are they not? But since no one says anything or seems to care about this, this might as well get closed indeed.

**Comment by BoGuu** [comment]
Sorry, I'm currently very busy at the moment, and was trying to clear up some issues/PRs, from the PR link in the title and SimZor's comment I assumed this was seen to. I'll take another read of it all when I can and see what we can do.

**Comment by NeFShARk** [comment]
Nah, no problem :) I saw you working like a machine on the PRs, I've got several e-mails haha! I good to clear them indeed, since several have been around for a long time and some are not valid anymore.

**Comment by DirectGaming** [comment]
I disagree in this suggestion, that is why EMS is there!

**Comment by NeFShARk** [comment]
@DirectGaming I think that you didn't read this issue\suggestion at all! I'm pretty sure that you just read the title! The ability for civs to revive other civs has already been merged, see #146! I think you should read the entire issue\suggestion, not just the title, then you can give an opinion about it :) and it will be very much welcome.

I created this issue\suggestion with the sole objective to prevent the roles of the EMS to become irrelevant, and also to improve how these two features will work together, without the two of them creating more problems than it solves.

**Comment by Jawshy** [comment]
Closing old issue ticket.
