### ISSUE TITLE
Clothing Shop - Free Clothing

### ISSUE THREAD

**Issue by rebornfuel** [AsYetUntitled/Framework#191]
Expected behaviour

When using the clothing shop, you should not be able to get clothing for free.

Actual behaviour

There is a sequence, if repeated allows you to get free clothing regardless of price and how much money you have on you.

Steps to reproduce the behaviour

1. stand in front of the clothing shop/rebel shop NPC
2. hold down the key that the clothing item begins with ie G for Ghillie, or F for fatigues or whatever you want but dont click on anything.
3. used the mouse scroll wheel to highlight the open clothing shop on the NPC, while still holding the letter key.
4. use the mouse wheel button to open the clothing shop, while still holding the letter key.
5. when the menu opens you will see it has taken you to the first item of clothing that begins with the letter you are holding, so while still holding the letter key press escape.
6. check your inventory and you will be wearing the clothing.

RPT and/or extDB2 logs (if applicable)
N/A

Mission version:
4.4R3 & 4.4R4

Launcher version:
N/A

Game version:
N/A

Branch:
N/A

**Comment by H0lidays** [comment]
Getting the same issue on 4.5

**Comment by BoGuu** [comment]
Testing a fix for this now

**Comment by rebornfuel** [comment]
I have tested it all seems to work for me.

**Comment by BoGuu** [comment]
Check the changes in 2747463eb362b4d1173ddd842db68f50ecfd7c93

**Comment by BoGuu** [comment]
Assuming fixed
