### ISSUE TITLE
Update animate to animateSource

### ISSUE THREAD

**Issue by Jawshy** [AsYetUntitled/Framework#192]
Update all uses of [`animate`](https://community.bistudio.com/wiki/animate) to [`animateSource`](https://community.bistudio.com/wiki/animateSource) because it is better. 

#### Files to update: 
- [x] [Framework/Altis_Life.Altis/core/functions/fn_keyHandler.sqf](https://github.com/AsYetUntitled/Framework/blob/bee14a1317248b1844ada3411c585c55623bef43/Altis_Life.Altis/core/functions/fn_keyHandler.sqf)  
- [x] [Framework/Altis_Life.Altis/core/cop/fn_doorAnimate.sqf](https://github.com/AsYetUntitled/Framework/blob/98d19e4208ec199fbf27ea9f5e5132383eab7327/Altis_Life.Altis/core/cop/fn_doorAnimate.sqf) 
- [x] [Framework/Altis_Life.Altis/core/housing/fn_lockupHouse.sqf](https://github.com/AsYetUntitled/Framework/blob/98d19e4208ec199fbf27ea9f5e5132383eab7327/Altis_Life.Altis/core/housing/fn_lockupHouse.sqf) 
- [x] [Framework/Altis_Life.Altis/core/housing/fn_copBreakDoor.sqf](https://github.com/AsYetUntitled/Framework/blob/98d19e4208ec199fbf27ea9f5e5132383eab7327/Altis_Life.Altis/core/housing/fn_copBreakDoor.sqf) 
- [x] [Framework/Altis_Life.Altis/core/cop/fn_repairDoor.sqf](https://github.com/AsYetUntitled/Framework/blob/98d19e4208ec199fbf27ea9f5e5132383eab7327/Altis_Life.Altis/core/cop/fn_repairDoor.sqf) 
- [x] [Framework/life_server/init.sqf](https://github.com/AsYetUntitled/Framework/blob/33213795c08f082fecd048ced786f06e3580f3c4/life_server/init.sqf)

**Comment by BoGuu** [comment]
Waiting on #193 merge
