### ISSUE TITLE
webseite

### ISSUE THREAD

**Issue by T4ss** [AsYetUntitled/Framework#198]
hi

website down or hacked ? 

greetings

**Comment by imKLM** [comment]
down for a re-install

**Comment by NeFShARk** [comment]
Use this one for the time being.

https://www.altisliferpg.com/

**Comment by T4ss** [comment]
thx imklm

**Comment by Emma-L** [comment]
@NeFShARk perhaps don't advertise random websites on the repo ;)

**Comment by Jawshy** [comment]
@T4ss, asking about the status of a website is **not** the purpose of [issues](https://help.github.com/articles/about-issues/). Join the [ArmA RPG Life Discord](https://discordapp.com/invite/sEcQdPn) ([contact](https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md#contact)) if you wish to keep up-to-date with what is happening on the [forums](https://armarpglife.com/forums/). 

As a side note, the **only** forums officially affiliated with this repository and Discord server is https://armarpglife.com/forums/.
