### ISSUE TITLE
Update my fork from the framework

### ISSUE THREAD

**Issue by WolfSkin1337** [AsYetUntitled/Framework#200]
Hello, how can I best update my fork from the framework at the "GitHub-Page"?
Can you explain to me the step by step?

Greetz WolfSkin

**Comment by Jawshy** [comment]
[Issues](https://help.github.com/articles/about-issues/). Are. Not. For. Support. 

Use [GitHub Help](https://help.github.com/) and ask on the [ArmA RPG Life Discord server](https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md#contact).
