### ISSUE TITLE
Buy Prices cant be loaded in Shops when Dynamicmarket is enabled!

### ISSUE THREAD

**Issue by MypowerHD** [AsYetUntitled/Framework#201]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
All works right.

### Actual behaviour
When i buy an item, the item costs 0.
When i disable the Dynamicmarket via "dynamic_market = false; //True enables Dynamic Market", all works right and the items have their current purchase price!

### Steps to reproduce the behaviour 
1. install Dynamicmarket to 4.5
2. go ingame and go into the supermarket or other shop who you can buy virtualitems.

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB2 logs (if applicable)
Client RPT http://hastebin.com/raw/melagumika
Server RPT http://hastebin.com/raw/ixifovoqir
----

Mission version: 4.5

Launcher version: ---

Game version: ---

Branch: dynamicmarket

**Comment by BoGuu** [comment]
We don't have a dynamic market?

**Comment by Jawshy** [comment]
GitHub [Issues](https://help.github.com/articles/about-issues/) are for reporting bugs and discussing ideas and enhancements **to the latest vanilla build of the framework.** You, @MypowerHD, are using an out-of-date and modified version of the framework as indicated by your client and server logs. 

If you are using https://github.com/AsYetUntitled/Framework/pull/64 then comment your issues on that pull request. 

[CONTRIBUTING.md → Issues](https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md#before-creating-a-new-issue-make-sure-to)
> #### Before creating a new issue make sure to... 
> [...] 
> * **...check that you are using the latest files from the master branch.** 
>   * If your files are behind then it is possible that the issue you are reporting has already been fixed in a recent commit. 
> * **...check that you have not modified the files from what is on the repository.** 
>   * If your files are different from what is on the repository then it is possible that a change that you made is what is causing the issue. 
> 
> [...]

**Comment by MypowerHD** [comment]
@Jawshy no problem sorry for my fault.

**Comment by Jawshy** [comment]
:ok_hand: Thanks for understanding.
