### ISSUE TITLE
Battleye PublicVariable/Script Restriction kick

### ISSUE THREAD

**Issue by thefuturechaos** [AsYetUntitled/Framework#205]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
Have working battleye filters that wont kick players upon joining

### Actual behaviour
Getting kicked for Script Restrictions and public variable restriction

### Steps to reproduce the behaviour 
Copy and pasted the provided Battleye filters

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB2 logs (if applicable)
#0 "this enableSimulation false; this allowDamage false; this addAction["BMW Shop",life_fnc_vehicleShopMenu,["civ_bmw",civilian,"civ"
 #4 "ble["bis_reviveParam_bleedOutDuration",-100]};
bis_revive_forceRespawnDuration = if ((missionNamespace getVariable["bis_revivePa"

----

Mission version: 3.1.4.8

**Comment by setoy** [comment]
`civ_bmw` is not a default variable, so this is the fault of your editing.

**Comment by thefuturechaos** [comment]
I also found out that im running an old version of altis life using the 4.4 battleye filter. Gonna try tomorrow!

**Comment by Jawshy** [comment]
@thefuturechaos, as mentioned by @setoy, there is no `BMW Shop` or `civ_bmw` variable in the vanilla framework. GitHub [Issues](https://help.github.com/articles/about-issues/) are only for reporting issues with the latest vanilla build of the framework as clearly stated [here](https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md#before-creating-a-new-issue-make-sure-to). Furthermore, support for version 3.1.4.8 ended... like... two years ago.
