### ISSUE TITLE
why didn't you guyz apply new library of BIS_fnc_param?

### ISSUE THREAD

**Issue by Hyunsuk-Baek** [AsYetUntitled/Framework#206]
BIS_fnc_param is deprecated, you know? 
why didn't change follow function yet? 
is there no problem? 

param, params. 
https://community.bistudio.com/wiki/BIS_fnc_param

**Comment by sargken** [comment]
because there is something even better than that https://community.bistudio.com/wiki/params

**Comment by sargken** [comment]
Why don't you help and submit a commit or pull request?

**Comment by BoGuu** [comment]
This is in the TODO (#128) if you had a look through. This will be one of the last things done before a new release (general cleanup).

**Comment by Hyunsuk-Baek** [comment]
i already applied . https://github.com/Hyunsuk-Baek/ddabongLife/commit/c11594debf26af7156df612c4dc0bf05d5017677

**Comment by BoGuu** [comment]
He wasn't referring to your own branch/build @Hyunsuk-Baek

**Comment by Jawshy** [comment]
I'll just leave this here: [CONTRIBUTING.md: Before creating a new issue make sure to...](https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md#before-creating-a-new-issue-make-sure-to)

> #### Before creating a new issue make sure to... 
> * **...check that the issue you are reporting does not already exist.** 
>   * If it does exist and it is still open then you may wish to add more information to that issue in a comment. 
>   * If it does exist but it has been closed then comment on **that** issue instead of creating a new one. An [organisation member](https://github.com/AsYetUntitled) will then decide if the issue needs to be reopened.
