### ISSUE TITLE
BattlEye setVariable Restriction

### ISSUE THREAD

**Issue by thefuturechaos** [AsYetUntitled/Framework#207]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
Working battleye

### Actual behaviour
Kicked

### Steps to reproduce the behaviour 
Added default filters and updated through the github 

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB2 logs (if applicable)
13.12.2016 14:37:14: Jack Dawson   - #0 "bis_fnc_selectrespawntemplate_respawned" = true 2:1750 C_man_1
13.12.2016 14:37:14: Jack Dawson   - #2 "bis_fnc_selectrespawntemplate_respawned" = true 2:1750 C_man_1
13.12.2016 14:37:14: Jack Dawson  - Value Restriction #0 "bis_fnc_selectrespawntemplate_respawned" = true 2:1750 C_man_1

----

Mission version: 4.4

**Comment by Jawshy** [comment]
@thefuturechaos, you should not be having this issue if you are using the [BattlEye filters](https://github.com/AsYetUntitled/Framework/tree/master/BEFilters) - specifically [setVariable.txt](https://github.com/AsYetUntitled/Framework/blob/19390397e90d9be14a3c1501276529cd709483f6/BEFilters/setVariable.txt) - that came with [version 4.4r1](https://github.com/AsYetUntitled/Framework/releases/tag/v4.4r1) or any more recent [mission version](https://github.com/AsYetUntitled/Framework/releases).

**Comment by thefuturechaos** [comment]
I just removed the filters and im just gonna use infistar!

**Comment by Jawshy** [comment]
![facepalm](https://cloud.githubusercontent.com/assets/10876578/21169773/f9e82a7a-c20a-11e6-885e-b9ee336b90bf.png)
