### ISSUE TITLE
Civ Spawning in Debug

### ISSUE THREAD

**Issue by thefuturechaos** [AsYetUntitled/Framework#208]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
Spawning in as civ 

### Actual behaviour
Civs are spawning in on debug island

### Steps to reproduce the behaviour 
Went and made sure all players were set as playable and civs are still spawning in debug, We get the option to choose where we spawn but no matter where we click we spawn in debug

----

Mission version: 4.4r3

**Comment by Jawshy** [comment]
I just download the files and launched a server with [version 4.4r4](https://github.com/AsYetUntitled/Framework/releases/tag/4.4r3) (same as 4.4r3), and I did not get this issue. This is most likely a fault on your end, @thefuturechaos. If you would like to join the [ArmA RPG Life Discord server](https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md#contact) then others may be able to help you diagnose this issue.

**Comment by H0lidays** [comment]
not getting it at all

**Comment by BrendanTHC** [comment]
what edits have you made to the framework if none get on discord and ill chat with you there and help you in whatever way possible

**Comment by BoGuu** [comment]
Assuming not a repo issue
