### ISSUE TITLE
Mission Completed after slot selection

### ISSUE THREAD

**Issue by amrasosy** [AsYetUntitled/Framework#209]
Hello i installed this work V5 but i have a problem, and sorry for my bad english. If i select any civ slot and then press ok , then i get sometimes mission completed error and back to the lobby, wenn i try join the server again i spawn on dubug island. RPT File: http://pastebin.com/6aTS12wr

**Comment by baua1310** [comment]
this is not the default mission:

`21:08:44 "------------------------------------------ Version 5.0.0 -------------------------------------------"
21:08:44 "----------------------------------------------------------------------------------------------------"
21:08:44 "----------------------------------------------------------------------------------------------------"
21:08:44 "               End of Altis Life Server Init :: Total Execution Time 0.0470009 seconds "
21:08:44 "----------------------------------------------------------------------------------------------------"
21:08:44 "compile init finished"
21:08:44 "======================================="
21:08:44 "aclogger is not present on the server , cheaters will not be logged in aclogger folder."
21:08:44 "======================================="
21:09:11 "------------- Client Query Request -------------"
21:09:11 "QUERY: SELECT playerid, name, cash, bankacc, adminlevel, donatorlvl, civ_licenses, arrested, civ_gear, civ_stats, civ_alive, civ_position, playtime FROM players WHERE playerid='76561198139276583'"
21:09:11 "Time to complete: 0.0400009 (in seconds)"
21:09:11 "Result: [""76561198139276583"",""Osman."",2.08547e+007,4.12126e+006,""5"",""1"",""[[`license_civ_driver`,1],[`license_civ_boat`,1],[`license_civ_pilot`,1],[`license_civ_trucking`,1],[`license_civ_gun`,0],[`license_civ_dive`,1],[`license_civ_home`,1],[`license_civ_admin`,1],[`license_civ_taksi`,1],[`license_civ_adac`,1],[`license_civ_oil`,1],[`license_civ_diamond`,1],[`license_civ_salt`,1],[`license_civ_sand`,1],[`license_civ_iron`,1],[`license_civ_copper`,0],[`license_civ_cement`,1],[`license_civ_medmarijuana`,0],[`license_civ_tutunisleme`,1],[`license_civ_altinisleme`,1],[`license_civ_meyvesuyu`,0],[`license_civ_alkolticaret`,0],[`license_civ_sisesut`,0],[`license_civ_pirinc`,1],[`license_civ_uzum`,1],[`license_civ_cocaine`,1],[`license_civ_heroin`,1],[`license_civ_marijuana`,0],[`license_civ_rebel`,1],[`license_civ_clanA`,1],[`license_civ_clanB`,1],[`license_civ_clanC`,1],[`license_civ_clanD`,1],[`license_civ_clanE`,1],[`license_civ_clanF`,1],[`license_civ_clanG`,1],[`license_civ_clanH`,1]]"",0,""[`U_C_Po
21:09:11 "------------------------------------------------"
21:09:48  Mission id: 0072024e7c5a5f2e1a4c72f298b8a49b8ac157a0
21:09:48 "########################## DYNAMIC MARKET ##########################"
21:09:48 "### >> CAN'T LOAD PRICES FROM DATABASE: ERROR 01x                ###"
21:09:48 "###        THE REQUESTED PRICEARRAY WAS UNEXPECTEDLY EMPTY!      ###"
21:09:48 "###        IF YOU ARE RUNNING DYNMARKET FOR THE FIRST TIME,      ###"
21:09:48 "###        PLEASE IGNORE THIS ERROR!                             ###"
21:09:48 "####################################################################"`

**Comment by NeFShARk** [comment]
First read:

> **Issues**
> 
> **Before creating a new issue make sure to...**
> 
> **...check that the issue you are reporting does not already exist.**
> If it does exist and it is still open then you may wish to add more information to that issue in a comment.
> If it does exist but it has been closed then comment on that issue instead of creating a new one. An organisation member will then decide if the issue needs to be reopened.
> **...check that you are using the latest files from the master branch.**
> If your files are behind then it is possible that the issue you are reporting has already been fixed in a recent commit.
> **...check that you have not modified the files from what is on the repository.**
> If your files are different from what is on the repository then it is possible that a change that you made is what is causing the issue.
> **...check that you can reproduce the issue.**
> If you cannot reproduce the issue then it can be very difficult to fix it.

Then use the issue template when reporting a problem - [Template](https://github.com/AsYetUntitled/Framework/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by Jawshy** [comment]
> Hello i installed this work V5 but i have a problem, and sorry for my bad english. If i select any civ slot and then press ok , then i get sometimes mission completed error and back to the lobby, wenn i try join the server again i spawn on dubug island. RPT File: http://pastebin.com/6aTS12wr

@amrasosy, as pointed out by @baua1310 and @NeFShARk, you are using a modified version of the framework. GitHub [Issues](https://help.github.com/articles/about-issues/) are only for reporting issues with the **latest vanilla build** of the framework. In future do fill out the whole [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/273f4e7bd21e5c8fca60d1095e8a24fc539d9d83/.github/ISSUE_TEMPLATE.md). "Bad English" is not an excuse. 

Furthermore, [version 5.0.0](https://github.com/AsYetUntitled/Framework/projects/1) is currently in development. You should only be using version 5.0.0 if you know what you are doing. If not then use a stable [release version](https://github.com/AsYetUntitled/Framework/releases).
