### ISSUE TITLE
Processing at gang hideout

### ISSUE THREAD

**Issue by AlaskaVet** [AsYetUntitled/Framework#21]
It seems that I cant get processing at gang hideout to work. Have the right drugs on me and I own the base but there was no action anywhere to process the drugs. And yes I tried the sink.

**Comment by Jawshy** [comment]
Any errors in RPT logs? Do your mission files exactly match the repository's files?

**Comment by AlaskaVet** [comment]
Yes I'm sure because I was testing it on the Official Tanoa Life server.
http://www.altisliferpg.com/topic/15395-tanoa-life-official-server-test-build/

**Comment by BoGuu** [comment]
Fixing in next update

**Comment by BoGuu** [comment]
#31
