### ISSUE TITLE
Refueling vehicle at a gas station does not deduct money

### ISSUE THREAD

**Issue by setoy** [AsYetUntitled/Framework#210]
### Expected behaviour
Money should have been deducted from either your wallet or your bank account when filling up your vehicle at a gas station.

### Actual behaviour
The vehicle gets filled up, however no money is deducted.

### Steps to reproduce the behaviour 
1. Get a car
2. Drive to a gas station
3. Fill up your car
4. Free gas. Wheeey.

----

Mission version: 5.0.0

Launcher version: ~~Yeah, dunno. At work. Latest.~~ 1.5.139.565 -- Edit: @Jawshy

Game version: ~~Yeah, dunno. At work. Latest.~~ 1.66.139586 -- Edit: @Jawshy

Branch: Stable

**Comment by Jawshy** [comment]
@setoy, is [`pump_service`](https://github.com/AsYetUntitled/Framework/blob/e908c08f622bda24de3bd9d9b1b39c223a7dc203/Altis_Life.Altis/config/Config_Master.hpp#L71) set to `true` in [Config_Master.hpp](https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/config/Config_Master.hpp)? If it is `true` then refuelling should cost money and it is done through a dialog. If it is `false` (default) then refuelling is free and there is no dialog.

**Comment by setoy** [comment]
Yep, it's set to `true` and the dialog appears.

**Comment by Jawshy** [comment]
I assume there were no errors or other relevant messages in the [arma.rpt file](https://community.bistudio.com/wiki/Crash_Files#Arma_3)?

**Comment by setoy** [comment]
If there were, I'd have posted them :p

Neither client nor server rpt showed anything.

**Comment by Jawshy** [comment]
I know; just double checking. 

I will try to reproduce this issue shortly.

**Comment by Jawshy** [comment]
I tried refuelling a Hatchback (Sport) and it cost $99 per litre from the bank account, but it should have cost [$80 per litre](https://github.com/AsYetUntitled/Framework/blob/e908c08f622bda24de3bd9d9b1b39c223a7dc203/Altis_Life.Altis/config/Config_Master.hpp#L72). :thinking: 

Using files as of [dfb5302](https://github.com/AsYetUntitled/Framework/tree/dfb53022915b8d2ff2cda10dbeb95aa035db87ac).

**Comment by setoy** [comment]
Prolly something to do with my low value of `1.4` for `fuel_cost` then

**Comment by BoGuu** [comment]
I looked into this around the time of issue creation, will take a second look. But it seemed to be deducting for me, just odd amounts

**Comment by BlackFisch** [comment]
this issue is due to the way of payment in the loop for the statusbar:
```SQF
if !((BANK - round(0.01 * _totalcost))> 0) exitWith {};
BANK = BANK - round((0.01 * _totalcost));
```

little workaround incoming as a PR, simply subtracting the difference on finish
