### ISSUE TITLE
BattlEye filters for DEV 5.0 are pretty fucked up!!?

### ISSUE THREAD

**Issue by Angrygargamel** [AsYetUntitled/Framework#214]
i just saw the be filters for the dev version
for example
`5 createDialog !\"altisPhone\" !\"Chop_Shop\" !\"DeathScreen\" !\"Federal_Safe\"`

all these `\"` on beginning and end of an exception are wrong...
(afaik - correct me if im wrong) an exception has always to start and end with "  without any \

5 createDialog !"altisPhone" !"Chop_Shop" !"DeathScreen" !"Federal_Safe"

and there are many more...

**Comment by Jawshy** [comment]
@Angrygargamel, the exceptions you listed for [`createDialog`](https://github.com/AsYetUntitled/Framework/blob/31d9648921c44dd9f904e8eda626102797c67163/BEFilters/scripts.txt#L4) in [scripts.txt](https://github.com/AsYetUntitled/Framework/blob/master/BEFilters/scripts.txt) are fine. 

Also, when reporting a bug or other issue please follow the [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md) that is provided.

**Comment by Angrygargamel** [comment]
wtf.... why are they !"altisPhone" now when i wrote them with the leading \
its listed as !\"altisPhone\" and that is wrong

**Comment by Jawshy** [comment]
[`\`](https://en.wikipedia.org/wiki/Backslash) is an [escape character](https://en.wikipedia.org/wiki/Escape_character).

**Comment by Angrygargamel** [comment]
which shouldnt be on the opening " and the closing "  or am i wrong?

**Comment by Jawshy** [comment]
They should be and they are.

**Comment by Angrygargamel** [comment]
since when should they be also on the opening and closing " because it was damn wrong before...
!"exception" was right
!\ "exception\ " was wrong

**Comment by Jawshy** [comment]
See [BattlEye Filters](https://github.com/AsYetUntitled/Framework/wiki/BattlEye-Filters). 

Are these filters causing false positives or false negatives, or are they only wrong in theory?

**Comment by Angrygargamel** [comment]
well if the wiki is right (and me too) then the filters are wrong there is no escape \ on leading/ending quotation marks
only within
so if its with escaping backslash before now even on leading and ending quotationmarks then the wiki is wrong (and me too)

**Comment by Jawshy** [comment]
[Framework/Altis_Life.Altis/core/shops/fn_chopShopMenu.sqf, line 21](https://github.com/AsYetUntitled/Framework/blob/ec8c51d8ef2595944bc58031b02c7884eef0e8db/Altis_Life.Altis/core/shops/fn_chopShopMenu.sqf#L21): 

```sqf
if (!(createDialog "Chop_Shop")) exitWith {hint localize "STR_Shop_ChopShopError"};
```

[Framework/BEFilters/scripts.txt, line 4](https://github.com/AsYetUntitled/Framework/blob/31d9648921c44dd9f904e8eda626102797c67163/BEFilters/scripts.txt#L4): 

```sqf
5 createDialog !\"altisPhone\" !\"Chop_Shop\" !\"DeathScreen\" !\"Federal_Safe\" !\"Life_Admin_Compensate\" !\"life_admin_menu\" !\"Life_atm_management\" !\"Life_cell_phone\" !\"Life_Clothing\" !\"Life_Create_Gang_Diag\" !\"Life_FuelStat\" !\"Life_impound_menu\" !\"Life_key_management\" !\"Life_My_Gang_Diag\" !\"life_news_broadcast\" !\"life_spawn_selection\" !\"life_ticket_give\" !\"life_ticket_pay\" !\"Life_Vehicle_Shop_v2\" !\"life_wanted_menu\" !\"life_weapon_shop\" !\"pInteraction_Menu\" !\"playerSettings\" !\"RscDisplayCamera\" !\"RscDisplayDebugPublic\" !\"RscDisplayWelcome\" !\"RscGUIEditor\" !\"SettingsMenu\" !\"shops_menu\" !\"TrunkMenu\" !\"vInteraction_Menu\"
```

The exception - `!\"Chop_Shop\"` - is for `"Chop_Shop"`. This is to say that the `"` (quotation marks) are a part of the exception which is intended and is correct. The following would also work as exceptions: `!"Chop_Shop"` and `!Chop_Shop`.

**Comment by Angrygargamel** [comment]
the wiki also says:
As it contains spaces it will need to be enclosed within quotation marks like so:

`"\"_side\",\"_struct\"];\ndisableSerialization;\n\ncloseDialog 0;\ncreateDialog 'playerMenu';\n\n_inv = ((findDisplay 20057) displayCtrl 15"`

so this tells me... no quotationmarks with escaping chars on start and end of the exception string

**Comment by Angrygargamel** [comment]
alright... i have read the wiki again and your posts again.... i guess now i get it...
i was just confused because i have never seen filters done this way before

so this issue can be closed i guess
