### ISSUE TITLE
Cop cars does not work

### ISSUE THREAD

**Issue by mur202** [AsYetUntitled/Framework#219]
As a police officer you are not able to buy cars. I belive that it checks if the officer has a driver license,(only suppost to do this for civs)

this was checked at the newest version of altislife

**Comment by NeFShARk** [comment]
Please, use the [issue template](https://github.com/AsYetUntitled/Framework/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by WolfSkin1337** [comment]
#164

**Comment by Jawshy** [comment]
@mur202, as @NeFShARk said, please follow the provided [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md). It is there for a reason. 

Also see the pull request that @WolfSkin1337 linked (https://github.com/AsYetUntitled/Framework/pull/164).
