### ISSUE TITLE
Air Shops

### ISSUE THREAD

**Issue by AlaskaVet** [AsYetUntitled/Framework#22]
Air shops are not working. Nothing shows up inside and I get a error.
` 3:23:16 Error in expression < _x select 1;
_levelName = _levelAssert select 0;
_levelType = _levelAssert sele>
 3:23:16   Error position: <select 0;
_levelType = _levelAssert sele>
 3:23:16   Error select: Type Number, expected Array,String,Config entry
 3:23:16 File mpmissions\__CUR_MP.Tanoa\core\shops\fn_vehicleShopMenu.sqf, line 51`
Video can be found [here](http://plays.tv/video/5793576bf0df1b6e83/error-at-airshop)

**Comment by AlaskaVet** [comment]
I was testing this out on the Official Tanoa Life server.
http://www.altisliferpg.com/topic/15395-tanoa-life-official-server-test-build/

**Comment by BoGuu** [comment]
Fix inc

**Comment by BoGuu** [comment]
#31 - Post if problem persists (server updated)
