### ISSUE TITLE
Defibrillator can only be used once as Medic

### ISSUE THREAD

**Issue by WolfSkin1337** [AsYetUntitled/Framework#222]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
Defibrillator can used more as once as Medic

### Actual behaviour
Defibrillator can only be used once as Medic

### Steps to reproduce the behaviour 
1. as medic buy a defi
2. as medic revive a dead people
3. it works
4. as medic attempt revive a other dead people
5. it not works

----

Mission version: ~actual~ v5.0.0 WiP https://github.com/AsYetUntitled/Framework/commit/a1911918f806457feede61df80632925cc97e4c5

Launcher version: ~actual~ 1.5.139565

Game version: ~actual~ 1.66.139586

Branch: ~actual~ main

**Comment by Jawshy** [comment]
Thanks for the report, @WolfSkin1337. I assume that "actual" means the current version so I will just edit that now for posterity. 

Is the defibrillator consumed after the first player is revived?

**Comment by WolfSkin1337** [comment]
yes it is the current version, i work with this. 👍

no the defi is not consumed.

**Comment by Angrygargamel** [comment]
in real life a defibrillator also isnt "consumed" after use... it needs to charge the battery maybe... but its not gone like a bandage or something out of a medikit

**Comment by Jawshy** [comment]
@WolfSkin1337, could you update to https://github.com/AsYetUntitled/Framework/commit/13de8d07a83748d32fd4c9ce26ed2d0f7ba90586 and then try to reproduce this issue?

**Comment by WolfSkin1337** [comment]
@Jawshy ok i will tested in the next time with this changes!

**Comment by jordanlee833** [comment]
Not a bug in the latest build.

**Comment by WolfSkin1337** [comment]
its old and is fixed by [https://github.com/AsYetUntitled/Framework/commit/13de8d07a83748d32fd4c9ce26ed2d0f7ba90586](url)
