### ISSUE TITLE
Cop/Civ Lose gear on revive

### ISSUE THREAD

**Issue by thefuturechaos** [AsYetUntitled/Framework#224]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
When someone gets revived they keep their gear and dont lose everything

### Actual behaviour
either revived through EMS or infistar players will be revived into the  same gear they have when they first join ( i.e just the clothing)

### Steps to reproduce the behaviour 
1. Kill somebody
2. Revive them

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB2 logs (if applicable)
<Check your client and server RPT and extDB2 logs for errors and warnings.>
<If there are relevant messages and they are short then post them here with code formatting.>
<If there are relevant messages and they are long then upload the whole file to GitHub, Pastebin, or Hastebin.>

----

Mission version: 4,4r3

Launcher version: <In the Arma 3 launcher go to ⚙ OPTIONS and click the version info below to copy it to your clipboard.>

Game version: 1.64

Branch:

**Comment by SimZor** [comment]
First of all, this framework does not support InfiShit. Second of all, you're using an older version of the framework which was an issue in. This is not an issue in the latest build.

Update your version to the latest.

This could be closed.

**Comment by thefuturechaos** [comment]
@SimZor After talking to jawsh he told me which file to replace and that still didnt fix it which is why i brought to the github

**Comment by SimZor** [comment]
@thefuturechaos Try to reach me on Discord and I'll help you. I just tried to reproduce your issue on the current build without succeeding.

**Comment by thefuturechaos** [comment]
@SimZor Yea ill head on

**Comment by Jawshy** [comment]
@thefuturechaos 

> Game version: 1.64

:open_mouth: The latest version of _Arma 3_ is [1.66](https://dev.arma3.com/post/spotrep-00063). 

As per [CONTRIBUTING.md](https://github.com/AsYetUntitled/Framework/blob/cf8603c9b047f596a9e0067448fceae29eb6cf76/.github/CONTRIBUTING.md): 

> * **...check that you are using the latest files from the master branch.** 
>   * If your files are behind then it is possible that the issue you are reporting has already been fixed in a recent commit. 
> * **...check that you have not modified the files from what is on the repository.** 
>   * If your files are different from what is on the repository then it is possible that a change that you made is what is causing the issue. 

As @SimZor said this should not be an issue on the latest development build so I will mark this as `needing-confirmation` for now, but this will likely be closed.

**Comment by Lylie14** [comment]
@Jawshy I can confirm this is an issue, lose both clothing & weapons on death after being revived

**Comment by thefuturechaos** [comment]
@Lylie14 i gave up on my server but it fixed when i went from 4.4r3 to 4.4r4 something is causing it in the mission file, because when i updated it it worked but when i brought my mission file back it didnt

**Comment by BoGuu** [comment]
So R4 is fine @thefuturechaos ?

**Comment by thefuturechaos** [comment]
@BoGuu ive found it worked better than r3 even tho r4 just the update for 1.64, i gave up because i had to redo my entire mission file

**Comment by BoGuu** [comment]
Well the question is:

Is this a problem with *vanilla* files?

**Comment by thefuturechaos** [comment]
@BoGuu I honestly dont think so

**Comment by BoGuu** [comment]
Any news?

**Comment by SimZor** [comment]
Its not an issue. I have tested it.

**Comment by Jawshy** [comment]
Then this issue will be closed.
