### ISSUE TITLE
Diving goggles not showing up in clothing menu

### ISSUE THREAD

**Issue by Blauschimmel** [AsYetUntitled/Framework#226]
### Expected behaviour
If you go to the clothing shop menu, you should be able to see diving googgles.

### Actual behaviour
You don't see them, because the player is not underwater.

### Steps to reproduce the behaviour 
Open any shop wich sells diving goggles and find out by yourself!

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB2 logs (if applicable)
NO RPT (not an actual error)

----

Mission version: ALL

Launcher version: ALL

Game version: ALL

Branch: What's a branch?

**Comment by Blauschimmel** [comment]
I fixed this by dipping the player into water for 0.0005 seconds;

Add this

`player setPosATL [-1000, -1000, 10];
sleep 0.0005;`

to core/functions/fn_clothingMenu.sqf between line 135 and 136 just above

`player attachTo [_testLogic,[0,0,0]];`

If there's any  other way to simulate that the player is underwater, that would probably be better, but this doesn't affect the player in any way.

**Comment by WolfSkin1337** [comment]
you mean
to `core/shops/fn_clothingMenu.sqf` https://github.com/AsYetUntitled/Framework/blob/2747463eb362b4d1173ddd842db68f50ecfd7c93/Altis_Life.Altis/core/shops/fn_clothingMenu.sqf#L136

**Comment by Blauschimmel** [comment]
Exactly!! I'll edit my comment!

**Comment by Blauschimmel** [comment]
Wait a second, I just realized that he removes all goggles but the diving goggles while being underwater...

**Comment by Blauschimmel** [comment]
So it could look like
`if(SEL(_this,3) in ["dive"]) then {
player setPosATL [-1000, -1000, 10];
sleep 0.0005;
};`

**Comment by Jawshy** [comment]
@Blauschimmel, thanks for the report and for providing a solution. If you like feel free to submit a [pull request](https://github.com/AsYetUntitled/Framework/pulls) (For PR guidelines see [Contributing: Pull Requests](https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md#pull-requests)). 

> Branch: What's a branch?

The [Arma 3 Steam Branches](https://community.bistudio.com/wiki/Arma_3_Steam_Branches) article on the Bohemia Interactive Community Wiki explains them.
