### ISSUE TITLE
Add Placeholders in stringtable.xml ?

### ISSUE THREAD

**Issue by WolfSkin1337** [AsYetUntitled/Framework#227]
Would we need Placeholders at `stringtable.xml`?

See example with empty strings:
https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/stringtable.xml#L6
https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/stringtable.xml#L2064
and any more

statement from @Jawshy:
https://github.com/AsYetUntitled/Framework/pull/223#pullrequestreview-15436754

----

**If you give me the OK then I can do that.**

----

Mission version: v5.0.0 WiP https://github.com/AsYetUntitled/Framework/commit/3b2d84d5dfc823af0f91c6002ee500f21c96811c

Launcher version: not important

Game version: not important

Branch: main

**Comment by Emma-L** [comment]
I'm in the process of tidying up the stringtable, and will commit ASAP (as I think the translations are coming to a close now). Thank you for offering to do them though, but I've already added the placeholders in my copy. Sorry I should have put this somewhere so you would know.

**Comment by WolfSkin1337** [comment]
@Emma-L 
i have time and i can do this.
:stuck_out_tongue_winking_eye:

**Comment by Emma-L** [comment]
@WolfSkin1337 I have it all done as the stringtable is now, but I'm waiting until all stringtable PRs have been closed, so there are no conflicts. Also I will be doing a tidy up of the English and punctuation at the same time.

**Comment by WolfSkin1337** [comment]
ok then i close this issues
