### ISSUE TITLE
English `Display Name` at the clothingshops for other language.

### ISSUE THREAD

**Issue by WolfSkin1337** [AsYetUntitled/Framework#228]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
- German inGame translation for Clothing.

### Actual behaviour
- English `Display Name` at the clothingshops

### Steps to reproduce the behaviour 
1. set your Game language at German or other 
2. go inGame to the Clothing-Shop
3. click to select on `"H_StrawHat"` is shows in language `Straw Fedora` but the right translation must be `Strohut` for German
see example: https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/config/Config_Clothing.hpp#L53 

----
My Request:
- deleting the `Display Name` for ingame translation
- and localize `Display Name` (I want to do this)

----

Mission version: v5.0.0 WiP https://github.com/AsYetUntitled/Framework/commit/3b2d84d5dfc823af0f91c6002ee500f21c96811c

Launcher version: 1.5.139565

Game version: 1.66.139586

Branch: main

**Comment by Jawshy** [comment]
[Localize](https://community.bistudio.com/wiki/localize) the display name. Good suggestion, @WolfSkin1337. This will be useful for the few clothing items that use a custom display name such as the [cop uniform](https://github.com/AsYetUntitled/Framework/blob/367d392667f7e8796ab6aee4c74d8ead7246b87d/Altis_Life.Altis/config/Config_Clothing.hpp#L121) as well as the `displayName` in [Config_SpawnPoints.hpp](https://github.com/AsYetUntitled/Framework/blob/504240b95daa484fceebc587d8fd74f6bd2be863/Altis_Life.Altis/config/Config_SpawnPoints.hpp) and nickname in [Config_Weapons.hpp](https://github.com/AsYetUntitled/Framework/blob/0ec12fa9c49aafabb58573617b404fab3ffd1146/Altis_Life.Altis/config/Config_Weapons.hpp).

**Comment by WolfSkin1337** [comment]
How do I have to change this for best?

Examples:
`hint localize "STR_ING`
or
`{hint localize "STR_ING"}`
or
`a other variant`

**Comment by WolfSkin1337** [comment]
i have found a other way see the Pull Request #237
