### ISSUE TITLE
Save vehicle native ?

### ISSUE THREAD

**Issue by etaux** [AsYetUntitled/Framework#229]
Hi I'm looking for a tutorial or a script to save the vehicles but not found, why he is not native as in exile mod?

I would like to help or a link to a tutorial I am on version 4.4r4 of altis life

**Comment by Jawshy** [comment]
@etaux, GitHub [Issues](https://help.github.com/articles/about-issues/) are for reporting bugs and proposing enhancements and ideas; they are not for asking for scripts. Vehicles have always been saved to the database.
