### ISSUE TITLE
Ammo

### ISSUE THREAD

**Issue by XGGAFFA** [AsYetUntitled/Framework#23]
just configs not setup i guess for ammo in weapons that you have added,tried the protector 9mm and the pm 9mm. no ammo is available

**Comment by SimZor** [comment]
I've tested the Protector with 9mm ammo on current build. This should not be an issue.

**Comment by Jawshy** [comment]
@SimZor, what about (Makarov) [PM](https://community.bistudio.com/wiki/Arma_3_CfgWeapons_Weapons#hgun_Pistol_01_F) 9 mm handgun ammo? 
 
 
 
 
 
 
([Spoiler](https://github.com/AsYetUntitled/Framework/blob/21b465dd1f29099e7d2813fa292e2c3ae6734afd/ApexContent/Config_Weapons.hpp#L39))

**Comment by SimZor** [comment]
Haven't tested that but should really be the same. @Jawshy
