### ISSUE TITLE
Very pro

### ISSUE THREAD

**Issue by etaux** [AsYetUntitled/Framework#230]
Congratulations very pro, asked a question and the post it is deleted after 5 minutes without explanation, it's called an asshole

**Comment by setoy** [comment]
https://github.com/AsYetUntitled/Framework/issues/229

You call that **deleted** and even **without explanation**?

Learn to use the platform before complaining.

**Comment by Emma-L** [comment]
Please use [the forums](https://armarpglife.com/forums/) or join the [discord](https://discord.gg/5Sz7XTc) for help. Jawshy explained to you why the issue was being closed, please see below:

>GitHub Issues are for reporting bugs and proposing enhancements and ideas; they are not for asking for scripts.

**Comment by NeFShARk** [comment]
![Morons everywhere](http://s2.quickmeme.com/img/46/464f1fc8e40b41968d8c41c15755f0d6659bed35050c5a9d577a64ab1f2c4cca.jpg)

**Comment by SimZor** [comment]
LMFAO
