### ISSUE TITLE
On my server i abort then come back and all my gear is gone

### ISSUE THREAD

**Issue by wilsonjude** [AsYetUntitled/Framework#231]
On my server i abort then come back and all my gear is gone!!!

**Comment by NeFShARk** [comment]
When reportting a problem, please use the [Issue Template](https://github.com/AsYetUntitled/Framework/blob/master/.github/ISSUE_TEMPLATE.md). thank you!

**Comment by Blauschimmel** [comment]
https://github.com/AsYetUntitled/Framework/issues/104

**Comment by Jawshy** [comment]
As @NeFShARk said, please follow the provided [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md) when reporting bugs, @wilsonjude. It is there for a reason.
