### ISSUE TITLE
Dupplication gang's bank

### ISSUE THREAD

**Issue by AltisCityOwn** [AsYetUntitled/Framework#233]
Hello,

Gays players on my server was duplicated with this shit :
- Open gang bank
- Withdraw and Deposit in same time
- And done, money was duplicated

Any solution for fix that ?

**Comment by Jawshy** [comment]
@AltisCityOwn, it looks like the issue that you are reporting has already been made: https://github.com/AsYetUntitled/Framework/issues/190. Please search before submitting a new issue as stated [here](https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md#before-creating-a-new-issue-make-sure-to). 

If you do submit an issue, please follow the provided [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md). 

It there a reason for why you have closed this issue?

**Comment by NeFShARk** [comment]
@Jawshy I think that he saw #190 after opening this issue and decided to close it. But it's just a guess! Let's wait and see if @AltisCityOwn tells us why :P
