### ISSUE TITLE
Server not starting - Unsupported language English in stringtable

### ISSUE THREAD

**Issue by kenzo47** [AsYetUntitled/Framework#234]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
Server should start.

### Actual behaviour
Server doesn't start with latest master branch files, keep getting mission read from bank in console. Tested it with latest release v4.4r4 mission PBO and server starts fine. Console keeps on spamming: "Unsupported language English in stringtable" and you're unable to connect.

### Steps to reproduce the behaviour 
By using the latest branch and starting the server. 

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB2 logs (if applicable)

http://pastebin.com/fULpp2Ni

Unsupported language English in stringtable

----

Mission version:  Latest master branch

Launcher version: Launcher version: 1.5.139565

Game version: 1.66.139586

Branch: main / beta branch not specified

**Comment by BoGuu** [comment]
Did you include the mission SQM (from the SQM folder?) and rename it to just mission.sqm

**Comment by kenzo47** [comment]
I'm very sorry, seems I missed that. Thanks for the very quick reply. It's fixed :)

**Comment by Jawshy** [comment]
Glad to see it is fixed. If you ever require more support you can join [our Discord server](https://discordapp.com/invite/sEcQdPn) or post on the [forums](https://armarpglife.com/forums/), @kenzo47.
