### ISSUE TITLE
NetServer SendMsg

### ISSUE THREAD

**Issue by Mateuus** [AsYetUntitled/Framework#235]
**Expected behaviour**

But does anyone get this? 

> NetServer::SendMsg: 

**Actual behaviour**

` 1:05:50 Server: Object 36:13 not found (message Type_93)
 1:05:50 Server: Object 12:4 not found (message Type_93)
 1:05:50 Server: Object 24:591 not found (message Type_93)
 1:05:50 Server: Object 12:3 not found (message Type_93)
 1:05:50 Server: Object 46:3 not found (message Type_93)
 1:05:51 NetServer::SendMsg: cannot find channel #178720262, users.card=18
 1:05:51 NetServer: users.get failed when sending to 178720262
 1:05:51 Message not sent - error 0, message ID = ffffffff, to 178720262 (REC.Quevedo)
 1:05:51 "<infiSTAR.de>ConnectLog| 0h 57min | Disconnected: REC.Quevedo(76561198080871929 - 69) - time: 3353.42 - serverFPS: 37.6471 (v0245)"
 1:05:51 No player found for channel 611417408 - message ignored
 1:05:51 Client: Remote object 69:0 not found`

**Steps to reproduce the behaviour**

**RPT and/or extDB2 logs (if applicable)**

Mission version:  v5.0.0 WiP 3b2d84d

Launcher version:  1.5.139565

Game version: 1.66.139586

Branch: main

**Comment by NeFShARk** [comment]
When reporting a problem, please use the [Issue Template](https://github.com/AsYetUntitled/Framework/blob/master/.github/ISSUE_TEMPLATE.md). thank you!

**Comment by Jawshy** [comment]
How does this relate to Altis Life RPG? It does not. @Mateuus, this should be asked on a forum or in a chatroom for _Arma_; not on a repository dedicated to the development of a mission for _Arma 3_. See [Bohemia Interactive Forums](https://forums.bistudio.com/) and [ARMA](https://discord.gg/arma) [Discord](https://discordapp.com) server.

**Comment by NeFShARk** [comment]
@Jawshy I guess that he thinks that these "problems" are coming from the mission, since he is using altis life and infishit.

**Comment by Jawshy** [comment]
Those messages are not exclusive to running this mission.
