### ISSUE TITLE
gang hideout 3

### ISSUE THREAD

**Issue by XGGAFFA** [AsYetUntitled/Framework#24]
no access to get inside building after capturing, i guess someone bought it?

**Comment by Heavybob** [comment]
yep, I purchased the building. Building will need to be added to blacklist.

**Comment by BoGuu** [comment]
Will add tomorrow along with many other fixes, thanks for the report.

**Comment by BoGuu** [comment]
It classes as a house - will change the building for the hideout

**Comment by Heavybob** [comment]
http://images.akamai.steamusercontent.com/ugc/1621679306998837341/BCCDE07FE5F97F14F0EF084A36148833F8C6BEE7/

Changed the building type.
