### ISSUE TITLE
Cars wont save in garage when restarting the server

### ISSUE THREAD

**Issue by mur202** [AsYetUntitled/Framework#244]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
The cars should go back into the players garage on restart

### Actual behaviour
If the car is not in the garage, it will go away

### Steps to reproduce the behaviour 
1. took out a car
2. restarted the server

----

Mission version: 5.0

Launcher version: newest

Game version: newest

Branch: 5.0

**Comment by NeFShARk** [comment]
Did you setup the appropriate account\s that run the sql procedures in your database?

**Comment by mur202** [comment]
such as?

**Comment by DarkSilencerZA** [comment]
lol

**Comment by Jawshy** [comment]
@mur202, thanks for the report. What @NeFShARk is asking is essentially "does the `arma3` user at `localhost` exist in your database?" See [altislife.sql, lines 31-68](https://github.com/AsYetUntitled/Framework/blob/2aed2f9c1ee20098194b76e670cbe2e6fefcaed1/altislife.sql#L31-L68). 

Although, I am quite sure I know what issue you are talking about and just need to confirm it on the latest build.

**Comment by NeFShARk** [comment]
If he used the sql file of this repo to create his database, then yes, the user\acc that i'm talking about is indeed **arma3** like @Jawshy said above.

**Comment by Jawshy** [comment]
@mur202, I cannot reproduce this issue on the latest ([281ceb2](https://github.com/AsYetUntitled/Framework/tree/281ceb239442fe2818887603084a608b3e043619)) version of the master branch. When the server is restarted any vehicle with `active = 1` is set to `active = 0` just as it should. See [/life_server/init.sqf, line 70](https://github.com/AsYetUntitled/Framework/blob/707b6507c3234fb994675648fd6bdf8c621fc64f/life_server/init.sqf#L70) and [/altislife.sql, lines 38-41](https://github.com/AsYetUntitled/Framework/blob/2aed2f9c1ee20098194b76e670cbe2e6fefcaed1/altislife.sql#L38-L41).

**Comment by Pokeristas** [comment]
This problem was to me too, solution is just set Definer to root@127.0.0.1 and save each table in this picture.
![pakeitimai mysql](https://cloud.githubusercontent.com/assets/28223642/25799851/629e877a-33ef-11e7-94a6-179055751943.PNG)
