### ISSUE TITLE
Restrain glitch

### ISSUE THREAD

**Issue by mur202** [AsYetUntitled/Framework#248]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
When having your hands up(surrender) and a cop restrains you it should make the restrain animation

### Actual behaviour
Your hands are still up and it wont do the restrain animation

### Steps to reproduce the behaviour 
1. surrender
2. get a cop to restrain you

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB2 logs (if applicable)
<Check your client and server RPT and extDB2 logs for errors and warnings.>
<If there are relevant messages and they are short then post them here with code formatting.>
<If there are relevant messages and they are long then upload the whole file to GitHub, Pastebin, or Hastebin.>

----

Mission version: <See core/init.sqf, briefingName in mission.sqm, or changelog in briefing.sqf for your mission version.> 5,0

Launcher version: <In the Arma 3 launcher go to ⚙ OPTIONS and click the version info below to copy it to your clipboard.> latest

Game version: latest

Branch: 5,0

**Comment by Jawshy** [comment]
Thanks for another bug report, @mur202.
