### ISSUE TITLE
jump animation

### ISSUE THREAD

**Issue by XGGAFFA** [AsYetUntitled/Framework#25]
maybe could be a better animation than guy flying while trying to put his gun away personally i remove it due to bug of jumping at top of a ledge and being able to fly up to your death.

**Comment by BoGuu** [comment]
The jump animation triggers the holstering animation currently (since 1.58 IIRC). This will eventually be fixed by Bohemia. There is no good alternative animation to use. I'll fix the super jump bug in due course, seems the last attempt was shoddy.
