### ISSUE TITLE
Numbers longer than 7 digits aren't precise

### ISSUE THREAD

**Issue by danielstuart14** [AsYetUntitled/Framework#256]
### Expected behaviour
Numbers longer than 7 digits should be precise. (Ex: 99,999,999 should return 99,999,999)

### Actual behaviour
Numbers longer than 7 digits are rounded. (Ex: 99,999,999 returns 100,000,000)

### Steps to reproduce the behaviour 
1. Just put some cash in your account

Of course it doesn't need to go up to 99,999,999. Anything after 9,999,999 will be rounded. I wrote a sqf library that can solve that. Here: https://github.com/danielstuart14/A3_SPFP-Fix (Read the README, it isn't the same from KilzoneKid)

Do you think it is worth?

----

Mission version: v5.0.0

Launcher version: Launcher version: 1.5.139565

Game version: 1.66.139586

Branch: main

**Comment by BoGuu** [comment]
I know the lack of precision on the A3 floats is disappointing, but I'm strongly against moving all numbers to strings, for many reasons. Performance alone would be enough to say this is not the best idea :P

Nice idea, and good job if you have everything working on your lib, but if people are having issues, they can just stop bloating their economies / putting silly price tags on things :D
