### ISSUE TITLE
global remote execution not allowed in life_server

### ISSUE THREAD

**Issue by Blauschimmel** [AsYetUntitled/Framework#257]
### Expected behaviour
A code like `[_vehicle, ["RopeAttach", {ropeCut [ _this select 1, 1];}]] remoteExec ["addEventHandler",0,true];
` should be executed in Functions/Systems/fn_spawnVehicle.

### Actual behaviour
It doesn't as JIP doesn't seem to be enabled or whatever.

### [RPT]
NO RPT

----

Mission version: Current

Launcher version: Current

Game version: Current

Branch: Altis Life 5.0

**Comment by BoGuu** [comment]
This is not a repo issue, but you need edit/whitelist stuff in your own CfgRemoteExec (addEventHandler will be under Commands)

**Comment by Blauschimmel** [comment]
i actually added it and it didn't work. I closed it, because it suddenly appears to work without it. The original intention was to make it possible to whitelist the functions/codes for life server files, but it seems like it already is included...
