### ISSUE TITLE
Safe to make a deposit all script?

### ISSUE THREAD

**Issue by ThePistachios** [AsYetUntitled/Framework#260]
*This is a suggestion/question, not a bug.*

**Feature:**
A simple button in the bank GUI that deposits all money on hand at once.

**Question:**
Is performing such an action safe? In the normal deposit script their is a max amount of money you can deposit, is this there for a safety reason? I doubt it but it I suppose the max could be there for database precautions or something. Thanks.

**Comment by SwAtRaNgEr** [comment]
The Feature is easily doable and safe to do so. Some servers do have it already implemented.

**Comment by ThePistachios** [comment]
@SwAtRaNgEr Fantastic, this is what I wanted to hear! I figured so, but just wasn't sure if that max deposit amount necessary or not. Thanks.
