### ISSUE TITLE
Error in expression - fn_weaponShopSelection

### ISSUE THREAD

**Issue by Jawshy** [AsYetUntitled/Framework#262]
### Expected behaviour
Magazines are sold at their respective price determined in [Config_Weapons.hpp](https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/config/Config_Weapons.hpp). 

### Actual behaviour
Magazines are sold for 0 dollars. 

### Steps to reproduce the behaviour 
1. Spawn in as police or civilian. 
2. Go to a weapon shop. 
3. Purchase a magazine. 
4. Sell the magazine. 
5. Note the [error in expression for fn_weaponShopSelection.sqf](https://github.com/AsYetUntitled/Framework/blob/98d19e4208ec199fbf27ea9f5e5132383eab7327/Altis_Life.Altis/core/shops/fn_weaponShopSelection.sqf#L22-L23) and that the magazine was sold for 0 dollars. 

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
```
Error in expression <ll TON_fnc_index;
_price = ((_itemArray select _item) select 3);
_priceTag ctrlS>
  Error position: <select _item) select 3);
_priceTag ctrlS>
  Error Zero divisor
File mpmissions\__CUR_MP.Altis\core\shops\fn_weaponShopSelection.sqf, line 22
```

----

Mission version: 5.0.0 as of https://github.com/AsYetUntitled/Framework/commit/88e9599e9379fc687077773aa0dd0192f8a1c0ba. 

Launcher version: 1.5.139565

Game version: 1.66.140166

Branch: [profiling](https://community.bistudio.com/wiki/Arma_3_Steam_Branches)

**Comment by Jason2605** [comment]
I would guess it because: https://github.com/AsYetUntitled/Framework/blob/98d19e4208ec199fbf27ea9f5e5132383eab7327/Altis_Life.Altis/core/shops/fn_weaponShopSelection.sqf#L20
is selecting from items and not mags

**Comment by Jason2605** [comment]
Fixed as of https://github.com/AsYetUntitled/Framework/commit/dc9eeb5eecc410d5205780d864fab6440b6ef1ca
