### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by mur202** [AsYetUntitled/Framework#263]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
When withrawing 40k in cash it should say: 40.000

### Actual behaviour
It says 40,000. The , is not correct, it should be replaced with a space or a dot

### Steps to reproduce the behaviour 
1. <How did you break it?>

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
<Check your client and server RPT and extDB3 logs for errors and warnings.>
<If there are relevant messages and they are short then post them here with code formatting.>
<If there are relevant messages and they are long then upload the whole file to GitHub, Pastebin, or Hastebin.>

----

Mission version: <See core/init.sqf, briefingName in mission.sqm, or changelog in briefing.sqf for your mission version.> Latest

Launcher version: <In the Arma 3 launcher go to ⚙ OPTIONS and click the version info below to copy it to your clipboard.> Latest

Game version: Latest

Branch: Latest

**Comment by setoy** [comment]
Depends on your region. For english speaking countries the comma is correct.

**Comment by mur202** [comment]
Okey, where I live it is suppost to say 40.000 (,00)

**Comment by Jawshy** [comment]
See [Decimal mark → Examples of use](https://en.wikipedia.org/wiki/Decimal_mark#Examples_of_use).

**Comment by BoGuu** [comment]
A current pull request changes the format from `40,000` to `40 000` for non English clients. There is a lot of ways to display numbers, and it'd be silly for us to account for them all, after all, I don't think it's hindering your game play, is it :)?
