### ISSUE TITLE
Can't remove "Binocular" from binocular slot

### ISSUE THREAD

**Issue by baua1310** [AsYetUntitled/Framework#264]
### Expected behaviour
Remove "Binocular" from Binocular Slot

### Actual behaviour
Nothing happens
### Steps to reproduce the behaviour 
execute `["Binocular",false] call life_fnc_handleItem;` while having only one Binocular in your Inventory in your Binocular Slot
### Solution
change [line 390](https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/core/functions/fn_handleItem.sqf#L390) from `if ((_details select 5) isEqualTo 1) then {` to `if ((_details select 5) isEqualTo -1) then {` like it is in [line 76](https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/core/functions/fn_handleItem.sqf#L76)

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
Nothing to show

----

Mission version: 5.0.0

Launcher version: 1.5.139565

Game version: 1.66.139586

Branch: ~development~ main -- Edit: @Jawshy

**Comment by jordanlee833** [comment]
Suggested fix did not work, will look into further detail soon.
