### ISSUE TITLE
Retrieved vehicle cannot be re-saved.

### ISSUE THREAD

**Issue by hamza47sohail** [AsYetUntitled/Framework#266]
### Expected behaviour
<After retrieving a vehicle from the Garage it should be saved again.>

### Actual behaviour
<After retrieving the vehicle from the Garage, it does not re-save. The message displayed " The server is trying to save the vehicle" is displayed endlessly.>

### Steps to reproduce the behaviour 
1. Buy a vehicle
2. Save it in the Garage
3. Retrieve it
4. Try to save it again

extDB3 Logs: http://pastebin.com/1rz9XtUe
RPT Logs: http://pastebin.com/XTAAMRsF

----
Database Type: mariaDB

Mission version: 5.0.0 with the latest commit as of today.

Launcher version: Launcher version: 1.5.139565

Game version: 1.66.139586

Branch: main / beta branch not specified

**Comment by NeFShARk** [comment]
For the exDB3 error, you need to create the user arma3 give it permission at localhost in your mariadb for the procedures to run properly, see: [arma3@localhost](https://github.com/AsYetUntitled/Framework/blob/2aed2f9c1ee20098194b76e670cbe2e6fefcaed1/altislife.sql#L31-L68)

**Comment by hamza47sohail** [comment]
Sorry about that, forgot to look at the .sql file.

I added a user like you mentioned however the problem persists. The user is working fine since things like, health, hunger and thirst were synced once I connected to the server which previously were not.

The interesting thing I noticed is, when you take the vehicle out of the Garage you can not put it back however, if you restart the server and go back to the Garage, the vehicle is saved inside inside the Garage.

I suspect the vehicle is not removed from the database once you retrieve it. That is why it does not save and when the server is restarted the vehicle appears in the Garage.

Logs after the above fix was applied.

extDB3: http://pastebin.com/swsyg2Xc
RPT: http://pastebin.com/eDtfYJWF

**Comment by BoGuu** [comment]
I haven't yet tested this, but I've seen mixed feedback so far in relation to it. The general consensus seems to be that it is indeed working though. Are you still having issues?

**Comment by XtGDevelopmentTeam** [comment]
I can confirm this bug is still con-current. Seems to be a extDB3 bug. Switching back to extDB2 fixing this problem.

**Comment by WolfSkin1337** [comment]
I cant confirm this bug. All works with [extDB3-1023+Linux.7z](https://bitbucket.org/torndeco/extdb3/downloads)

**Comment by XtGDevelopmentTeam** [comment]
@WolfSkin1337 - That is probably why its working for you, strange reason is Linux? / Windows

**Comment by BoGuu** [comment]
@XtGDevelopmentTeam It's just denoting that it includes the linux build aswell

**Comment by BoGuu** [comment]
Please see https://github.com/AsYetUntitled/Framework/commit/bffa3b8fd0d8778a36f6e7b6bf8061d0648a287c

**Comment by Jawshy** [comment]
Has @BoGuu's [above commit](https://github.com/AsYetUntitled/Framework/commit/bffa3b8fd0d8778a36f6e7b6bf8061d0648a287c) fixed this issue, @hamza47sohail and @XtGDevelopmentTeam?

**Comment by hamza47sohail** [comment]
@Jawshy 
This can be closed. As far as I can tell its fixed.
Sorry for the late reply!
