### ISSUE TITLE
Setting up client, please wait!

### ISSUE THREAD

**Issue by AndrewsSoftwares** [AsYetUntitled/Framework#267]
### Actual behaviour
Server tells me "Setting up client, please wait"

### [extDB3 log]

http://pastebin.com/QzTExvri

Mission version: ALTIS LIFE RPG V5.0.0

Launcher version: 1.5.139565

Game version: 1.66.139586

Branch: main / beta branch not specified

**Comment by WolfSkin1337** [comment]
tell use the RPT`s (https://community.bistudio.com/wiki/Crash_Files#Arma_3)

Or

come on the discord-Server (https://discord.gg/Cd3Zs)

**Comment by AndrewsSoftwares** [comment]
i realized what was the problem and solved it but i have no idea how to delete this "issue post"

**Comment by ThePistachios** [comment]
@AndrewsSoftwares You cannot delete issue posts on GitHub.

**Comment by WolfSkin1337** [comment]
@BoGuu
Then we can

CLOSE
