### ISSUE TITLE
Client Side Error - Anyone else getting it?

### ISSUE THREAD

**Issue by DarkSilencerZA** [AsYetUntitled/Framework#27]
18:21:34 Error in expression <ide isEqualTo west && (_sideRepairArray select 1) isEqualTo 0) then {
[false,"to>
18:21:34   Error position: <select 1) isEqualTo 0) then {
[false,"to>
18:21:34   Error Zero divisor
18:21:34 File mpmissions\__CUR_MP.Tanoa\core\actions\fn_repairTruck.sqf, line 58

**Comment by XGGAFFA** [comment]
nope,not me. only got some duplicate entries in stringtable. everything else seems fine
21:54:12 Item STR_House_SellHouseMSG listed twice
21:54:12 Item STR_Civ_Plane listed twice
21:54:12 Item STR_Police_Store listed twice
21:54:12 Item STR_Police_Car listed twice
21:54:12 Item STR_Police_Heli listed twice
21:54:12 Item STR_Police_Boat listed twice
21:54:12 Item STR_Rebel_Car listed twice
21:54:12 Item STR_Rebel_Heli listed twice

**Comment by BoGuu** [comment]
Will check it out tomorrow, should technically not be an issue. I'll also look into those double strings

**Comment by Jawshy** [comment]
Regarding STR_House_SellHouseMSG listed twice - see PR https://github.com/AsYetUntitled/Framework/pull/30.

**Comment by Jawshy** [comment]
@DarkSilencerZA, are you still getting that error in expression when using the latest build? If not then the issue will be closed.

**Comment by SimZor** [comment]
I think this can be closed, not stumbled upon this issue at all. @Jawshy @BoGuu
