### ISSUE TITLE
ExtDB3 + garage errror

### ISSUE THREAD

**Issue by Derfavo** [AsYetUntitled/Framework#274]
I updated to extDB3 and it looks like it works good. But when i go to the garage, get a acar out put it backnin and then try to put it put it's not coming out and this error appeared..

The error..
Error in Expression <, ((_parts select 0) select _i)], _damage select _i];
};
};

if ((_vInfo select 1>
Error Position: <select _i];
};
};

if ((_vInfo select 1>
Error Generic error in Expression
File life_server\Functions\Systems\fn_spawnVehicle.sqf, line 167

I did not changed the files for the vehicle spawning just updated to extDB3.
...

Mission version: 5.0

**Comment by WolfSkin1337** [comment]
Which Version of extDB3 do you use?
What was your last Change?

**Comment by Derfavo** [comment]
The latest of extDB3.

Just Dialogs and extDB3..

**Comment by cappino** [comment]
Thank god, I've spent hours on trying to find an error with no luck, I have exactly the same problem. I can buy vehicle then store it in the garage no errors no problem, but then I retrieve vehicle and the vehicle spawns but there is first server rpt error

` 0:46:11 Error in expression <y") isEqualTo 1)) then {
_items = _gear select 0;
_mags = _gear select 1;
_weapo>
 0:46:11   Error position: <select 0;
_mags = _gear select 1;
_weapo>
 0:46:11   Error Generic error in expression
 0:46:11 File life_server\Functions\Systems\fn_spawnVehicle.sqf, line 144`

Then it's impossible to store this vehicle back

**Comment by Derfavo** [comment]
It's just because of extDB3.

I think the mresArray is broken, but not sure at all. Maybe they will do a fix. Everyone will for now get the error :D

**Comment by WolfSkin1337** [comment]
@Derfavo 
the last Version from here?
https://bitbucket.org/torndeco/extdb3/downloads

**Comment by Derfavo** [comment]
Yeah that's the version i use!

**Comment by WolfSkin1337** [comment]
and you have do following? :
- copy the new `tbbmalloc.dll` to the main folder (Arma 3 Server)
- copy complete `@extDB3 include the addons folder` to the main folder (Arma 3 Server)
- change the things for you at `@extDB3\extdb3-config.ini`

**Comment by Derfavo** [comment]
Yeah i changed everything.

**Comment by WolfSkin1337** [comment]
and you use the newest `Altis Life Dev 5.0`?
from here https://github.com/AsYetUntitled/Framework

**Comment by ThePistachios** [comment]
@Dervafo 

> Everyone will for now get the error.

This issue is not happening to me, don't believe it's an error for everyone.

**Comment by Derfavo** [comment]
But why did I get this error?
I did not change something exept extDB3..

Okay then i need to checl again :D

**Comment by ThePistachios** [comment]
@Derfavo is extDB3 flashing any errors in the server logs/when starting up the server? 

Are you getting the `extDB3: Connected to Database` message?

Perhaps you need to redownload @life_server from the repo and replace what you have on your server.

**Comment by Derfavo** [comment]
The thing is that the auctionhouse the market players ect are working.. exept this..

And yeah i get the extdb is connectet message..

Extdb is just saying something like null "".
When im home i send the extdb log.

**Comment by BoGuu** [comment]
This situation is getting silly now, it's a 50/50 split, which just can't happen. Can the people with this issue, please clarify whether or not you're using the latest **vanilla** development build, with the **latest** extDB3 build.

**Comment by Derfavo** [comment]
All is latest and vanilla..

**Comment by BoGuu** [comment]
@Derfavo 

Can you use the debug dll supplied with the download of extDB, and post the log from it.

Same applies to anyone else with issues

**Comment by Derfavo** [comment]
Okay.

**Comment by Derfavo** [comment]
Here is my log. I connectet. get the car out put it in and then it does not work to get it out again :)


here are both logs..
[logs.zip](https://github.com/AsYetUntitled/Framework/files/764001/logs.zip)

**Comment by BoGuu** [comment]
@Derfavo 

So your log shows you're not using the vanilla, repo, could you please do so, then post again?

I see an error that could cause this in your extDB logs though, I'll look further into it

**Comment by Derfavo** [comment]
But I did not changed the vehicle parts?

**Comment by BoGuu** [comment]
You may not have, but to be totally sure of no interference, we prefer you to use the vanilla build. Can you try extDB3 1.023?

**Comment by Derfavo** [comment]
I have installed extDB2 for testing and it worked 100%! But when i'm going back to extDB3 the bug appears.

**Comment by Derfavo** [comment]
And I got this Version -> https://github.com/AsYetUntitled/Framework just did some small changes atm..

**Comment by BoGuu** [comment]
Yeh, bear with me, fix incoming @Derfavo

**Comment by BoGuu** [comment]
Please see https://github.com/AsYetUntitled/Framework/commit/bffa3b8fd0d8778a36f6e7b6bf8061d0648a287c

**Comment by Derfavo** [comment]
Thanks :)

**Comment by Jawshy** [comment]
@Derfavo, follow the provided [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md) for any future issues.
