### ISSUE TITLE
Discord link expired/not working

### ISSUE THREAD

**Issue by ThePistachios** [AsYetUntitled/Framework#275]
https://discord.gg/Cd3Zs

Link is dead. Can't seem to find a working one. Tried the link from the readme and copy and pasted from breifing.sqf update a few commits ago.

Sorry for opening a whole issue, just trying to get on it! :)

**Comment by NeFShARk** [comment]
Go to the forums, click on discord = success - https://discordapp.com/invite/sEcQdPn

**Comment by ThePistachios** [comment]
@NeFShARk I was actually looking at [this forum](https://www.altisliferpg.com/), sorry! 

Well, someone should still update the links here when they can. Thank you.

**Comment by BoGuu** [comment]
Fixed
