### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by NoelBank** [AsYetUntitled/Framework#276]
Hey i get this Error;

#1293 - Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause 

can anyone help me?

**Comment by BoGuu** [comment]
Update your MySQL server ver

**Comment by ThePistachios** [comment]
I had this exact issue when using a MariaDB server on centOS7.

I installed MySQL instead and it worked fine.

**Comment by NoelBank** [comment]
I have MySQL the Newest version

**Comment by ThePistachios** [comment]
Can you please please provide your box info? (Windows, Linux distribution, dedicated, etc)

**Comment by NoelBank** [comment]
Oh yes, Linux Debian  8

**Comment by ThePistachios** [comment]
Ok. Can you please provide me with the output of `mysql -V`

Also how are you connecting to your SQL server? Remotely or are you running the scripts locally?

**Comment by NoelBank** [comment]
`mysql  Ver 14.14 Distrib 5.5.54, for debian-linux-gnu (x86_64) using readline 6.3
`

**Comment by ThePistachios** [comment]
Try updating to MySQL 5.7.

[You can take a look at this guide](http://www.debiantutorials.com/install-mysql-server-5-6-debian-7-8/)

**Comment by ThePistachios** [comment]
Also ensure your using the altislife.sql from latest commit rather then the releases tab.

**Comment by NoelBank** [comment]
Okay!

**Comment by NoelBank** [comment]
Yes its working!!! But i dont can Find any MYSQL connect in the Life_master

**Comment by ThePistachios** [comment]
Awesome. 

Can you elaborate on that?

**Comment by NoelBank** [comment]
Hat sich erledigt habe den fehler gefunden. aber wie erstelle warum bekomme ich diese Meldung 
19:23:13 Can't find a mission collection / mission with template name: 'Altis_Life.Altis', skipping to next mission.

**Comment by ThePistachios** [comment]
This is an issue with your config. Make sure it has a mission file section (generally located at the bottom) and Altis_Life.Altis is spelled correctly.

Look [here](https://community.bistudio.com/wiki/server.cfg) for more information. (Look at the example config file, where the mission selector is)

**Comment by NoelBank** [comment]
Okay
Thanks i get it

**Comment by Jawshy** [comment]
@NoelBank, in future, read the [guidelines for contributing](https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md) and follow the provided [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md).
