### ISSUE TITLE
extDB3: Config Error: : No such node (.IP)

### ISSUE THREAD

**Issue by MrHeavyMetal** [AsYetUntitled/Framework#279]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
It should connect to the DB

### Actual behaviour
It does not connect to the DB

### Steps to reproduce the behaviour 
1. Download master files
2. Setup the server and DB
3. Try to start the server

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
```
extDB3: https://bitbucket.org/torndeco/extdb3/wiki/Home
extDB3: Version: 1.025
extDB3: Windows Version
Message: All development for extDB3 is done on a Linux Dedicated Server
Message: If you would like to Donate to extDB3 Development
Message: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2SUEFTGABTAM2
Message: Also leave a message if there is any particular feature you would like to see added.
Message: Thanks for all the people that have donated.
Message: Torndeco: 18/05/15


extDB3: Found extdb3-conf.ini
extDB3: Detected 8 Cores, Setting up 6 Worker Threads
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...


[13:46:28:917619 +00:00] [Thread 2912] extDB3: Config Error: : No such node (.IP)
```

----

Mission version: <See core/init.sqf, briefingName in mission.sqm, or changelog in briefing.sqf for your mission version.> 5.0.0

Launcher version: <In the Arma 3 launcher go to ⚙ OPTIONS and click the version info below to copy it to your clipboard.> N/A

Game version: ~Latest at time of writing~ 1.66 -- Edit: @Jawshy 

Branch: Main

**Comment by Jawshy** [comment]
When I encountered this error I fixed it by following the steps outlined [here](https://github.com/AsYetUntitled/Framework/wiki/Troubleshooting#extdb3-database-type-altislife-no-such-node-altislifeip-in-extdb3-log). This is most likely an error on your end and not that of the framework.

**Comment by MrHeavyMetal** [comment]
I tried that, it didnt work https://gyazo.com/c895700e565c82d2e3530a0000003de6

**Comment by MrHeavyMetal** [comment]
Found the issue with the help of the discord, turns out the vehicle config was breaking the description.ext
