### ISSUE TITLE
spawn medic

### ISSUE THREAD

**Issue by XGGAFFA** [AsYetUntitled/Framework#28]
Not really an error, just a placement change for marker. just think medic spawns too far from hospital in tanouka. also atm needs moving to the wall its on an angle currently and not near wall its also placed ontop of the npc

**Comment by Emma-L** [comment]
The hospital wasn't properly placed, they're to be moved, but they don't really serve a purpose for now as they don't really need testing. :)

**Comment by XGGAFFA** [comment]
oh ok thanks for info

**Comment by Emma-L** [comment]
No worries
