### ISSUE TITLE
Fix for buy/sell garage of the house

### ISSUE THREAD

**Issue by Dim2ke** [AsYetUntitled/Framework#281]
## Expected behaviour
- Fix price display of garage with purchase -> fixed in #273 
- Fix an error has occurred in fn_sellHouseGarage.sqf, _price instead of _sellprice -> fixed in #273
- Fix No message is displayed when selling garage -> fixed in #273
- ⚠️  Fix an error has occured in syntax when you click on the garage button without having bought the garage, i have tried multiple syntax combination and I have not successfully fixed it ⚠️ 
``` 
_Btn2 buttonSetAction "hint format [localize 'STR_pInAct_GarageExtNOTF',LIFE_SETTINGS(getNumber,'houseGarage_buyPrice')];";
```

## Actual behaviour
- ### Buy house garage
- When you click on the garage button without having bought the garage, an error message appears [screenshot](http://zupimages.net/up/17/08/17kz.png)
- When one buys the garage of a house the price is not displayed correctly [screenshot](http://zupimages.net/up/17/08/yror.png) 

- ### Sell house garage
- When someone sells the garage of a house, an no message dispalyed [screenshot](http://zupimages.net/up/17/08/5yxv.png)
- When someone confirms the sale of the garage of a house, an error message appears [screenshot](http://zupimages.net/up/17/08/3uqw.png)

## Steps to reproduce the behaviour 
1. Go to house garage and dont buy it
2. Open house menu
3. click on garage button error (1 in Actual behaviour/Buy house garage)
4. buy the house
5. buy the garage of the house (2 in Actual behaviour/Buy house garage)
6. Sell the garage of the house (1 in Actual behaviour/Sell house garage)
7. Confirm the of the garage (2 in Actual behaviour/Sell house garage)

----

Mission version: 5.0.0
~Launcher~ Game version: 1.66 -- Edit: @Jawshy 
Branch: Main

**Comment by BoGuu** [comment]
Hi, thanks for the issue. I really don't understand what you're trying to get across in this issue. Could you perhaps elaborate?

Also, still waiting on your changes for #273 (lazy eval etc) :)

**Comment by Jawshy** [comment]
I am with @BoGuu; I do not understand the issue. @Dim2ke, you have listed the expected behaviour, but not the actual behaviour (the issue/bug).

**Comment by Dim2ke** [comment]
Hi @BoGuu @Jawshy,
I reedit the issue for a better understanding.
About lazy evaluation, I try to figure out how to do it and I do it :)

**Comment by Jawshy** [comment]
Thanks. 

> About lazy evaluation, I try to figure out how to do it and I do it :)

See https://github.com/AsYetUntitled/Framework/pull/273#discussion_r101918067.
