### ISSUE TITLE
SQL Import Error

### ISSUE THREAD

**Issue by antonand03** [AsYetUntitled/Framework#283]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
It should of imported the sql file.

### Actual behaviour
It gave me this error: 
DELIMITER ;

-- --------------------------------------------------------

--
-- Table structure for table `players`
--

CREATE TABLE IF NOT EXISTS `players` (
  `uid` int(6) NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL,
  `aliases` text NOT NULL,
  `pid` varchar(17) NOT NULL,
  `cash` int(100) NOT NULL DEFAULT '0',
  `bankacc` int(100) NOT NULL DEFAULT '0',
  `coplevel` enum('0','1','2','3','4','5','6','7') NOT NULL DEFAULT '0',
  `mediclevel` enum('0','1','2','3','4','5') NOT NULL DEFAULT '0',
  `civ_licenses` text NOT NULL,
  `cop_licenses` text NOT NULL,
  `med_licenses` text NOT NULL,
  `civ_gear` text NOT NULL,
  `cop_gear` text NOT NULL,
  `med_gear` text NOT NULL,
  `civ_stats` varchar(32) NOT NULL DEFAULT '"[100,100,0]"',
  `cop_stats` varchar(32) NOT NULL DEFAULT '"[100,100,0]"',
  `med_stats` varchar(32) NOT NULL DEFAULT '"[100,100,0]"',
  `arrested` tinyint(1) NOT NULL DEFAULT '0',
  `adminlevel` enum('0','1','2','3','4','5') NOT NULL DEF[...]
MySQL sa: Dokumentation

#1293 - Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause 

### Steps to reproduce the behaviour 
1. I only imported the sql script.

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
<Check your client and server RPT and extDB3 logs for errors and warnings.>
<If there are relevant messages and they are short then post them here with code formatting.>
<If there are relevant messages and they are long then upload the whole file to GitHub, Pastebin, or Hastebin.>

----

Mission version: <See core/init.sqf, briefingName in mission.sqm, or changelog in briefing.sqf for your mission version.>

Launcher version: <In the Arma 3 launcher go to ⚙ OPTIONS and click the version info below to copy it to your clipboard.>

Game version: 

Branch:

**Comment by ThePistachios** [comment]
Lol. No reason to open up an entirely new issue. You should have just edited the other one. 

Again, see #276

**Comment by ThePistachios** [comment]
@antonand03 ,

Is your issue solved?

**Comment by Jawshy** [comment]
As @ThePistachios said, see issue https://github.com/AsYetUntitled/Framework/issues/276 (_MySQL_). @antonand03, use the search function before creating a new issue.
