### ISSUE TITLE
extDB2 for linux not working

### ISSUE THREAD

**Issue by Alexlyn1** [AsYetUntitled/Framework#285]
Hello, so i get this error in my logs

[20:38:32 +01:00] [Thread 28959] extDB2: Database Type: MySQL
[20:38:32 +01:00] [Thread 28959] extDB2: Database Exception Error: MySQL: [MySQL]: create session: bad connection string format, can not find '='

the connection information is correct, and it works for altislife 5.0 and extDB3 but for this not? I meet all requirements if i do
ldd extDB2.so

**Comment by ThePistachios** [comment]
The [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md) is there for a reason.

Edit your post to follow it and be sure to include your RPT logs and extDB logs.

**Comment by Alexlyn1** [comment]
Hello. Sorryy i did not see the template it says for bug though?

but okay so i dont get any errors in the rpt other than 'extDB2: Connection to database failed' 

and then in extdb logs i get what i posted

**Comment by ThePistachios** [comment]
Bug/Issue 

This question would truly be more appopriate on the Discord channel. But again please edit and include the full logs. 

Also add in your extDB config file.

**Comment by Alexlyn1** [comment]
Okay also i have tried discord people couldnt help me or tell me they arent there to build my server

i dont have the rpts anymore and i dont have those server files anymore because it wasnt working and i couldnt fix so i will try use 5.0 i just wanted to let u know it didnt work

**Comment by ThePistachios** [comment]
I see. Well this is a user error, as it extDB2 does indeed work for Altis 4.4r3.

**Comment by Jawshy** [comment]
> Hello. Sorryy i did not see the template it says for bug though?

@Alexlyn1, the [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md) is pre-written when you click "New issue." 

1. This repository is for the [mission framework](https://github.com/AsYetUntitled/Framework/blob/61e59db3b88e0df3d714208f465cb0b63ad111d3/README.md); not [extDB2](https://github.com/AsYetUntitled/extDB2). 
2. extDB2 has been superseded by [extDB3](https://bitbucket.org/torndeco/extdb3/downloads/). 

As @ThePistachios said, use the [Discord server, or even the forums](https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md#contact), for any issues not caused the mission (I.e. user errors).
