### ISSUE TITLE
money_log is empty

### ISSUE THREAD

**Issue by cappino** [AsYetUntitled/Framework#286]
### Expected behaviour
money_log should return some result

### Actual behaviour
money_log returns empty. 
BattlEye Log:
`27.02.2017 00:45:00: SomePlayer (00.00.000.00:2304) 16d4d6ef8435someguid1ee22c19d889ff3 - #0 "money_log" = ""`
RPT Log:
` 0:45:00 ""`
Interesting enough it's like that for 90% of players, it works if i join the server and test it.
### Steps to reproduce the behaviour 
N/A

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
there are no errors or warnings in client/server rpt.

----

Mission version: 5.0.0

Launcher version: 1.5.139565

Game version: 1.66.139586

Branch: main

**Comment by cappino** [comment]
I believe I found why this is happening, money log returns empty when player is using other than english language.

**Comment by BoGuu** [comment]
👍
