### ISSUE TITLE
Strings

### ISSUE THREAD

**Issue by Heavybob** [AsYetUntitled/Framework#29]
One of the police strings have been incorrectly labled and says "Police Heli" when it should say "Police Boat". Its in georgetown. 

"STR_Police_Boat">
inal>Police Heli</Original>
Key>

The blue x marked at the police air hq is a mistake and needs to be removed or altered to reflect the correct marker system standard.

**Comment by BoGuu** [comment]
Will sort tomorrow :+1:

**Comment by BoGuu** [comment]
#31 - Post if problem persists (server updated)
