### ISSUE TITLE
Admin Markers not disappearing

### ISSUE THREAD

**Issue by cappino** [AsYetUntitled/Framework#292]
### Expected behaviour
When clicked on Markers in the Admin Menu, all map markers should disappear.

### Actual behaviour
They do not disappear, in fact in some cases they somehow get duplicated.

### Steps to reproduce the behaviour 
1. Open admin menu and click markers

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
No Errors in client/server

----

Mission version: 5.0.0

Launcher version: 1.5.139565

Game version: 1.66.139586

Branch: main

**Comment by BoGuu** [comment]
Known issue, but thanks for the issue regardless. Fix can be expected in release
