### ISSUE TITLE
Default spikestripes cant be placed

### ISSUE THREAD

**Issue by killer-kirito** [AsYetUntitled/Framework#295]
Using of items doesnt work

The usage of any item doesnt work (i now tested other then the spikes)

i added a new item (deployable cones) afther that it didnt work anymore i think

i undo everything i did to add the new item, but it still doesnt work

Mission version: 5.0.0

Launcher version: L 1.5.139565

Game version: 1.66.139586
Branch: main / beta branch not specified

**Comment by Jawshy** [comment]
@killer-kirito, [edit](https://help.github.com/articles/editing-a-comment/) your issue and then add and fill out the [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/ff7099120fa87da294c4039ccd7ae2c7efd432dc/.github/ISSUE_TEMPLATE.md), please. 

The [player menu](https://github.com/AsYetUntitled/Framework/blob/707b6507c3234fb994675648fd6bdf8c621fc64f/Altis_Life.Altis/core/functions/fn_keyHandler.sqf#L192-L197) key is `Y`, not `Z`.

**Comment by killer-kirito** [comment]
@Jawshy im from germany on our keyboard z and y is changed, so i have to press z (where you have your y key)

**Comment by killer-kirito** [comment]
fixed it by using a clear new version from git, cant recreate my error
