### ISSUE TITLE
Bots spawn when people dc

### ISSUE THREAD

**Issue by mur202** [AsYetUntitled/Framework#296]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
When people disconnect they should get removed from the game

### Actual behaviour
When they disconnect they get replaced by a bot

### Steps to reproduce the behaviour 
1. Join
2. leave

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
<Check your client and server RPT and extDB3 logs for errors and warnings.>
<If there are relevant messages and they are short then post them here with code formatting.>
<If there are relevant messages and they are long then upload the whole file to GitHub, Pastebin, or Hastebin.>

----

Mission version: <See core/init.sqf, briefingName in mission.sqm, or changelog in briefing.sqf for your mission version.> latest 5.0

Launcher version: <In the Arma 3 launcher go to ⚙ OPTIONS and click the version info below to copy it to your clipboard.> latest

Game version: latest

Branch: latest

**Comment by Jawshy** [comment]
@mur202, this is an issue with how you have set up the mission; not an issue with the framework. In the mission.sqm, under `class ScenarioData`, `disabledAI` should be `1.` See [here](https://github.com/AsYetUntitled/Framework/blob/fe0c08baa83367986df3c125e3390016c814c4a0/SQMs/missionAltis.sqm#L166). See also [Eden Editor: Scenario Attributes → Multiplayer](https://community.bistudio.com/wiki/Eden_Editor:_Scenario_Attributes#Multiplayer).
