### ISSUE TITLE
Filter Issues

### ISSUE THREAD

**Issue by DarkSilencerZA** [AsYetUntitled/Framework#298]
### Expected behaviour
Errors on client side, however only the weapon filters are giving issues (from what I can tell)

### Actual behaviour
Weapon filters don't work

### Steps to reproduce the behaviour 
1. Use shops
2. Check client side RPTs

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
```
20:35:31 Error in expression <hVehInfo;  _control lbAdd (_vehicleInfo select 3);  _control lbSetPicture [(lbSi>
20:35:31   Error position: <select 3);  _control lbSetPicture [(lbSi>
20:35:31   Error Zero divisor
20:35:31 File core\shops\fn_vehicleShopMenu.sqf [life_fnc_vehicleShopMenu], line 37
```
```
20:49:17 Error in expression < else {_itemInfo select 1}];  _itemList lbSetData[(lbSize _itemList)-1,_itemInfo>
20:49:17   Error position: <lbSetData[(lbSize _itemList)-1,_itemInfo>
20:49:17   Error Type Any, expected String
20:49:17 File core\shops\fn_weaponShopFilter.sqf [life_fnc_weaponShopFilter], line 37
```
```
20:54:18 Error in expression <_fnc_fetchCfgDetails;  _pic = (_details select 2);  };  if ([_x] call in_fnc_lev>
20:54:18   Error position: <select 2);  };  if ([_x] call in_fnc_lev>
20:54:18   Error Zero divisor
20:54:18 File core\shops\fn_clothingFilter.sqf [life_fnc_clothingFilter], line 37
20:54:18 Error in expression <ualTo "") then {  _list lbAdd (_details select 1);  } else {  _list lbAdd _displ>
20:54:18   Error position: <select 1);  } else {  _list lbAdd _displ>
20:54:18   Error Zero divisor
20:54:18 File core\shops\fn_clothingFilter.sqf [life_fnc_clothingFilter], line 37
20:54:18 Error in expression <Value [(lbSize _list)-1,_price];  _list lbSetPicture [(lbSize _list)-1,_pic];  }>
20:54:18   Error position: <lbSetPicture [(lbSize _list)-1,_pic];  }>
20:54:18   Error Type Any, expected String
20:54:18 File core\shops\fn_clothingFilter.sqf [life_fnc_clothingFilter], line 37
```

----

Mission version: 5.0

Launcher version: 1.5.140900

Game version: 1.68.140908

Branch: Main

**Comment by Jawshy** [comment]
I cannot reproduce any of those above error in expression errors when using the framework build as of [db15496](https://github.com/AsYetUntitled/Framework/tree/db15496ef2a457a3efa2eea49ff8ae6eb792f831).

**Comment by SimZor** [comment]
Tbh, I think this error spat out sometimes even before the update.

**Comment by DarkSilencerZA** [comment]
It definitely does happen. Very frequently for some people, and not so frequent for others.

**Comment by SimZor** [comment]
Although, ArmA update did not make this issue. Definately not.

**Comment by DarkSilencerZA** [comment]
Yeah, come to think of it, this issue was present before the update. It's just that I'm noticing it more frequently.

**Comment by fresqo** [comment]
yeah pretty sure the filters miss things. Katiba mags also from what i hear .. nice idea though... the thought was there..

**Comment by SimZor** [comment]
@DarkSilencerZA +1, liked it better when everything was just plain and not sorted into different tabs. Go into a shop, get up a menu with weapons, mags, attachments etc in one list.

**Comment by DarkSilencerZA** [comment]
@Jawshy Can we add this to the list of things to do? It's probably a good idea to go back to just ```items[] = ```. If server owners want the attachments / mags separate, all they need to do is create an extra shop.

**Comment by Jawshy** [comment]
@DarkSilencerZA, would you, or anyone else (@SimZor), be able to provide more specific reproduction steps for this error?

**Comment by DarkSilencerZA** [comment]
It used to happen randomly to my players. I always thought it was a user error, as it happened to some and not to others; till it happened to me today. I can't really say exactly what causes it or how it happens, but I can definitely say that the filters don't work correctly with specific weapons and it's been like that since the beginning of time; and for this reason I really don't see the need for them in the first place. Personally, I will be removing them and using ```items[] = {};``` for everything, with separators between sets.
