### ISSUE TITLE
Clothing Shop Interface Misalignment

### ISSUE THREAD

**Issue by gioporta** [AsYetUntitled/Framework#303]
### Expected behaviour
The Clothing Shop interface should be aligned properly.

### Actual behaviour
The Clothing Shop interface is misaligned and objects are overlapping each other.
![Example](http://i.imgur.com/ihfJVVn.jpg)

### Steps to reproduce the behaviour 
1. Open the clothing shop

My resolution is 1080p and my interface size is set to normal. The server is a vanilla installation running an unaltered Altis Life mission.

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
Did not find any errors in my client or server RPT logs, however here is the client one just in case:
https://pastebin.com/zWh7b9Wf

Issue is similar to one I found on an older Altis Life repository - danielstuart14/Altis-Life#10

----

Mission version: Clone of the mission repository as of yesterday - v5.0.0

Launcher version: 1.5.141066

Game version: 1.68.141112

Branch: master

**Comment by DarkSilencerZA** [comment]
Seems fine on my server, running 1080p, full gfx etc etc.

**Comment by gioporta** [comment]
What's your interface size? As far as I'm aware it seems to work properly if set to small.

**Comment by gioporta** [comment]
Here is what it looks like for me on small interface size (1080p, 16:9). Seems to be some sort of scaling issue.

![Example](http://i.imgur.com/QsCDCHP.jpg)

**Comment by gioporta** [comment]
Figured it out. Issue is due to the x and y coordinates of interface controls using safezone values (they change depending on your monitor) but the width and heights remain the same because they use absolute values.

By using absolute values for the x and y coordinates, there is no misalignment or overlapping.

![Example](http://i.imgur.com/f8FaSRS.jpg)

Here is my [modified clothing.hpp](https://gist.github.com/gioporta/f19881512cfa8006c164acb2623293cb) file that reflects the changes in x and y positions.

**Comment by DomT602** [comment]
Due to the lack of activity and that the issue was not confirmed (also worked fine for others), this will be closed.
