### ISSUE TITLE
Error compiling '' in 'xxxxx'

### ISSUE THREAD

**Issue by Thesam1798** [AsYetUntitled/Framework#305]
### Expected behaviour
The server should start without problems

### Actual behaviour
The server reads the mission but breaks after

### Steps to reproduce the behaviour 
1. start the server

### [LOG]
RPT: https://pastebin.com/raw/XJxFUjPr
Config Serveur File : https://pastebin.com/raw/1kSLeuKf
Serveur Network : https://pastebin.com/raw/FkWQP8qP
extDB3 : https://pastebin.com/raw/LHESpdUt

----

Mission version: Latest commit 0163211 V5.0.0

Launcher version: 1.5.141066

Game version: 1.68.141112

Branch: main / beta branch not specified

Information server :

Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) 1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22)

No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 8.7 (jessie)
Release: 8.7
Codename: jessie

----

Thank you for reading Thesam1798

**Comment by H0lidays** [comment]
Seems like your extDB3 is loading correctly, but your mission doesn't start(by start I mean the message "Starting Altis Life Init V.5.0"). Did you try to launch it in .PBO ?

**Comment by Thesam1798** [comment]
The mission of already in PBO

**Comment by Larry-Lizard** [comment]
This is exactly the same error i have encountered after the latest arma server update.

**Comment by Thesam1798** [comment]
Very good but how you solve this problem ?

**Comment by Larry-Lizard** [comment]
Well i fixed it by getting a windows server. I could not fix the error, even with the performance builds provided by the maker of extDB3

**Comment by Thesam1798** [comment]
Ok ... but the mistake that fact even on the bass missions of arma

**Comment by Larry-Lizard** [comment]
Yea as i said, probably a problem​ with the latest a3 server update

**Comment by DarkSilencerZA** [comment]
AFAIK, the following is related to certain gear armor ratings being outdated. It's Bohemia related.
```20:25:43 Error compiling '' in 'HitPelvis'
20:25:43 Error compiling '' in 'HitAbdomen'
20:25:43 Error compiling '' in 'HitDiaphragm'
20:25:43 Error compiling '' in 'HitChest'
20:25:43 Error compiling '' in 'HitArms'
20:25:43 Error compiling '' in 'HitLegs'
```

**Comment by BradenJM** [comment]
I believe this was caused by using extDB3 version 1028 when the latest Linux compatible version is (https://bitbucket.org/torndeco/extdb3/downloads/)[1023]. As you can see, it has the "+Linux" on the name, indicating I included the Linux specific files.

**Comment by BoGuu** [comment]
@BradenJM 
@Thesam1798 

Errors are from latest A3 update, another load of spam to clog up the RPT unfortunately.
