### ISSUE TITLE
Players can't move when dammaged.

### ISSUE THREAD

**Issue by nanougames** [AsYetUntitled/Framework#312]
Hi, i dont know why, but when players gets dammaged (+50%), they can't move. They're stuck. Normally, it's an animation with broken legs na? Do you know where is the problem?

**Comment by BoGuu** [comment]
You do have a damaged/broken leg animation now, but I've never heard of getting completely stuck (and have certainly never experienced it). Can you reproduce this every time? Have you altered the damage handler?

**Comment by nanougames** [comment]
`#include "\ALF_Client\script_macros.hpp"
/*
	File: fn_handleDamage.sqf
	Author: Bryan "Tonic" Boardwine

	Description:
	Handles damage, specifically for handling the 'tazer' pistol and nothing else.
*/
private["_unit","_damage","_source","_projectile","_part","_curWep"];
_unit = SEL(_this,0);
_part = SEL(_this,1);
_damage = SEL(_this,2);
_source = SEL(_this,3);
_projectile = SEL(_this,4);

//Handle the tazer first (Top-Priority).
if(!isNull _source) then {
	if(_source != _unit) then {
		if(_unit getVariable["Revive",false]) exitWith {};
		_curWep = currentWeapon _source;

		if(_curWep in ["ALF_Pioche","ALF_Batte","ALF_Hache","ALF_Faux"]) then {
			if(_source isKindOf "Man" && alive _unit) then
			{
				_damage = (getDammage player) + 0.015;
			};
		};

		if(_projectile in ["ALF_B_Taser"] && _curWep in ["ALF_X26"]) then {
			private["_distance"];
			_distance = 50;
			_damage = false;
			if(_unit distance _source < _distance) then {
				if(!life_istazed && !life_isknocked && !(_unit getVariable ["restrained",false])) then {
					[_unit,_source] spawn life_fnc_tazed;
				};
			};
			//Temp fix for super tasers on cops.
			_damage = false;
		};

		//THIS IS WHERE THE NEW VDM STOPPER IS ADDED - REMOVE IF BUGGED
		if ((vehicle _unit) isEqualTo _unit) then
		{
			_isVehicle = vehicle _source;
			if (_isVehicle isKindOf "Air" OR _isVehicle isKindOf "Car" OR _isVehicle isKindOf "Boat") then {
				_damage = (getDammage player) + 0.3;
				[player,"amovppnemstpsraswrfldnon",true] remoteExecCall ["life_fnc_animSync",RCLIENT];
			};
		};
	};
};
_damage;`

This is my handleDamage... Nothing wrong i guess.... But every time after after car shooting or anything else, players gets stuck... can't move !!

**Comment by H0lidays** [comment]
Try removing VDM stopper and see if it's working correctly.

**Comment by DarkSilencerZA** [comment]
lol... got the same issue now too... wtf?
