### ISSUE TITLE
House

### ISSUE THREAD

**Issue by mur202** [AsYetUntitled/Framework#313]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
Items should save

### Actual behaviour
Items does not save when you relog

### Steps to reproduce the behaviour 
1. put items inside your container
2. logout
3. log back in and the items are gone

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
<Check your client and server RPT and extDB3 logs for errors and warnings.>
<If there are relevant messages and they are short then post them here with code formatting.>
<If there are relevant messages and they are long then upload the whole file to GitHub, Pastebin, or Hastebin.>

----

Mission version: <See core/init.sqf, briefingName in mission.sqm, or changelog in briefing.sqf for your mission version.>5.0

Launcher version: <In the Arma 3 launcher go to ⚙ OPTIONS and click the version info below to copy it to your clipboard.>

Game version: 1.68

Branch: 5.0

**Comment by setoy** [comment]
Cannot reproduce with repo version.

**Comment by coresync2k** [comment]
same thing here, cant reproduce with actually repo version

**Comment by Dim2ke** [comment]
@mur202 
I tried and I can not reproduce not the error, is it concerned any object objects specifically?

**Comment by Jawshy** [comment]
Closed; others cannot reproduce bug.
