### ISSUE TITLE
Clothing bug

### ISSUE THREAD

**Issue by SalihF7** [AsYetUntitled/Framework#315]
### Expected behaviour
When he comes out of the game and enters again, he remains on the equipment. The price is not decreasing

### Actual behaviour
http://plays.tv/video/58ee1f7df083d56e16/bu

### Steps to reproduce the behaviour 
1.  Open the clothing shop. (Same and ESC click)

http://plays.tv/video/58ee1f7df083d56e16/bu

Mission version: v5.0
Launcher version: 1.5.141155
Game version: 1.68.141205
Branch: main / beta branch not specified

**Comment by samurai111** [comment]
confirmed

**Comment by Wackbatt** [comment]
Confirmed the described behavior, looking into a fix.

**Comment by C74K** [comment]
.rpt file link ?

**Comment by Wackbatt** [comment]
For what?

**Comment by SimZor** [comment]
@Wackbatt so how is your looking into a fix going? 🗡

**Comment by BlackFisch** [comment]
I don't know how the state of this issue is, but a possible solution would be to check in fn_escInterupt for other opened dialogs. Will create a PR soon
