### ISSUE TITLE
Money Glitch with chopshop

### ISSUE THREAD

**Issue by numpty9989** [AsYetUntitled/Framework#318]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
Money Should Go In Bank

### Actual behaviour
Money In Bank Duped into cash also got the Chop shop cash in cash

### Steps to reproduce the behaviour 
1. https://youtu.be/30agb7ftfNs?t=61
link to proof

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
No Errors
Chopshop File Stock 5.0 file

----

Mission version: <See core/init.sqf, briefingName in mission.sqm, or changelog in briefing.sqf for your mission version.>5.0

Launcher version: <In the Arma 3 launcher go to ⚙ OPTIONS and click the version info below to copy it to your clipboard.>Latest Launcher Version

Game version: 

Branch:

**Comment by SalihF7** [comment]
`_nearVehicles = nearestObjects [getMarkerPos (_this select 3),_chopable,15];
_nearUnits = (nearestObjects[player,["Man"],500]) arrayIntersect playableUnits;
if (count _nearUnits > 1) exitWith {hint localize "STR_NOTF_PlayerNear"};

added > fn_chopShopMenu.sqf

**Comment by numpty9989** [comment]
how does that fix the Bank Dupe

**Comment by SimZor** [comment]
Think @BoGuu said he was doing a queue system instead of some hotfix.

**Comment by numpty9989** [comment]
oh soz xD

**Comment by DomT602** [comment]
The money was intended to be paid as cash in hand (rather then the bank), this can be changed for your server relatively easily. As this is a non-issue, this will be closed.
