### ISSUE TITLE
fn_playerSkins undefined.

### ISSUE THREAD

**Issue by Leigham** [AsYetUntitled/Framework#327]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
Clothing should be placed on the player based on  server set variables.

### Actual behaviour
Clothing was set correctly it seems but script errors.

### Steps to reproduce the behaviour 
A big playerskins file. (both cop and swat level are defined)

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
 8:52:47  Mission id: 988b506ee5d06a5dc501dac3ddaf494644ad4fb6
 8:52:47 Error in expression <)))then{
switch (true) do
{
case ((call life_coplevel == 0) || (call life_coplev>
 8:52:47   Error position: <life_coplevel == 0) || (call life_coplev>
 8:52:47   Error Undefined variable in expression: life_coplevel
 8:52:47 File core\functions\fn_playerSkins.sqf [life_fnc_playerSkins], line 94
 8:52:47 Error in expression <lice\uniforms\1.paa";
};
};
};
if((call life_swatLevel > 0) && ((str(player) in >
 8:52:47   Error position: <life_swatLevel > 0) && ((str(player) in >
 8:52:47   Error Undefined variable in expression: life_swatlevel
 8:52:47 File core\functions\fn_playerSkins.sqf [life_fnc_playerSkins], line 132

----

Mission version: <See core/init.sqf, briefingName in mission.sqm, or changelog in briefing.sqf for your mission version.>
5.0
Launcher version: <In the Arma 3 launcher go to ⚙ OPTIONS and click the version info below to copy it to your clipboard.>

Game version: 

Branch:

**Comment by fresqo** [comment]
from my knowledge this is not a framework issue as life_swatLevel is not a thing
. also life_coplevel is a const variable, you can't call it like you are. Your scripting error sorry, Look at how life_coplevel is called in other scripts and replicate it for your swat stuff.

**Comment by Leigham** [comment]
I tried the same thing i even tried replicating the default script  and still giving the swat level error

**Comment by imKLM** [comment]
have you applied the most recent commit to the framework which fixes this issue? (like i said on discord)
https://github.com/AsYetUntitled/Framework/commit/349ce59a068011352842b2ea7b9ed64f5d1a619d

p.s you may have to set life_swatlevel the same way that life_coplevel is set (if you havent already)

**Comment by Leigham** [comment]
Thanks @imKLM  Yeah it was changing the gear before checking the level xD so just move load gear till after the switchcase, thanks :)
