### ISSUE TITLE
Bug Door Federal Bank

### ISSUE THREAD

**Issue by Dim2ke** [AsYetUntitled/Framework#329]
### Expected behaviour
When the "boltcutter" is used the doors of the federal bank open

### Actual behaviour
When the "boltcutter" is used the doors of the federal bank remain closed and we c'ant open the doors, if the item is reused, we get the messsage "the door is already unlocked"
### Steps to reproduce the behaviour 
1. buy boltcutter
2. go to the federal Bank
3. use boltcutter and wait finish process
4. Open door

Mission version: 5.0.0
Map: Tanoa
Launcher version: 1.5.141155
Game version: 1.68.141205
Branch: Main

**Comment by BoGuu** [comment]
Anything in your RPTs? (See the issue template)

**Comment by Dim2ke** [comment]
I have no log RTP, I put hint in the script and it looks to run normally until the end.
I did the following tests:
```
_b = cursorObject;
stat = _b getVariable "locked";
Hint format ["% 1",_stat];
Result
Any
```
I tried to put the variable with the command setVariable, the variable is well put on the building but not of opening of door.
If someone could do a test and confirm the result it would be great

**Comment by imKLM** [comment]
have you edited the mission.sqm at all?

**Comment by Dim2ke** [comment]
@imKLM 
sorry but I did not understand what you are asking me

**Comment by imKLM** [comment]
have you made any changes to the files or are they all default straight from the github repo? i.e. have you made any changes to the mission.sqm or any other files?

**Comment by Dim2ke** [comment]
hi @imKLM 
I added my script to the mission, but I'm sure it's not related to my script because they are totally unrelated and are not related to the federal bank or the
I will try with the master without modification and keep you informed boltcutter

**Comment by Dim2ke** [comment]
Hi @imKLM
I just tried with the mission without any changes
I only change minimum cops required online to rob the Federal Reserve from 5 to 0 in Config_Master.hpp
`minimum_cops = 0; //Minimum cops required online to rob the Federal Reserve`
Result 
Doors do not open

**Comment by MrMax000** [comment]
Test : open your mission.sqm in editor and enables dynamic simulation on the dome ( Land_Dome_Big_F ) !

**Comment by Leigham** [comment]
the issue here is bis changed the selection names.

**Comment by Jason2605** [comment]
I have just tested using a bolt cutter on all doors within the federal reserve and there were no issues.
