### ISSUE TITLE
Choppers are Exploding after recover from garage on top of buildings

### ISSUE THREAD

**Issue by diegobh** [AsYetUntitled/Framework#330]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
Recover the chopper from garage, spawning it on a helipad at the top of a hospital building.
OR at top of any building. Spawns now don't have the Z value for height, so its causes a lot of issues.

### Actual behaviour
The chopper is spanwned but inside the hospital building and it's exploding.

### Steps to reproduce the behaviour 
1. Place on the mission one hospital building ([Screnshot](https://s3.amazonaws.com/files.enjin.com/743768/Images/Buildings/A3%20Hospital.jpg)) / ([Code](https://pastebin.com/0jmTteHU))
2. Set the garage spawn (Markers -> System -> Empty) to the top of the building, on the helipad. ([Code](https://pastebin.com/7nujYXbW))
3. Place the Medic's Helis Seller / Garage. ([Code](https://pastebin.com/hmwjWBQr))
4. Take out your chopper from the garage.

----

Mission version: Tanoa Life RPG v5.0.0

Launcher version: 1.5.141155

Game version: 1.68.141205

Branch: Main

**Comment by J4Wx** [comment]
The issue you're reporting here, isn't a bug in the framework, but is that you've missed a step.

Medic Helicopter garages rely on the name of the marker to determine whether or not they must be spawned on the roof of the nearest hospital. To add your marker to this array you must go to dialog\function\fn_unimpound.sqf, on line 46 you'll see:

```if (life_garage_sp in ["medic_spawn_1","medic_spawn_2","medic_spawn_3"]) then {```

Add your marker name to the array, and that should work just fine. The reason for this methodology is that `getMarkerPos` always returns a height at terrain level, and so a marker alone is not enough to calculate the spawn position of the helicopter.

**Comment by diegobh** [comment]
You're right, thanks a lot.

Just another question, please.

If the building isn't the hospital E.G any custom building with a helipad on the top of it.
On this case, how to set the height to top of building instead of terrain level, please?

Thank you!

**Comment by BoGuu** [comment]
Take a look at the current exception in the code for the hospital & helipad, to get a grasp of how it's done (just need to replicate). I'm closing this now, as it's a non repo issue from here. If you need further help, use the Discord :)
