### ISSUE TITLE
No DebugConsole

### ISSUE THREAD

**Issue by Dim2ke** [AsYetUntitled/Framework#334]
### Expected behaviour
Open the debug console from the admin menu
### Actual behaviour
When you click on the debug button from the admin menu, the debug console opens but is not displayed [screenshot](https://img4.hostingpics.net/pics/484386201705200130181.jpg)
### Steps to reproduce the behaviour 
1. Open admin menu
2. click on buton "debug"
----
**I searched and found this
https://feedback.bistudio.com/T124835**

----
Mission version: 5.0.0
Launcher version: 1.5.141753
Game version: 1.70.141764
Branch: Master

**Comment by imKLM** [comment]
can confirm, seems like they removed it. will try to make a temporary one for now

**Comment by AWildTeddyBear** [comment]
To clarify, there is no issue here -- This is part of the new ArmA Update.. To fix this "issue" you **have** to be logged in as admin into the server before you can access debug console now. Hope this saves some frustration.

**Comment by imKLM** [comment]
Yeah it's a shame, working on an alternate at the moment. will probably still be open to the same security issues but hey ho

**Comment by ShadowRanger** [comment]
The only workaround to this issue is making your own custom debug menu. You can pretty much duplicate the default debug console identically by copying the associated classes and scripts and just editing them to remove the new checks.

**Comment by imKLM** [comment]
Bare in mind im pretty sure this still has security risks but #335 
will look at making it better later

**Comment by Dim2ke** [comment]
@imKLM 
Thanks a lot for the console debug this helps me a lot

**Comment by imKLM** [comment]
@Dim2ke bare in mind its not that secure. i would only suggest using it for development purposes and disable it once the server goes live. i'll do a bit more work on it to put it on server side etc
