### ISSUE TITLE
Speeding up Progress Bar - New Issue

### ISSUE THREAD

**Issue by DankToad** [AsYetUntitled/Framework#336]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

**Expected behavior:**
The progress bar should follow the set timing.

**Actual behavior:**
You can increase the progress bar speed via increasing FPS.

**Steps to reproduce:**
Well it's pretty simple, lower your render distance to 500m. Start repairing a vehicle (to create the progress bar) now open your map and zoom all the way in to any location (this will boost your FPS) now watch the massive difference in the bar speed. 

**Logs:** N/A

**Mission version:** 53

**Launcher version:**
Launcher version: 1.5.141829
Game version: 1.70.141838
Branch: main / beta branch not specified

**Comment by DankToad** [comment]
Just to note I have completely remade the progress bar script but the issue also happens on the latest version of Altis Life (worry not I have tested this, it's not a theory).

**Comment by ColinM9991** [comment]
On inspection, I can see that the problem here is that the scripts implementing progress functionality use `sleep` to do so, the briefing on the Bohemia Wiki page for sleep outlines that it gets its update on framerate, which means the issue you're reporting is tying directly in with the `sleep` function.

Fixing this is basically updating those scripts using progress bars and replacing `sleep` -> `uiSleep`

https://community.bistudio.com/wiki/sleep

**Comment by setoy** [comment]
@ColinM9991 Wouldn't it be a good way to change every `sleep` inside the script to `uiSleep`?

**Comment by ColinM9991** [comment]
If it's appropriate without adding much overhead then yes, although this is all client side anyway so overhead depends on the users PC which is a black box to us.

**Comment by DankToad** [comment]
Can confirm after testing uiSleep resolves the issue. Good spot there @ColinM9991

**Comment by ColinM9991** [comment]
Have you created a pull request? The issue isn't resolved until then and still lives in the framework.

**Comment by DankToad** [comment]
@ColinM9991 my bad I completely forgot. I will do that now.

**Comment by ColinM9991** [comment]
@DankToad let me know when it's done and I'll give the scripts a sweep review

**Comment by ColinM9991** [comment]
So have you forgotten again @DankToad ?
