### ISSUE TITLE
Database Players-Table

### ISSUE THREAD

**Issue by z0ckyZockt97** [AsYetUntitled/Framework#337]
I used your altislife.sql but my MySQL-Server show me the following error:

> Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

How can i fix this error?

Ps.: Sry for my bad english ;)

**Comment by Jason2605** [comment]
Update your MySQL server

**Comment by BradenJM** [comment]
See #276

**Comment by z0ckyZockt97** [comment]
Thank you.
I have fixed the problem.
