### ISSUE TITLE
House Dupe

### ISSUE THREAD

**Issue by kadir6185** [AsYetUntitled/Framework#344]
### Expected behaviour
<What should have happened?>
I dont know maybe sell and now close dialog.

<What actually happened?>

If you get an auto clicker you can buy a house, then spam sell the house with an auto clicker and you will get a lot of money.

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
<Check your client and server RPT and extDB3 logs for errors and warnings.>
<If there are relevant messages and they are short then post them here with code formatting.>
<If there are relevant messages and they are long then upload the whole file to GitHub, Pastebin, or Hastebin.>

http://oi67.tinypic.com/pnox.jpg

Mission version: 5

**Comment by H0lidays** [comment]
Give us full log file please, the picture you linked doesn't help us in any way.

**Comment by SimZor** [comment]
It's just fine @H0lidays @kadir6185 

Should be fixed in https://github.com/AsYetUntitled/Framework/pull/349

@ColinM9991 @BoGuu

**Comment by CreatorSolly** [comment]
@SimZor yeah I hope it gets fixed very soon. I tried it on a server called Altis Horizon and it worked.

**Comment by Yigith4n** [comment]
@kadir6185 Çözüm gayet basit kadir kardeşim ama kendin oturup yap isterim bir döngü oluşturarak bu olayı çözebilirsin.
