### ISSUE TITLE
Escorting flooding the server?

### ISSUE THREAD

**Issue by Fubister** [AsYetUntitled/Framework#348]
### Expected behaviour
Escorted player should be detached, and battleye should log it once

### Actual behaviour
Server get's flooded, everyone stops moving, i lose connection to rcon even though server is working, it takes a restart to make everything back to normal. Battleye logs: #0 "escorting" = false 2:2510 C_man_1 for over **few hundred thousand times** in one second.

### Steps to reproduce the behaviour 
1. I really tried hard to reproduce but I can't i happens once every few days.

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
Due to insanely big log, i have to paste only those from the time this lag happened 
Server RPT: https://pastebin.com/VcHbTnUs
Battleye setvariable.log: https://pastebin.com/NUaMSQ3p

----

Mission version: 5.0.0

Launcher version: Latest

Game version: Latest

Branch: Latest

**Comment by ColinM9991** [comment]
With no server logs, and no other information, there is nothing we can do or investigate.

Pastebin or file-share your RPT file(s) (Client/Server) and we can look, otherwise this issue will be closed.

**Comment by Fubister** [comment]
You were right, I have updated my post

**Comment by ColinM9991** [comment]
What is the file size of your RPT, can you file-share it?

**Comment by Fubister** [comment]
sure http://www76.zippyshare.com/v/rVHl9C8g/file.html

please don't mind the mods, exactly the same thing happened before I modded the server. On BI forums I was advised to get more powerful machine, and I did, yet didn't help

**Comment by ColinM9991** [comment]
Have you tried

- A windows server
- No Task Force Radio

Can you also link the BI forums post?

**Comment by Fubister** [comment]
I was on a windows machine before, and as I mentioned this was happening before I modded the server, in fact the mission was pretty unchanged by me. https://forums.bistudio.com/forums/topic/202322-unusual-server-lag/

**Comment by ColinM9991** [comment]
All of the advice is in that thread really.

1. Use a default, unedited Altis Life mission with addons
2. Use a default, unedited Altis Life mission with no addons
3. Use a default vanilla server with a basic ArmA mission with addons
4. Use a default vanilla server with a basic ArmA mission with no addons

If the issue occurs during those 4 tests then we'll investigate further via Discord, you can find me there with the name "Elite III"

I'm going to close this issue as it's not related directly to this repository, and (as mentioned in that thread) is a network issue relating to dropped packets, so there is no change we can make to resolve this.
