### ISSUE TITLE
[Limit Vehicles]Maximum store vehicles the limit per player garage

### ISSUE THREAD

**Issue by Pega86** [AsYetUntitled/Framework#35]

**Comment by BoGuu** [comment]
Would you care to actually write an issue?

**Comment by tkcjesse** [comment]
Not really.

**Comment by Jawshy** [comment]
Closing due to lack of effort put into writing the 'issue'. 

Feel free to add a meaningful description and then reopen the issue.

**Comment by Jawshy** [comment]
See https://github.com/AsYetUntitled/Framework/pull/110.
