### ISSUE TITLE
Error in expression | No Hint Displayed When Buying a House with a Garage

### ISSUE THREAD

**Issue by kurganpepper** [AsYetUntitled/Framework#350]
### Expected behaviour

Approaching the house with a garage to buy, should be the hint
RPT logs: https://pastebin.com/3eHz6YzJ

### Actual behaviour

Approaching the house with a garage to buy is not showing the hint

### Steps to reproduce the behaviour 

1. To approach the house with garage
2. Press the "WIN"

Should be(check please)):
Line 112
_Btn2 buttonSetAction hint format [localize "STR_pInAct_GarageExtNOTF",LIFE_SETTINGS(getNumber,"houseGarage_buyPrice")];

I just started to learn ARMA-3, so it seems to work))).

----

Mission version: 5.0.0
Map: Tanoa
Game version: 1.72.142223

_-- Edit (formatting/layout): @Jawshy [2017-10-26]_

**Comment by Dim2ke** [comment]
Fix for buy/sell garage of the house #281

**Comment by kurganpepper** [comment]
Expected behaviour:
 [screenshot](http://fotohost.by/image/2jLr)

Actual behaviour:
 [screenshot](http://fotohost.by/image/2jLu)


Not displayed hint when buying a house with a garage
Mission version: 5.0.0
Map: Tanoa
Game version: 1.72.142223
