### ISSUE TITLE
Houses delete when pressing U

### ISSUE THREAD

**Issue by viper18276** [AsYetUntitled/Framework#352]
### Expected behaviour
Should  unlock house.

### Actual behaviour
When pressing U the house will physically delete from screen, but other players still see the house.

### Steps to reproduce the behaviour
Started happening when battleye filters were put in.

----

Mission version: 5.0.0

**Comment by ColinM9991** [comment]
This is not an issue with the mission repository, mission issues go here, server issues go on the discord.
