### ISSUE TITLE
Wiki enhancing --> Setup part.

### ISSUE THREAD

**Issue by H0lidays** [AsYetUntitled/Framework#359]
### Expected behaviour
Nothing special, except be more precise.

### Actual behaviour
Lack of useful informations

### Steps to reproduce the behaviour 
Just read.

### Changes
1. For the MySQL part, when you're using the altislife.sqf file, you have to edit the database username for the procedures, else they will not run and it'll be broken.
Example : 
``CREATE` DEFINER=`arma3`@`localhost` PROCEDURE `resetLifeVehicles`()
BEGIN
  UPDATE `vehicles` SET `active`= 0;
END$$``

Here, the username is arma3. If you're using root or something else, it won't work.
2. Create separate tutorials for extDB2 install **and** extDB3 install. Plus, add a upgrading tutorial to switch from extDB2 to extDB3, both client and server side.

Feel free to add your suggestions here.

**Comment by ColinM9991** [comment]
The point with 1 is that people actually create a less privileged SQL user, instead of using 'root'.

**Comment by H0lidays** [comment]
yeah of course, maybe it could be easier to create the user with the database, with the right perms only. we could add this into the altislife.sql, so everything's setup'd and protected

**Comment by ColinM9991** [comment]
Agreed, feel free to make a Pull Request for that and it can be merged in.

**Comment by H0lidays** [comment]
working on it atm, will release it probably today or tomorrow :D

**Comment by Jawshy** [comment]
Reference: https://github.com/AsYetUntitled/Framework/pull/363

**Comment by Jason2605** [comment]
#363 has been merged.
