### ISSUE TITLE
Weapon dupe

### ISSUE THREAD

**Issue by samurai111** [AsYetUntitled/Framework#361]
### Expected behaviour
If you put weapon inside vehicle and press alt+f4 then re log you should not have your weapon back in your hand

### Actual behaviour
if you put your weapon inside vehicle and press alt+f4 while inventory open, then rel log your weapon duplicated, in your hand and inside vehicle inventory

### Steps to reproduce the behaviour 
1. open vehicle inventory
2. put your weapon inside vehicle inventory and press alt+f4 while open inventory
3. re log then your weapon in your hand and in vehicle inventory

----

Mission version: 5.0

Launcher version: 1.5.142122

Game version: 1.74.142559

Branch: main / beta branch not specified

**Comment by jordanlee833** [comment]
Without going in-game, this looks to be a valid issue. Your inventory is not pushed to DB until you close the inventory [in fn_inventoryClosed.sqf](https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/core/functions/fn_inventoryClosed.sqf#L33)

I can't find an event for inventory changed or something similar [on the wiki](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers).

I'll try it in-game when I get a chance.

**Comment by jordanlee833** [comment]
Issue confirmed.

**Comment by jordanlee833** [comment]
Working on fix.

**Comment by Jawshy** [comment]
Hi, @jordanlee833. Do you have an update on the progress of your fix for this issue?

**Comment by samurai111** [comment]
we need to update player info before disconnect to fix this problem.

**Comment by SimZor** [comment]
@samurai111 no lol, that would just make things worse. What needs to be done is to sync when an item has been put inside a vehicle, i.e. the put eventhandler (put weapon in vehicle - sync player instantly after).

**Comment by samurai111** [comment]
what if we add gear check in fn_clientDisconnect.sqf?

**Comment by SimZor** [comment]
Why would you do that? @samurai111

That does not stop Alt+F4 and is no need to if you just use the eventhandler.

**Comment by jackmsimo** [comment]
@SimZor Could just have an InventoryOpened eventhandler which sync's data to server..

**Comment by SimZor** [comment]
@jackmsimo why would you do that? that would mean syncing at unneccesarry times. Just use onPut / onTake evh's IIRC and that should be fine and be as accurate as you can get.
