### ISSUE TITLE
say3D - Update Syntax

### ISSUE THREAD

**Issue by BlackFisch** [AsYetUntitled/Framework#366]
Since Arma 3 Update 1.70 say3D allows the use of Array-Format, to get additional parameters for distance and pitch (see: https://dev.arma3.com/post/spotrep-00067). This should be reworked, in order to make sirens and other stuff audible at distances over 100m.

-> Fix already WIP, Pull Request will follow soon

----

Mission version: all

Game version: 1.70+

Branch: all

**Comment by ColinM9991** [comment]
Is this something you could PR?

**Comment by BlackFisch** [comment]
PR? (sorry, I'm not a native English speaker ^^)

**Comment by BradenM** [comment]
@BlackFisch PR = Pull Request

_Sent from my Samsung SM-G950U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by BlackFisch** [comment]
...okay, I could have guessed it ^^ 
Obviously it is :) I just had to fork the repository before doing that ^^
