### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by SQLStatement** [AsYetUntitled/Framework#370]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
<What should have happened?>
The MySQL database should have loaded.
### Actual behaviour
<What actually happened?>
It gave me an error.
ERROR 1293 (HY000) at line 70: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
This one, to be exact
### Steps to reproduce the behaviour 
1. <How did you break it?>
I did not.
### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
<Check your client and server RPT and extDB3 logs for errors and warnings.>
<If there are relevant messages and they are short then post them here with code formatting.>
<If there are relevant messages and they are long then upload the whole file to GitHub, Pastebin, or Hastebin.>

----

Mission version: <See core/init.sqf, briefingName in mission.sqm, or changelog in briefing.sqf for your mission version.>

Launcher version: <In the Arma 3 launcher go to ⚙ OPTIONS and click the version info below to copy it to your clipboard.>

Game version: 

Branch:

**Comment by Jason2605** [comment]
Please update your MySQL server to at least version 5.6.5

**Comment by imKLM** [comment]
Should probably edit the server setup wiki to mention the version requirement

**Comment by ColinM9991** [comment]
PR it
