### ISSUE TITLE
Can drop car keys whilst in locked vehicle

### ISSUE THREAD

**Issue by imKLM** [AsYetUntitled/Framework#372]
<Please review the guidelines for contributing to this repository. The link is above.>
<If you are reporting a bug then you must use the provided issue template.>

### Expected behaviour
Should not allow players to drop the key to the vehicle they are in whilst it is locked as if they do they will become trapped and can only get out if a cop pulls them out or if they press escape and click respawn.

### Actual behaviour
Can trap yourself in your own car

### Steps to reproduce the behaviour 
Get in car, Lock car, Drop key, cry.

----

Mission version: 5.0
Branch: dev

**Comment by ColinM9991** [comment]
Or add functionality to unlock the car from inside the car, because without that this is a problem you'd experience in real life.
