### ISSUE TITLE
life_server/init.sqf line 89

### ISSUE THREAD

**Issue by WRInspire** [AsYetUntitled/Framework#377]
### Expected behaviour
Server Startup

### Actual behaviour
Server Sits on "Waiting for server"

### RPT

https://pastebin.com/zweYFnsR
(hastebin was down)
I am using the latest version of the init.sqf from the life_server.

Mission version: 5.0.0

**Comment by ColinM9991** [comment]
This isn't an issue with the repository, head over to Discord and seek help there.
