### ISSUE TITLE
Housing work ? 

### ISSUE THREAD

**Issue by Finch29** [AsYetUntitled/Framework#38]
Hi,
the problem is : When i buy a house, the database don't have any information about the house but when i put container(s), only container(s) go in database ... Have you solution ?

**Comment by BoGuu** [comment]
Sorry, what files are you using?

**Comment by Finch29** [comment]
your files whithout any modifications

**Comment by BoGuu** [comment]
Post your client/server RPT's, and extDB log

**Comment by Finch29** [comment]
So it's a mistake by my self ! ^^ i have add " garage " manualy in DB but i have forgot the " Default Value " !!! >< Sorry ;) Thx a lot for your job ! ;)
