### ISSUE TITLE
Error in expression - fn_notifyAdmins

### ISSUE THREAD

**Issue by Jawshy** [AsYetUntitled/Framework#383]
### Expected behaviour
No script error. 

### Actual behaviour
Script error on joining game. 

### Steps to reproduce the behaviour 
1. Launch and join a server running the framework as of commit [3014462](https://github.com/AsYetUntitled/Framework/tree/3014462a955eef6f951005ad41a6738100e42bfc). 
2. Choose any role (cop, medic, or civlian) and load into the game. 
3. Observe error. 

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
```
"--------------------------------- Starting Altis Life Client Init ----------------------------------"
"------------------------------------------ Version 5.0.0 -------------------------------------------"
[...]
Error in expression < !hasInterface) exitWith {}; 
if ((call life_adminlevel) < 1) exitWith {};
hint >
  Error position: <life_adminlevel) < 1) exitWith {};
hint >
  Error Undefined variable in expression: life_adminlevel
File SpyGlass\fn_notifyAdmins.sqf [SPY_fnc_notifyAdmins], line 66
```

### Relevant files
- [Framework/Altis_Life.Altis/SpyGlass/fn_notifyAdmins.sqf](https://github.com/AsYetUntitled/Framework/blob/98d19e4208ec199fbf27ea9f5e5132383eab7327/Altis_Life.Altis/SpyGlass/fn_notifyAdmins.sqf)
- Files that mention [SPY_fnc_notifyAdmins](https://github.com/AsYetUntitled/Framework/search?utf8=%E2%9C%93&q=SPY_fnc_notifyAdmins&type=)
----

Mission version: Version 5.0.0 as of commit [3014462](https://github.com/AsYetUntitled/Framework/tree/3014462a955eef6f951005ad41a6738100e42bfc). 

Launcher version: 1.5.142859

Game version: [1.76.142872](https://dev.arma3.com/post/spotrep-00073)

Branch: main / beta branch not specified

**Comment by SimZor** [comment]
@Jawshy most likely the variable is not initiated yet, when it checks?
