### ISSUE TITLE
Keys to houses and vehicles

### ISSUE THREAD

**Issue by CentrinoJa** [AsYetUntitled/Framework#396]
### Expected behaviour
After purchasing a house or vehicle the key should remain on your key chain.

### Actual behaviour
When you get disconnected or log out and back into the server without a server restart the key chain is empty and you cannot access your cars or house.

### Steps to reproduce the behaviour
1. Buy a vehicle or house
2. unlock and use said vehicle or house
3. lock said vehicle or house
4. disconnect from server
5. log back onto the server and check key chain

Mission version: 4.4r4

Launcher version: 1.5.143475

Game version: 1.76.143187

Branch: main

Any help or advice with this issue would be much appreciated if  the issue is not experienced elsewhere

**Comment by Jason2605** [comment]
This seems to be an issue regarding changes you have made, can you confirm this is an issue with the framework itself rather than a version of the framework which has been modified?

**Comment by H0lidays** [comment]
Could you give us your server logs ? That's probably, like @Jason2605 said, something by your side and not the framework.

**Comment by BlackFisch** [comment]
1. House keys get retrieved from the database evrytime you connect by default. If not, you changed something and that doesn't work anymore.
2. Keychain-Variable does not get deleted when dis-/reconnecting, but when restarting the game or playing on another server. If it does get deleted on your server (when reconnecting), you changed something that does make it not work.

We run a server and never had a problem, never even heard something relatable from others.

**Comment by CentrinoJa** [comment]
Hey guys,

Thanks for the reply I have been super busy with work and will find/upload the logs to here as soon as I possibly can, like I said work is hell right now. as for it been an issue with just our server that was what I was not wanting to hear haha but I have spent all the spare time i had looking into trying to fix this issue.

Kind Regards,
CentrinoJa

**Comment by BlackFisch** [comment]
No Problem. 
I think that is not a problem for here, if you want you can come to https://native-network.net/ and you'll get help

@Jason2605 I think his issue can be closed

**Comment by Jason2605** [comment]
There is also a discord available to seek help for issues such as these.
