### ISSUE TITLE
Altis life Stuck of Setting Cilent info please wait

### ISSUE THREAD

**Issue by malekbaradei881** [AsYetUntitled/Framework#400]
I just started my server and works correctly and the mission does and everything but
When i join it says Setting Cilent info please wait Its just stuck there forever ive been trying to fix it for 5 days failed every time

If anyone can help me like by joining a discord/TS  and help me from there 

# **Please help im really inneed of it**

**Comment by Jason2605** [comment]
Join the discord linked on this repo for support, as this is not an issue with the repo and more of a user error i will close this issue, but feel free to reach out to us by other methods.

**Comment by malekbaradei881** [comment]
where is it ?

**Comment by malekbaradei881** [comment]
can u just post it please

**Comment by Justin-pDev** [comment]
https://discord.gg/EaB7Jgw
