### ISSUE TITLE
Items dupe

### ISSUE THREAD

**Issue by MrWeyLand** [AsYetUntitled/Framework#405]
http://d1playscdntv-a.akamaihd.net/video/HViwHQlAg1m/processed/720.mp4
Here is the video

### Expected behaviour
You should only get the one item you buy that you have money too

### Actual behaviour
What is happing when you are putting 15000 in an buy it you get what you can have in your inventory

### Steps to reproduce the behavior
As you can see in the video you buy 15000(It seems like it have to be 15000 only you can not do it with etc. 20000) of something that you don't have money to and then you press buy 15000 of a item and then buy 1 of another item you can afford and then you get the other item

**Comment by mySNAKE** [comment]
Good after testing, to fix that.

Since you have to be quick to do this, you just have to disable the buy button for 2 to 3 seconds and then reactivate it for the player to redeem.

**Comment by H0lidays** [comment]
Solution n°2 : simply make a check to see if the user is trying to buy more than x items at once. I think 100 should be okay, because even if the user can only buy 100 by 100, the delay between actions is like 1-2s so there's no big problem.

**Comment by MrWeyLand** [comment]
It works with the new #403 so you cant dupe any more
