### ISSUE TITLE
Police and Medic Lights not appearing after disconnect and rejoining

### ISSUE THREAD

**Issue by Nathan021000** [AsYetUntitled/Framework#407]
### Expected behaviour
Police and Medic Lights should stay visible to everyone whether they join after or before the lights we're activated

### Actual behaviour
If you leave and re-join the server, the lights are not visible anymore, however, you still know they are on as you have to press Shift + L twice to reactivate them so you can see them again

### Steps to reproduce the behaviour
1. Put lights on using Shift + L
2. Leave the server to the lobby.
3.Re-join and go to the same place where the car was placed. You will see lights are not visible
4. Get back into car and see that you have to push Shift + L twice to make them visible again

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
No logs entries produced

----

Mission version: 4.4r3, but other versions have been tested and they get the same outcome

Launcher version: Launcher version: 1.5.14375

Game version: 1.80.143869

Branch: main / beta branch not specified

**Comment by SalihF7** [comment]
and If you hold down "Shift + L" you will see your traffic increase. This problem goes on until the server shuts down

**Comment by Nathan021000** [comment]
What do you mean? You shouldn't have to hold it down, just press it once to turn on then press it again to turn off. However, turn the lights on then someone joins after they won't be able to see the lights until he turns them off and on again... not sure whether you understood what I meant?

**Comment by SalihF7** [comment]
if you hold the "SHIFT + L" key, the server crashes or lag grows %90.

**Comment by BlackFisch** [comment]
try adding a JIP-Tag to the remoteExec-Call of the sirenLights
-> https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/core/cop/fn_sirenLights.sqf#L21
-> https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/core/medical/fn_medicSirenLights.sqf#L21

**Comment by Nathan021000** [comment]
@BlackFisch. Yeah that one sounds a bit complicated for me a step to step would really help ;)

**Comment by BlackFisch** [comment]
Sit back ^^ I'll take my time maybe this afternoon and make a pull request ;)

**Comment by BlackFisch** [comment]
Pull request out now :P I tried to keep it as simple as possible while adding the feature in a neat way :)
