### ISSUE TITLE
NO SUCH IP PLS

### ISSUE THREAD

**Issue by lolamess0901** [AsYetUntitled/Framework#408]
### Expected behaviour

it should be able to access the server without any problem

### Actual behaviour

it happened that in the logs of extdb there is to mark no such node (.IP)

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
 EXTDB LOGS
https://pastebin.com/GwyqKadV
EXTDB CONF
https://pastebin.com/LSjQeEJe
init.sqf life serveur
https://pastebin.com/TfhAA11t
description
https://pastebin.com/ffiytU6j

----

Mission version:  4.4r4

Launcher version: 

Game version: 

Branch:

**Comment by lolamess0901** [comment]
Serveur : MySQL (localhost via TCP/IP)
Type de serveur : MySQL
Version du serveur : 5.7.19 - MySQL Community Server (GPL)
Version du protocole : 10
Utilisateur : root@localhost
Jeu de caractères du serveur : UTF-8 Unicode (utf8)

**Comment by Jawshy** [comment]
@lolamess0901, issue tickets are for reporting issues with the mission. As this is a user error I will close this issue. 

For help setting up a server please see [Setup Server](https://github.com/AsYetUntitled/Framework/wiki/Setup-Server) and [Troubleshooting](https://github.com/AsYetUntitled/Framework/wiki/Troubleshooting). For community chat support you can join the [Discord server](https://discord.gg/EaB7Jgw).
