### ISSUE TITLE
Wanted System Cleanup

### ISSUE THREAD

**Issue by BoGuu** [AsYetUntitled/Framework#41]
Need's a bloody good cleanup

**Comment by dbenson24** [comment]
I actually rewrote this also, made it into a Public Variable system with a refresh rate similar to how I did dynamic market. Made it much more responsive when alot of players were online and reduced database load

**Comment by nearbyplayer** [comment]
So I know you're planning to fix this up and since dbenson24 has some fixes to performance... wouldn't it be easy to tackle [#299 - Custom Jail Times [suggestion]](https://github.com/ArmaLife/Framework/issues/299)? Just an idea...

**Comment by BoGuu** [comment]
@nearbyplayer 

It's already 'cleaned', reworks are future things. What do you mean easy to tackle? Shouldn't make a difference

**Comment by nearbyplayer** [comment]
@BoGuu 
Alright... I was just suggesting that if you were already working on the wanted system it might have been easier than going back and fourth if it was going to be a feature (I only mentioned it because it's still in the next Milestone on the ArmaLife/Framework repo). That's all I meant.

**Comment by BoGuu** [comment]
@nearbyplayer 

Nono, not working on it in that sense. Just cleaning up the messy code. It'll get done in due course (infact it should only take **minimal** changes). However, only bugs will be carried over from the Arma Life repo to here, i.e, no milestones etc. This is a totally separate project.

**Comment by nearbyplayer** [comment]
@BoGuu 
Alright, I was aware this was a separate repo. However, I was not aware only bugs would be carried over, thanks for clarifying. Well, anyways I'll just let you guys get back to work, thanks again.
