### ISSUE TITLE
Players Markers

### ISSUE THREAD

**Issue by RoberioJr** [AsYetUntitled/Framework#423]
### Expected behaviour
player markers should appear on the map...
//
### Actual behaviour
When ever I go into the map as an EMS it does not show where people request to be revived.
When ever I go into the map as a Cop it does not show other officers markers or my marker on the map. For this one as well it does the same on EMS and Civilian Side.
//
### Steps to reproduce the behaviour
1. Open The Map.
//
### [RPT]
--> https://pastebin.com/s03ZmZzv
//
Mission version: 5.0.0
//
Launcher version: 1.5.143751
//
Game version: 1.80.143869
//
Branch: main / beta branch not specified

**Comment by Ermen07** [comment]
This is the fix:
https://github.com/AsYetUntitled/Framework/issues/425
