### ISSUE TITLE
Database player saving

### ISSUE THREAD

**Issue by torchgodz** [AsYetUntitled/Framework#427]
How do you get your database to run 2 timestamps for the player saving positioning? It has always thrown an error so i have to delete one of them and will not save player position between server restarts.

**Comment by Jason2605** [comment]
MySQL versions before 5.6 do not allow multiple timestamps columns within the same table, just update and you shouldn't get any errors.

**Comment by Jason2605** [comment]
Since there has been no response, and this isn't actually an issue with the framework i will close this issue.
