### ISSUE TITLE
Re-animate Rebel Hummingbird

### ISSUE THREAD

**Issue by tkcjesse** [AsYetUntitled/Framework#43]
We need to animate the benches back onto the rebel hummingbird when pulled from the garage... 
Just putting this here because I know I'll forget. Easy fix though.

**Comment by jcbjoe** [comment]
Ill get this done, shouldn't take long...

**Comment by jcbjoe** [comment]
#54

**Comment by tkcjesse** [comment]
I'm a dumbass
