### ISSUE TITLE
ALTISLIFERPG.COM IS BROKEN FOR NEW USERS

### ISSUE THREAD

**Issue by OpenPollSal** [AsYetUntitled/Framework#439]
altisliferpg.com user registration is broken. The site is using an outdated version of captcha and won't display the security check to users. Same goes for Steam account user login. 

Displaying the HTML under the security check gives me this:
![image](https://user-images.githubusercontent.com/37787393/39101943-7668f9de-466d-11e8-9cf9-b9f028a24800.png)

That version of captcha has been out of use over a month. Nobody can register to the site without passing it, which is impossible.

 I would use contact us on the bottom of the website but you need to file a captcha to send a message. If whoever responds to this cannot deal with the issue, can you please relay it to somebody who can?

Thank you.

**Comment by imKLM** [comment]
Hello, This repository is not affiliated with the domain altisliferpg.com
I have however passed your concern onto the owner of that forum, hopefully they will be able to resolve it

**Comment by imKLM** [comment]
I have spoken to MoNtEcRiStO© over at Altisliferpg.com and he says that the issue should be fixed now and to try again, if not then Steam login should still work. Any further issues please contact him at https://discord.gg/JHZMqW
