### ISSUE TITLE
I do not see request medic and respawn buttons

### ISSUE THREAD

**Issue by BraK3NN** [AsYetUntitled/Framework#440]
### Expected behaviour
request medic and respawn buttons show

### Actual behaviour
https://www.youtube.com/watch?v=6c_bD-ZcpcE

Game version: v5

Branch:

**Comment by imKLM** [comment]
Hello, have you modified any files at all or is this with all default files?

**Comment by BraK3NN** [comment]
I modified fn_escInterupt.sqf for this https://github.com/AsYetUntitled/Framework/issues/315

**Comment by Jawshy** [comment]
@BraK3NN, revert any files that you have changed back to their default state, and then let us know if that did or did not fix your issue.

**Comment by BraK3NN** [comment]
@Jawshy Problem is resolved when I return to default but the clothes are working for the bug

**Comment by Jawshy** [comment]
Closing because this is not an issue with the repository files.
