### ISSUE TITLE
Licenses are not visible

### ISSUE THREAD

**Issue by BraK3NN** [AsYetUntitled/Framework#442]
### Expected behaviour
See licenses

### Actual behaviour
I do not see licenses

RPT
https://hastebin.com/uzebiperiy.tex

player_inv.hpp

https://hastebin.com/ruduvayizu.scala

----

Game version: v5

**Comment by BraK3NN** [comment]
okey.

**Comment by Jawshy** [comment]
Closing as per @imKLM's comment.
