### ISSUE TITLE
Player Markers On Map

### ISSUE THREAD

**Issue by RoberioJr** [AsYetUntitled/Framework#444]
The player markers (gang members, players, medics can not know where the players died) do not appear on the map.
Steps to reproduce the behaviour: Open The Map.

Mission Version: 5.0.0
[RPT](https://pastebin.com/ej5Zgzij)
Game Version: 1.82

**Comment by imKLM** [comment]
Have you updated your version of 5.0 to the current files? I believe this issue was fixed recently

**Comment by RoberioJr** [comment]
@imKLM Yes, here is the [MISSION](https://github.com/RoberioJr/Arma-3/tree/master/Cidade%20De%20Deus/CidadeDeDeus.Altis).

**Comment by imKLM** [comment]
Does this happen with vanilla files? (no changes) or just your files?
If it only happens with your files due to changes you have made please ask for help on our Discord server as issues are reserved for problems with the framework files

**Comment by imKLM** [comment]
Please try with the default 5.0 files that are currently on the repo, I can see your files are currently different. You may have an issue with your files causing the issue
