### ISSUE TITLE
Inventory deletion

### ISSUE THREAD

**Issue by Legion64** [AsYetUntitled/Framework#446]
### Expected behaviour

Expected behavior does not delete the player inventory, license etc.

### Actual behaviour

When every game is entered, the player inventory, license etc. is erased.

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)

RPT: https://hastebin.com/pugibaqixa.tex
extDB2: https://hastebin.com/fapakaqoza.http

**Comment by Jawshy** [comment]
Hi, @Legion64. After reviewing the log files, it looks like you are running an older version of Altis Life RPG that is no longer supported. Try using the latest build of the mission ([v5.0.0](https://github.com/AsYetUntitled/Framework/archive/master.zip)), or seek help in our Discord server (link in [README](https://github.com/AsYetUntitled/Framework/blob/master/README.md#links)).
