### ISSUE TITLE
The problem of deleting bots

### ISSUE THREAD

**Issue by Legion64** [AsYetUntitled/Framework#447]
### Expected behaviour
The bots required to log in are not deleted. And they're moving on their own.

### Actual behaviour
After the game is installed, the bots on the island need to be deleted.

### Steps to reproduce the behaviour
Log in to the game as a policeman. Then open the map. You'll see that the bots are wandering on the island on their own.

Problem Image: 
![Image of Problem](https://cdn.discordapp.com/attachments/239303696020668416/445178771482476564/Adsz.png)
----

Mission version: Altis Life RPG V5.0.0

Launcher version: 1.5.144689

Game version: 1.82.144710

Branch: main / beta branch not specified

**Comment by Legion64** [comment]
#1
mojombo#1
mojombo/github-flavored-markdown#1

**Comment by Wackbatt** [comment]
You have AI enabled on in your mission.sqm or description.ext by the looks of it.

**Comment by Legion64** [comment]
So how do we turn it off? Every time I enter the game, the AI writes.

![Image Of Problem](https://image.ibb.co/kjwFFd/Ads_z2.png)

**Comment by Legion64** [comment]
Okay, thank you so much. I fixed it.
