### ISSUE TITLE
playertags.sqf

### ISSUE THREAD

**Issue by BraK3NN** [AsYetUntitled/Framework#449]
ı change color blue name tags for cops but not change v5 is problem help me pls ?

**Comment by BraK3NN** [comment]
No, related to this v5 version. I tried everything

**Comment by PrilA3** [comment]
> ı change color blue name tags for cops but not change v5 is problem help me pls ?

The original playerTags file is fine. You have changed something to make it not fine.

**Comment by Jason2605** [comment]
Not an issue with the framework.
