### ISSUE TITLE
OpFor faction do not spawn with gear - Array errors

### ISSUE THREAD

**Issue by lpjn** [AsYetUntitled/Framework#454]
### Expected behaviour

OpFor faction to spawn with gear. All files related to gear spawning (ie loadout sqf files) are copied identically from the civ faction, no issues there.

### Actual behaviour

OpFor faction spawn naked, errors are seen in server RPT logs that look familiar to Array errors.

### Steps to reproduce the behaviour
1. 
Spawn as OpFor 
### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)

----

Mission version:  v5.0 Tanoa

Errors below when spawning as OpFor faction:
Error in expression <) isEqualTo _uid) exitWith {
_x set [1, _time_gathered];
_x set [2, time];
};
} >
  Error position: <_time_gathered];
_x set [2, time];
};
} >
  Error Undefined variable in expression: _time_gathered
File \life_server\Functions\PlayTime\fn_setPlayTime.sqf [TON_fnc_setPlayTime], line 24
Error in expression <st pushBack [_uid, _new];
};
[_uid,_new select 1] call TON_fnc_setPlayTime;

};
>
  Error position: <select 1] call TON_fnc_setPlayTime;

};
>
  Error Zero divisor
File \life_server\Functions\MySQL\fn_queryRequest.sqf [DB_fnc_queryRequest], line 230

**Comment by Alex715** [comment]
i have already got undefined variable _time_gathered, random for me but very rare.

check insert_time cologne in ur players table, if there is not a null result instead of a number.

**Comment by imKLM** [comment]
by default the framework does not support Opfor,
if you intent to use Opfor you will need to implement it yourself, there are plenty of guides online for how to do this.
As this issue is not an issue with the current code it will likely be closed, if you are having issues with something you are trying to add yourself please feel free to join the Discord server listed in the readme for help

**Comment by lpjn** [comment]
Hey @imKLM 

I have already set up the faction in its entirety (following tutorials), it functions correctly in every aspect aside from gear! :(

Okay np I'll join the Discord.

Closed
