### ISSUE TITLE
Access locked containers. 

### ISSUE THREAD

**Issue by Kapppa** [AsYetUntitled/Framework#456]
### Expected behaviour
Stops you from accessing locked container.

### Actual behaviour
You can access any locked container.

### Steps to reproduce the behaviour
1. Place item on floor near the container you wish to open.
2. Stand next to the container you wish to open.
3. Look at the item on the floor and access the grounditem inventory.
4. At the top you will see container click it. You now have access to a locked container. 

### Recommend fix
Inside of "core/functions/fn_inventoryOpened.sqf" there are two containers passed via the event handler. Check them both not just the primary container.  
https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#InventoryOpened

**Comment by Leigham** [comment]
You just need to check for nearby locked containers for this

**Comment by Kapppa** [comment]
> You just need to check for nearby locked containers for this
if near locked container, dont show the players inventory.
The eventhandler has object passed to it but the code is not using it. Why would you need to check the near by objects?

**Comment by DomT602** [comment]
Thankyou @Kapppa for reporting this. As above this issue has been sorted via #484. We appreciate your help in improving the framework!
