### ISSUE TITLE
Rental car && Garage spawn

### ISSUE THREAD

**Issue by Finch29** [AsYetUntitled/Framework#46]
Hi, 
When i try to put a rental car in garage, i have a hint : " Try to store your vehicle ..." but why he don't tell me " Sorry you can't store because it's a rental car ! " ?? ;) 

Edit : When a vehicle is on the spawn point and i want to span another on the same point, the hint tell me : Spawning vehicle please wait..

**Comment by setoy** [comment]
Yes, rental cars cannot be stored, AFAIK. However a message should indicate that and nota  generic "Try to store".

**Comment by BoGuu** [comment]
Fix is coming in Patch 2, thanks for the report. If you're interested, it's down how fn_broadcast deals with its localizing: https://github.com/AsYetUntitled/Framework/blob/3f9a27418ff307c300a11b89b2e7c566f4ca2b7e/Altis_Life.Altis/core/functions/network/fn_broadcast.sqf#L15-L17

**Comment by CarlosHingel** [comment]
@BoGuu You guys are like machines on this repo! So the problem on the other one was liberty and leadership? What a shame there. Keep the good work.
