### ISSUE TITLE
Database not saving gear anymore..

### ISSUE THREAD

**Issue by Cocaina-Ricky** [AsYetUntitled/Framework#461]
### Expected behaviour

Sync Data > supposed to save gear that's what I expected, but I got multiple reports saying "My gear doesn't save", "My vehicles do not save"

The datbase literally saves nothing.

### Actual behaviour

So one day, we were playing it's perfectly fine.. The next day, the whole server turns against us and now anything we do does not save, whether we sync data 10 minutes before, 30 minutes before, etc. It does not save anything.

### Steps to reproduce the behaviour
1. 
No idea what you mean by this.

Press Sync Data > Wait 2 mins, go back to lobby, it's supposed to sync, you come back as a civilian / officer etc and nothing saves. You're back to your default gear.

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)

I have checked the RPT with a developer of mine and nothing there. Same with extDB.
----

Mission version: 

Launcher version: 

Launcher version: 1.5.144689

Game version: 1.82.144710

Branch: main / beta branch not specified

**Comment by Logfro** [comment]
Did you change anything from the mission or the life_server? Or is it 100% from this GitHub?

**Comment by FallenUK** [comment]
Without any logs no one is gonna be able to help you.

**Comment by Cocaina-Ricky** [comment]
@Logfro 
@FallenUK 

I recall changing the mission file & life_server, but I reverted them to a backup and it still doesn't work.

I can give you logs.

Pastebin: RPT > https://pastebin.com/N0DgsCqW
Pastebin: ExtDB > https://pastebin.com/SAMqK2S7

Altis Life Version : 4.4r4

**Comment by FallenUK** [comment]
I suggest upgrading to the newest version of altis life + extdb3. Will have a look at the logs when I get time thou.

**Comment by Cocaina-Ricky** [comment]
@FallenUK 

Most of our development is done on 4.4r4, we won't be switching anytime soon. Like I stated above, it has only recently starting doing this and we have no idea why.

**Comment by Leigham** [comment]
I think someones telling porkies.
because if the function is being called to save to the database, and it fails it will produce an error.

**Comment by Leigham** [comment]
```
> 14:16:37 "extDB2: Connected to Database"
14:16:37 "----------------------------------------------------------------------------------------------------"
14:16:37 "---------------------------------- Starting Altis Life Server Init ---------------------------------"
14:16:37 "------------------------------------------ Version 4.4r4 -------------------------------------------"
14:16:37 "----------------------------------------------------------------------------------------------------"
14:16:37 Strange convex component322 in a3\structures_f\research\dome_big_f.p3d:geometryFire
14:16:37 Strange convex component327 in a3\structures_f\research\dome_big_f.p3d:geometryFire
14:16:37 "<infiSTAR.de> infiSTAR dll loaded successfully"
14:16:37 "<infiSTAR.de> Roleplay Labs Altis Life | Development Server"
14:16:37 "<infiSTAR.de> License accepted!"
14:16:37 "<infiSTAR.de> Loading infiSTAR code.."
14:16:37 CallExtension 'extDB3' could not be found
```
Looks to me like someone has already tried changing to extdb3

**Comment by Leigham** [comment]
If its calling the extension, but it fails it will tell you extdb logs.

**Comment by Cocaina-Ricky** [comment]
So what's my best bet? Does extDB3 work with 4.4R4?

**Comment by Leigham** [comment]
if you use the extdb debug pbo
it will tell you all calls made to extdb.

**Comment by Cocaina-Ricky** [comment]
extdb debug pbo? What's that... I have just tried googling it and it comes up with nothing.

**Comment by Cocaina-Ricky** [comment]
@Leigham 

Ignore that last post, this is my pastebin for the debug:
https://pastebin.com/nQEjsxNd

**Comment by imKLM** [comment]
are your procedures properly set up in your database?

**Comment by Leigham** [comment]
Was that just on a server startup ?
because if it was, thats really not going to help is it.

**Comment by Jason2605** [comment]
This is not an issue with the framework, but more an issue with your particular files. There is a discord link on the readme of the repo, and you are welcome to get support via that.
