### ISSUE TITLE
Garage storing vehicle don't work on custom vehicles

### ISSUE THREAD

**Issue by btx78000** [AsYetUntitled/Framework#465]
### Expected behaviour
If u buy a car, 1 line in vehicles SQL database is added, and spawned ingame, then updated on storing.

### Actual behaviour
If u buy a car, nothing is added in SQL database, but vehicle is temp spawned ( until next reboot ), and can't be stored.

### Steps to reproduce the behaviour
Add a modded vehicle, then try to buy it and store it.

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)

----

Mission version: 5.0.0

Launcher version: Last

Game version: Last

Branch:

**Comment by Jason2605** [comment]
Modded cars are not part of the framework, and the issues here on github are intended to be of use when an issue is found within the framework. If you join the discord we would be more than happy to help you out there!
