### ISSUE TITLE
Vehicle Shop is not closing after vehicle is purchased

### ISSUE THREAD

**Issue by Angrygargamel** [AsYetUntitled/Framework#474]
we encounter this problem in at least 3 different servers/missions now
3d vehicle preview is enabled if that matters (havent tested without yet to be honest)

### Expected behaviour
buy vehicle - shop window should close

### Actual behaviour
buy vehicle - shop window stays open

### Steps to reproduce the behaviour
open the vehicle shop - buy a vehicle

Mission version: 5.0

Game version: happens at least with the 5 last versions of A3 so i would say its not a3 version related

the closedialog line is at the end of the file but it just does nothing

**Comment by imKLM** [comment]
Is this happening on your own server or servers you are joining?
If this is happening on your own server, have any of the 3d preview files or the vehicle store dialogs been altered?

**Comment by Angrygargamel** [comment]
one is my own server
and 2 others where i help developing

shop files havent been changed so far

**Comment by imKLM** [comment]
Can you give any further steps on how to replicate this issue?
Also have you tried pulling any changes to 5.0 since your fork/dl?
I have been unsuccessful so far in my own testing.

**Comment by Angrygargamel** [comment]
alright guys... seems it was our own mistake..
there was an uisleep 3 placed to make sure the vehicle spawns without any damage under any circumstances
