### ISSUE TITLE
House Container Duplication 

### ISSUE THREAD

**Issue by Leigham** [AsYetUntitled/Framework#488]
### Expected behaviour
when player logs out, to cleanup containers.

### Actual behaviour
does not delete the container so can duplicate the containers and contents.

### Steps to reproduce the behaviour
Spawn in, logout, and spawn in again.

Bad conversion: array
Error in expression <"_pos"];
{
deleteVehicle _x;
} forEach (nearestObjects[_pos,["Box_IND_Grenades_F>
  Error position: <nearestObjects[_pos,["Box_IND_Grenades_F>
  Error 0 elements provided, 3 expected
File \life_server\Functions\Housing\fn_houseCleanup.sqf [TON_fnc_houseCleanup], line 19
-->

**Comment by CarlDizy** [comment]
oof

**Comment by Jason2605** [comment]
#494
