### ISSUE TITLE
Job Creator (Software)

### ISSUE THREAD

**Issue by TaktischerSpeck** [AsYetUntitled/Framework#497]
Hey,

in front, this is not a bug.

I only don't know how else I would get some attention from you guys :D

so I made a java based tool which automatically creates the syntax and code for new jobs (resources etc).

Its open source and free to use for everyone

if you might want to give some editors a hint here is my git link:

https://github.com/TaktischerSpeck/Life_Job_Creator/releases

also there gonna be a new release soooooooonnnn with English translation.

hope I could help somebody with this tool :)

**Comment by Jason2605** [comment]
I appreciate that you are trying to get some traffic for the tool however issues on the repo are generally reserved for problems/feature requests for the base framework. You are more than welcome to join our discord and paste a link to this in our #server_tools channel.
