### ISSUE TITLE
Cannot register unknown string

### ISSUE THREAD

**Issue by TaktischerSpeck** [AsYetUntitled/Framework#501]
The Log says:

Cannot register unknown string STR_3DEN_CAMERA_NAME
Cannot register unknown string STR_DIFF_SCENE_ONLY
Cannot register unknown string STR_DIFF_SCENE_AND_MAP

Maybe just add this to the Stringtable?

<Package name="unknown_strings">
		<Key ID="STR_3DEN_CAMERA_NAME">
			<Original>IDK</Original>
		</Key>
		<Key ID="STR_DIFF_SCENE_ONLY">
			<Original>IDK</Original>
		</Key>
		<Key ID="STR_DIFF_SCENE_AND_MAP">
			<Original>IDK</Original>
		</Key>
	</Package>

**Comment by Angrygargamel** [comment]
this is caused by bughemia with one of their updates a while ago
you can report it to their bugtracker and wait until they fix it some day
or you can just ignore it at all as it doesnt break anything yet

**Comment by DomT602** [comment]
As mentioned above, these strings are in base code. Feel free to report it here: https://feedback.bistudio.com/
As we cannot do anything about this, the issue will be closed.
