### ISSUE TITLE
Vehicle purchase: forgot check

### ISSUE THREAD

**Issue by aecy** [AsYetUntitled/Framework#504]
Video : https://youtu.be/KVKIECM3mFQ

### Expected behaviour
When buying a vehicle, it should buy and close the dialog, for now everything is ok.

### Actual behaviour
When a player buys a vehicle, if he uses a car clicker to buy, it stacks the vehicles and generates a lot of explosion!

### Steps to reproduce the behaviour
1. Go to a shop for buy a vehicle.
2. Open an auto clicker.
3. Configure the auto clicker for spam the buy button.

**I pull a new request for fix the glitch**

----

Mission version: Altis Life RPG v5.0.0

Launcher version: 1.5.144923

Game version: 1.84.144923

Branch: main / beta branch not specified

**Comment by moeck** [comment]
Maybe you can just change the dialog buttons with "closeDialog 0;"

**Comment by aecy** [comment]
i make that for all of my project, no more dup right now :)
