### ISSUE TITLE
Recent Commit broken Vehicle Unlocking

### ISSUE THREAD

**Issue by HarrisonCode** [AsYetUntitled/Framework#516]
https://github.com/AsYetUntitled/Framework/commit/e2c443d51782ae71aa14cfac99bdceca8746313f#diff-43c869a83228d28fb92fea556a47c74a

Made it so you can't unlock vehicles in game. May need someone to test but had issue and only fix was to revert file.

**Comment by DomT602** [comment]
@HarrisonCode Thanks for bringing this up, found the issue and sorted it.
