### ISSUE TITLE
2nd Main Weapon (Rocket-Launcher) are not saving on the Database

### ISSUE THREAD

**Issue by powerafro2** [AsYetUntitled/Framework#520]
Hello,

The 2nd Main Weapons (Rocket-Launcher) are not saving on the Database. 
I have already tried adding it in the fn_loadGear.sqf and fn_saveGear.sqf, but then I get an error from the fn_loadGear.sqf that the gear can´t load it from Database and I´m not coming into the Spawnscreen. Have any an Fix of these please? 

Thanks in advance, I need it :D

**Comment by DomT602** [comment]
This is not an issue with the framework as this isn't intended behaviour (thus not a bug). This would be something you can do to make your server different. Therefore, this issue will be closed.
