### ISSUE TITLE
error in fn_copInteractionMenu.sqf

### ISSUE THREAD

**Issue by yatmanyatan** [AsYetUntitled/Framework#531]
10:30:39 Error in expression <_fnc_seizePlayerAction; closeDialog 0;";.        

if ((call life_coplevel) < _seizeR>
10:30:39   Error position: <.        

if ((call life_coplevel) < _seizeR>
10:30:39   Error Invalid number in expression
10:30:39 File core\cop\fn_copInteractionMenu.sqf [life_fnc_copInteractionMenu], line 141
10:30:39 Error in expression <_fnc_seizePlayerAction; closeDialog 0;";.        

if ((call life_coplevel) < _seizeR>
10:30:39   Error position: <.        

if ((call life_coplevel) < _seizeR>
10:30:39   Error Invalid number in expression
10:30:39 File core\cop\fn_copInteractionMenu.sqf [life_fnc_copInteractionMenu], line 141
10:30:39 Error in expression <ndOf "CAManBase&quot then {
if((_curTarget GVAR ["restrained",false]) && !dialog &&>
10:30:39   Error position: <GVAR ["restrained",false]) && !dialog &&>
10:30:39   Error Missing )
10:30:

**Comment by IceEagle132** [comment]
Share file with pastbin

**Comment by BoGuu** [comment]
Hi, could you please fill out the template you're given for issues?

It's not clear what version you're on (despite it being very old), and whether it's vanilla or not (seems not).

If the latter is the case, use the Discord & close this, if not, template
