### ISSUE TITLE
EXTDB_SETTING returns empty variables

### ISSUE THREAD

**Issue by Vlieker** [AsYetUntitled/Framework#545]
### Expected behaviour

EXTDB_SETTING(getText,"DatabaseName") and EXTDB_SETTING(getNumber,"HeadlessSupport") should return the right values from the config.

### Actual behaviour

They both returned empty, so my database does not connect, unless I hardcode the values.

### Steps to reproduce the behaviour
A normal server restart from today caused those variables to return empty.

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)

extDB3: Error with Database Connection in the server logs
extDB3: Config Error: : No such node (.IP) in the extDB3 logs

By hardcoding the variables it works again, but I am not supposed to, it should read the variable from the description.ext
----

Mission version: 5.0.0

**Comment by imthatguyhere** [comment]
It sounds to be like you have an error in a config that is causing an End of File previous to the DatabaseName. This doesn't occur in the default framework. Check your server RPT for errors and resolve them, especially anything config related.

**Comment by moeck** [comment]
this error is the result of a failure in the extdb-conf.ini. please rename the database in the brackets to altislife or the name you chose.

[altislife]

**Comment by Vlieker** [comment]
It seems it was a failing script on my side, which has been resolved with help from the script developer.

For everyone who has the issue with No such node (.IP) it means that there is an issue with your Altis_Life.Altis folder.

Op 4 apr. 2019 om 16:39 heeft moeck <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

this error is the result of a failure in the extdb-conf.ini. please rename the database in the brackets to altislife or the name you chose.

[altislife]

**Comment by Vlieker** [comment]
@moeck It was clearly not a failure in my settings, it was my missionfile returning empty setting variables

"".IP

**Comment by imthatguyhere** [comment]
As I said, it was a config EOF (I'm in that discord with you):
`13:18:11 Warning Message: Config : some input after EndOfFile.`

If the file ends before the DatabaseName in the config it wouldn't be able to read it from the config. Either way this issue can be closed as there's not a problem with the framework here.

**Comment by DomT602** [comment]
Issue solved, closed.
