### ISSUE TITLE
Configs - Apex

### ISSUE THREAD

**Issue by BoGuu** [AsYetUntitled/Framework#55]
We have *some* content already added to the configs: https://github.com/AsYetUntitled/Framework/tree/master/ApexContent. However it's lacking, and we need more **appropriate** things added.

Anyone up for it ;)?

P.S. Don't forget BattlEye

**Comment by Jawshy** [comment]
What content do we wish to add? Perhaps all of the Apex assets with the exception of the most heavily armed vehicles. 

See [here](https://arma3.com/apex) for a list of the Apex content.

**Comment by tkcjesse** [comment]
@BoGuu - Why just the Apex? Like look at the rebel that was for Altis... 

https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/config/Config_Weapons.hpp#L42-L62

Imo, either update it to have everything and comment out stuff. Or just let people do it themselves. I mean idk. I can offer my configs for Tanoa if ya want.

**Comment by BoGuu** [comment]
The way in which I look at the repo configs, is such that if you were to setup a fresh server, the configs would be perfectly acceptable to leave. Ofcourse people are free to change things as they see fit, but a good basis to start. I.e, adding content that is applicable to the shop, and not adding excessively over powered things (such as the Lynx, Armed vehicles etc). 

I'm not overly bothered about the configs, however it'd be nice to get them filled up and left for the next content release :+1:
