### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by Turdant** [AsYetUntitled/Framework#553]
### Expected behaviour
Server starts with missionfile loaded

### Actual behaviour
Server starts without loading the missionfile.

### Steps to reproduce the behaviour
1. Start the server with the batch file on the wiki
2. To fix replace it with this one(also updated for x64) https://pastebin.com/YPrh2dHv

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
N/A

----

Mission version: 5.0

Launcher version: 1.5.145631

Game version: 1.92

Branch: main / beta branch not specified

**Comment by Jason2605** [comment]
I've updated the wiki, thanks!
