### ISSUE TITLE
fn_clientDisconnect.sqf _side not init

### ISSUE THREAD

**Issue by Nark0t1k** [AsYetUntitled/Framework#556]
Forget:

private _side = side _unit;

**Comment by imthatguyhere** [comment]
Are you referring to the _side used here? https://github.com/AsYetUntitled/Framework/blob/master/life_server/Functions/Systems/fn_clientDisconnect.sqf#L23

**Comment by Nark0t1k** [comment]
Done ;-)

**Comment by Jason2605** [comment]
Yup, was fixed in the related PR above. Thanks for the issue :)
