### ISSUE TITLE
Wrong vehicle selling on chopshop

### ISSUE THREAD

**Issue by Casperento** [AsYetUntitled/Framework#567]
### Expected behaviour

We should be able to sell the selected vehicle on Chop_Shop's dialog while it's away from the shop

### Actual behaviour

The wrong vehicle is being deleted when you press the Sell button

### Steps to reproduce the behaviour
1. Get an expensive vehicle from garage/shop
2. Get a cheap vehicle from  garage/shop
3. Bring those vehicles to the nearest chop shop (ask for a friend to help you out)
4. Park your expensive vehicle beside the shop's npc and let your cheap vehicle far from it
5. Open the shop's dialog
6. Ask your friend to leave that expensive vehicle far away from the shop's position and bring the cheap one for it's old position (don't close the dialog until he is far away from you with the expensive vehicle)
7. Once you are with the expensive vehicle listed on the shop's dialog, click on the sell button and the cheap vehicle will get deleted and you will get the sell price of the expensive one on your wallet!

### Solution
Store vehicle's netId on the dialog's data field and don't use _nearVehicles variable again on fn_chopShopSell.sqf (once you already got it on fn_chopShopMenu.sqf). Check out on my Fork: https://github.com/Casperento/Framework/commit/8a4a7ac14e356e1d9dafa96ee4496cb8e08ed952

Mission version: all those which use _nearVehicles variable on fn_chopShopSell.sqf

Branch: master

**Comment by klmunday** [comment]
Nice spot! if the code in the commit you linked is current and solves the problem feel free to create a Pull Request!
