### ISSUE TITLE
Gang Disbanding

### ISSUE THREAD

**Issue by JManL46** [AsYetUntitled/Framework#579]
### Expected behaviour
Gang menu should be set to the 'create new gang' menu for all members in the gang which was disbanded

### Actual behaviour
Everyone but the gang leader's gang menu is set to the 'create new gang' menu. Gang leader still has the active gang menu while being told the gang was disbanded.

### Steps to reproduce the behaviour
1. Create a gang
2. Disband the gang
3. Open the gang menu

### [RPT] and/or extDB3 logs
Nothing in the logs to do with the gang when disbanded

----

Mission version: 5.0.0

Launcher version: 

Game version: 1.96.146070

Branch: main

**Comment by DomT602** [comment]
@JManL46 Thanks for the bug report, a PR has been submitted to fix this!
