### ISSUE TITLE
HUD not setting up on spawn

### ISSUE THREAD

**Issue by BlackFisch** [AsYetUntitled/Framework#614]
### Expected behaviour
HUD shows up after spawn selection

### Actual behaviour
It does not. Problem seems to be, that the HUD gets created in `fn_spawnConfirm.sqf` but gets created after the welcome-message display is created which results in the overlay being on that display instead of display 46. A fix should be pretty easy - just setup the hud before or after welcome message, I'll make a PR later

### Steps to reproduce the behaviour
1. setup server
2. join

----

Mission version: v5.0.0 Release

**Comment by Casperento** [comment]
I believe you're talking about the same thing of this PR: https://github.com/AsYetUntitled/Framework/pull/606

**Comment by BlackFisch** [comment]
okay, yeah I didnt see that :D I'll verify later that this fix works and close the issue :D

**Comment by Casperento** [comment]
it's something like that, but I think the PR owner could add your suggested fix in his changes.
