### ISSUE TITLE
DB-user arma3 can't DELETE

### ISSUE THREAD

**Issue by ErikMast3r** [AsYetUntitled/Framework#633]
### Expected behaviour
The user created from the sql-file do not have permission to use DELETE. For many operations he need this privileg.

### Actual behaviour
Now the user have no rights to do a DELETE, so the extDB-logs were spammed with errors.

### Steps to reproduce the behaviour
1. Use the latest master branch and latest extDB3-release
2. Execute the sql-file from the framework
3. Change the credentials in the extdb3-conf.ini to the given in the sql file
4. Start the server, load mission
5. Look at the extDB-logs

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
from the extDB3-log
`[15:40:12:817066 +01:00] [Thread 8176] extDB3: SQL: Error MariaDBStatementException1: DELETE command denied to user 'arma3'@'localhost' for table 'vehicles'
[15:40:12:817085 +01:00] [Thread 8176] extDB3: SQL: Error MariaDBStatementException1: Input: deleteDeadVehicles
[15:40:12:817918 +01:00] [Thread 5240] extDB3: SQL: Error MariaDBStatementException1: DELETE command denied to user 'arma3'@'localhost' for table 'houses'
[15:40:12:817933 +01:00] [Thread 5240] extDB3: SQL: Error MariaDBStatementException1: Input: deleteOldHouses
[15:40:12:818922 +01:00] [Thread 10336] extDB3: SQL: Error MariaDBStatementException1: DELETE command denied to user 'arma3'@'localhost' for table 'gangs'
[15:40:12:818945 +01:00] [Thread 10336] extDB3: SQL: Error MariaDBStatementException1: Input: deleteOldGangs`

----

Mission version: master/v6.0

Launcher version: Don't user the launcher

Game version: 1.96.146114

Branch: master

**Comment by BlackFisch** [comment]
Not a bug.

See: https://github.com/AsYetUntitled/Framework/blob/master/altislife.sql#L37

-> the new SQL creates the procedures with the current user as definer. Thus you have to create the user yourself and/or editor the privileges

**Comment by DomT602** [comment]
As @BlackFisch has described above, this is not a bug and is intended behaviour. If you need any help feel free to ask on the discord.

**Comment by BlackFisch** [comment]
`GRANT DELETE ON altislife.* TO 'arma3'@'localhost'`
-> replace `altislife` with your database name if it differs

**Comment by BoGuu** [comment]
> ```sql
> GRANT DELETE ON altislife.* TO 'arma3'@'localhost';
> FLUSH PRIVILEGES;
> ```
> 
> -> replace `altislife` with your database name if it differs

If you don't mind it having those permissions, that is

**Comment by BlackFisch** [comment]
> 
> 
> > ```sql
> > GRANT DELETE ON altislife.* TO 'arma3'@'localhost';
> > FLUSH PRIVILEGES;
> > ```
> > 
> > 
> > -> replace `altislife` with your database name if it differs
> 
> If you don't mind it having those permissions, that is

well, technically we force that with the procedures :D
though you could only grant them on the tables it really needs to:

```sql
GRANT DELETE ON altislife.vehicles, altislife.houses, altislife.gangs TO 'arma3'@'localhost';
FLUSH PRIVILEGES;
```

**Comment by BoGuu** [comment]
> > > ```sql
> > > GRANT DELETE ON altislife.* TO 'arma3'@'localhost';
> > > FLUSH PRIVILEGES;
> > > ```
> > > 
> > > 
> > > -> replace `altislife` with your database name if it differs
> > 
> > 
> > If you don't mind it having those permissions, that is
> 
> well, technically we force that with the procedures :D
> though you could only grant them on the tables it really needs to:

It's contained though, you can't just delete everything

**Comment by BoGuu** [comment]
Ref:

```
If the DEFINER clause is omitted, the default definer is the user who executes the CREATE PROCEDURE or CREATE FUNCTION statement. This is the same as specifying DEFINER = CURRENT_USER explicitly. 
```
