### ISSUE TITLE
ATM

### ISSUE THREAD

**Issue by MarsMoon81** [AsYetUntitled/Framework#636]
ATM withdraw or deposit  is reversed. 

When trying to withdraw money, I noticed that I couldn't withdraw even with money in the account. So I git deposit and I noticed it withdraw that account from my account. ALFramework 5.0

Nothing in the RPT logs or extdb3 logs shown on this error, just thinking the code is reversed.
Altis new copy of the ALFramework 5.0 was just downloaded. This is where I found the error on.

**Comment by Jason2605** [comment]
Hi there! Thanks for submitting a bug report, however we feel this is not an issue with 5.0. It's worth checking your files to ensure that the buttons are actually the correct way round here: https://github.com/AsYetUntitled/Framework/blob/v5.X.X/Altis_Life.Altis/dialog/bank.hpp

If you require some more support, feel free to join the discord and we can help you from there!

**Comment by MarsMoon81** [comment]
It’s the exact same, I downloaded the framework right from github have not
made any changes to anything

**Comment by BoGuu** [comment]
> It’s the exact same, I downloaded the framework right from github have not made any changes to anything

Have you changed your cash/bank variables?

**Comment by MarsMoon81** [comment]
No

**Comment by BoGuu** [comment]
> No

Can you verify that these lines/files are the same on your end?

https://github.com/AsYetUntitled/Framework/blob/v5.X.X/Altis_Life.Altis/dialog/bank.hpp#L51
https://github.com/AsYetUntitled/Framework/blob/v5.X.X/Altis_Life.Altis/dialog/function/fn_bankWithdraw.sqf#L17
