### ISSUE TITLE
storeVehicle can't find nearest vehicle

### ISSUE THREAD

**Issue by ErikMast3r** [AsYetUntitled/Framework#659]
### Expected behaviour
When I execute the "store vehicle in garage" it should be stored.

### Actual behaviour
When I put my vehicle in front of the npc (doesn't matter fresh buyed or a veh out of the garage) and execute the "store vehicle in garage" action, I get to this:
`if (isNull _vehicle) exitWith {
    hint localize "STR_Garage_NoNPC"
};`
This fault is since #346 
I can't figure out where the fault is. It should be in storeVehicle before this if-condition.
There is no error in the logs, so maybe he can't find a vehicle?!

Notice: I have the property vehicle_rentalReturn on true! It doesn't work for buyed and rented cars!

### Steps to reproduce the behaviour
1. Buy a car or call one from the garage
2. Go to the garage NPC
3. Try to store the vehicle

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)

----

Mission version: 6.0.0

Launcher version: I don't use the launcher

Game version: 1.98

Branch: master

**Comment by BlackFisch** [comment]
can confirm

**Comment by DomT602** [comment]
Fix is in #647 - just awaiting a review + merge.

**Comment by DomT602** [comment]
Fixed in #660.
