### ISSUE TITLE
Error: Object(х.ххх) not found

### ISSUE THREAD

**Issue by MasonsOD** [AsYetUntitled/Framework#661]
Good day, I came across this error when starting the server
Extract from RTP
Error: Object(2 : 553) not found
Error: Object(2 : 558) not found
Error: Object(2 : 560) not found
Error: Object(2 : 562) not found
Error: Object(2 : 564) not found
Error: Object(2 : 566) not found
Error: Object(2 : 568) not found
Error: Object(2 : 570) not found
Error: Object(2 : 572) not found
Error: Object(2 : 574) not found
Error: Object(2 : 576) not found
Error: Object(2 : 578) not found
Error: Object(2 : 580) not found
Error: Object(2 : 582) not found
Error: Object(2 : 584) not found
Error: Object(2 : 586) not found
Error: Object(2 : 588) not found
Error: Object(2 : 590) not found
Error: Object(2 : 662) not found
Hope this has a solution?

**Comment by BlackFisch** [comment]
No issue on this framework's side.
Happens if the deletion of objects is not properly broadcasted or trying to access local objects on a network device. not much you can do about it really

**Comment by MasonsOD** [comment]
Does it make sense to look for a solution to the problem ?? Or is it not significant

**Comment by BlackFisch** [comment]
I doesn't have any impacts on performance and the problem is pretty common and known, if you look for it on google
so no, probably not worth the hassle

**Comment by MasonsOD** [comment]
Yes, I searched a lot but didn’t find anything

**Comment by BlackFisch** [comment]
https://forums.bohemia.net/forums/topic/170354-object-not-found-spam-in-rpt/
Bug reports:
https://feedback.bistudio.com/T82940
https://feedback.bistudio.com/T79285
https://feedback.bistudio.com/T83321
https://feedback.bistudio.com/T77860
https://feedback.bistudio.com/T76277

you can find more than enough resources confirming this, it most likely just won't get any attention anymore. no performance impact and arma is technically end of life

**Comment by MasonsOD** [comment]
life_hc - Do not tell me why this folder and its bundle to load a word in the instructions about it

**Comment by BlackFisch** [comment]
instructions are outdated take a look in #645
