### ISSUE TITLE
drugdealer cleanup seem to have an issue

### ISSUE THREAD

**Issue by cryptearth** [AsYetUntitled/Framework#665]
### Expected behaviour
N/A

### Actual behaviour
N/A

### Steps to reproduce the behaviour
N/A

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)

server-console:
`Error in expression <bjNull];
if !(isNull _dealer) then {
_x setVariable ["sellers", [], true];
};
} >
  Error position: <setVariable ["sellers", [], true];
};
} >
  Error setvariable: Type String, expected Namespace,Object,Group,Display (dialog),Control,Team member,Task,Location
File \life_server\Functions\Systems\fn_cleanup.sqf [TON_fnc_cleanup]..., line 74`

Mission version: master branch commit a5a5821

Launcher version: N/A

Game version: N/A

Branch: see above

As for the linenumber: As I figured so far the enigne seem to count the line numbers after all includes are done - the actual line number within the file is: 16
I tried to track it down, but couldn't find any point where the class of dealers itself is defined hence I couldn't check if the class has the required member.
But, when someone looks into the script fn_questionDealer.sqf the same (or very similar) code is used to clear the list which does not throw an error. I don't know enough about the ArmA scripting language or this framework to track this issue further down - but as this code fails but pretty much the same runs smooth in some other script seems kind of strange. Can this maybe an issue cause the cleanup is run inside life_server which itself may doesn't even have an instance of the dealer objects?

**Comment by WolfSkin1337** [comment]
i dont have this Problem, and i work with the newest "master".

Have other scripts or mods on the server?

can you tell use the complet RPT?

**Comment by cryptearth** [comment]
Nope - only zip download of current master branch and packed both life_server and the mission with PBO Manager v.1.4 beta - which, as far as I can tell with hex-editor and "packed-by-handy" with small java code only packs the mission
as for RPT: my linux dedicated server doesn't log any RPT although it's the same config as on my local windows which does log RPT - don'T know if there's a difference in how the linux binary handles it - anyway - don't know what a RPT should show more as it's just the console output piped into a file - so if there would be any RPT its content would be the same as the console output itself - I can try to redirect the console output to a file and post that if required

**Comment by cryptearth** [comment]
well - as the default seem to take some time (30min) I've set up this:
I selled drugs to each of the 3 dealers as a civ and then questioned all 3 as cop - no error so far. Now I wait for the 30min to let the check run - if this still doesn't throw an error than it maybe some not initialized stuff ... we'll see - report back later ...

**Comment by cryptearth** [comment]
Hmm, no such luck, the error is still thrown as posted above.

**Comment by cryptearth** [comment]
Fixed in PR(merged) #667 - hence closed
