### ISSUE TITLE
can not stop escort

### ISSUE THREAD

**Issue by ghost** [AsYetUntitled/Framework#675]
### Expected behaviour
When you escort another player press win to stop escorting.

### Actual behaviour
When pressing win no menu appears - escorting can only be stopped by another cop un-restrain the restrianed player.

### Steps to reproduce the behaviour
1. cop A use shift-R to restrian other player
2. cop A use win on restrained player to start escorting
3. cop A can no longer use win to somehow stop escorting
4. another cop B has to use win on restrianed player to unrestrain

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)
not applicable

Mission version: 6.0.0 beta

Branch: master 4b0735e

This was already a topic back in 2017 but either not got fixed or somehow re-introduced.

**Comment by DomT602** [comment]
Good spot - found the issue, it'll get fixed in #674.
