### ISSUE TITLE
FuelStation does not work with Land_FuelStation_01_pump_F

### ISSUE THREAD

**Issue by setoy** [AsYetUntitled/Framework#68]
### Expected behaviour

You should be able to fuel up your vehicle on `Land_FuelStation_01_pump_F` stations.
### Actual behaviour

You can select to "fuel up car", but no dialog opens.
### Steps to reproduce the behaviour
1. Get a car
2. Go to a station that features the `Land_FuelStation_01_pump_F` station (e.g. nearly all in Georgetown, unfortunately).
3. Try to fuel up your car
### RPT and/or extDB2 logs (if applicable)

No logs, but I believe it's because of [this](https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/core/shops/fn_FuelStatOpen.sqf#L17).

Update:
I added a `hint` to the `exitWith` above and it indeed showed up, so I believe this is the culprit. I just don't know what the name of the correct feeder would be.

---

Launcher version: 1.5.137506

Game version: 1.62.137494

Branch: main / beta branch not specified

**Comment by BoGuu** [comment]
Interesting that it even got an addAction to begin with. Anyhow, it should be fixed in #37 already

**Comment by setoy** [comment]
Unfortunately, I've just tested it using the fn_setupStationService.sqf from your commit, but to no avail.

The fuelStatOpen.sqf hasn't changed in that PR.

**Comment by BoGuu** [comment]
@setoy 

Indeed, oversight, well spotted. Will add it shortly. Awful design in that fuelStat file tbh.

**Comment by setoy** [comment]
@BoGuu 

Thank you. Would you mind explaining to me how I can get the class names of those fuel station parts? I tried fixing it myself but wasn't able to get the class name from the editor :(

**Comment by Jawshy** [comment]
> [...] Would you mind explaining to me how I can get the class names of those fuel station parts? [...] 

Paste `copyToClipboard typeOf cursorObject` into the debug console, place your cursor over an object, and then locally execute. The class name of the object under your cursor will then be added to your clipboard.

**Comment by tmoitoi** [comment]
UP

**Comment by setoy** [comment]
This was an easy fix. I'll prepare a PR for that later.

**Comment by BoGuu** [comment]
I have this in a batch of things locally, no need to PR, thanks though.

To everyone: no need bump issues, the repo is a development build for a reason, they will be fixed for the release (when it's intended to be used).
