### ISSUE TITLE
Jail System

### ISSUE THREAD

**Issue by Cocaina-Ricky** [AsYetUntitled/Framework#681]
### Expected behaviour

When you get put to jail by a cop, it should set "arrested" column to 1 in "players" table.
It should also display a timer to show how long you have left.
After escaping, the chat message should default say that you have escaped from jail and "arrested" should switch back to 0

### Actual behaviour

When you jail someone, it permanently keeps them in jail regardless of you escaping or restarting the server.

### Steps to reproduce the behaviour
1. 
I didn't even touch anything to do with it and if I did, I don't know what it could've been?

### [RPT](https://community.bistudio.com/wiki/Crash_Files#Arma_3) and/or extDB3 logs (if applicable)

There's no RPT / extDB3 logs. (I enabled Debug)

Pastebin Client: 
https://pastebin.com/V9CB91WG

Pastebin Server:
https://pastebin.com/vkFfJ7ws

ExtDB3:
[15:04:54:006349 +01:00] [Thread 7112] extDB3: SQL: Initialized: Add Quotes around TEXT Datatypes mode: 2
[15:04:54:007191 +01:00] [Thread 7112] extDB3: SQL: Initialized: NULL = ""
[15:04:54:007213 +01:00] [Thread 7112] extDB3: Locked

----

Mission version: 5.0.0

Launcher version: Latest

Game version: Latest
Branch: Stable?

**Comment by cryptearth** [comment]
> "-servermod=@infiSTAR_A3;@The_Programmer;@extDB3;@life_server;@kden_load;@obfusqf"

Did you tried without the extra mods but only the vanilla mission?

**Comment by Cocaina-Ricky** [comment]
Thanks for the fast reply. I can guarantee you it's none of this servermods as they have nothing to do with the jail system, because everything else is working.

However wanted system isn't working either. Top right says "Establishing Connection...."

Do you know which files the jail system / wanted uses so I can try and find the error?

It's so strange to why these aren't working. I'm sure one of my files are messed up somewhere and I would like to repair/replace it but not sure which it could be.

**Comment by cryptearth** [comment]
I'm currently try to test the vanilla master branch without any modifications, and already found a lot of errors, but as I don't have a second account I have to wait for friends to help me out - and they often rarely join me in ArmA3. So player-player interaction is hard to test for me. In our last session we had to issue that the button to jail someone was greyed out so we couldn't test it, but I still don't know yet why it was not useable.

**Comment by Cocaina-Ricky** [comment]
I can join you to test it?

**Comment by cryptearth** [comment]
Sure, just add me on Steam: https://steamcommunity.com/id/cryptearth
Let's discuss it there to not further spam this issue.

**Comment by Cocaina-Ricky** [comment]
This hasn't been solved. If anyone could assist it would be such a relief.

**Comment by BlackFisch** [comment]
Jail works fine; you have to be at one of the `sendtoJail_locations` defines in master config -> https://github.com/AsYetUntitled/Framework/blob/master/Altis_Life.Altis/config/Config_Master.hpp#L112

**Comment by cryptearth** [comment]
> you have to be at one of the `sendtoJail_locations` defines in master config

Yea, figured that out after looking into how it works AFTER I replied. At the time of test we were at one of the legal gun shops - so far far away from one the police stations or the prison. Thanks for the explaining reply.

**Comment by Cocaina-Ricky** [comment]
> sendtoJail_locations

Thank you for the reply however this isn't the issue... I explained that:

sendtoJail_locations works by default. Again, this isn't the issue.

"When you get put to jail by a cop, it should set "arrested" column to 1 in "players" table.
It should also display a timer to show how long you have left.
After escaping, the chat message should default say that you have escaped from jail and "arrested" should switch back to 0"

**Comment by BlackFisch** [comment]
> 
> 
> > sendtoJail_locations
> 
> Thank you for the reply however this isn't the issue... I explained that:
> 
> sendtoJail_locations works by default. Again, this isn't the issue.
> 
> "When you get put to jail by a cop, it should set "arrested" column to 1 in "players" table.
> It should also display a timer to show how long you have left.
> After escaping, the chat message should default say that you have escaped from jail and "arrested" should switch back to 0"

Oh, okay I didn't see that.
Is that issue on master branch or 5.X.X branch/release? You didn't specify

**Comment by Cocaina-Ricky** [comment]
That issue is on 5.X.X branch.

**Comment by BlackFisch** [comment]
Thanks for the report, let us know if you can repro with a 100% clean install please
I guess the jail system needs a rework anyway, but thats a thing for the next release

**Comment by cryptearth** [comment]
Ah ok, 5.x.x branch huh? I'm only working with master branch, but I'm working with a clean repo clone so maybe we can reproduce it also on the master branch?
I'm anyway currently working on adding a lot of debug to anything - and also try to figure out how to use headless client to also test it.

**Comment by cryptearth** [comment]
Currently testing jail - at least me getting jailed seem to work in the master branch - the timer ticks - but although I have 1m+ cash it says I can't pay the bail, which is only 4k. I also can't interact with the officer at all.

**Comment by cryptearth** [comment]
btw - just for anybody to know that this is not an issue with the framework:

Cocaina-Ricky
> I've sorted my issue out
> With 5.x.x
> Rentable housing by C0kkie was the issue
> I don't understand what housing has to do with jail system but on a 4.4r3 I was adding scripts from scratch
> When all of a sudden I come across jail issue after using it.. i asked my friend to try on the 5.x.x if I remove it, we removed it and boom it worked

cryptearth
> Well, what files require Rentable Housing to be changed? Maybe there's a line clashing with how the jail works?

Cocaina-Ricky
> Fn_buyHouse
> Full file replacement
> [and] a locked .pbo
> In life_server / addons

I guess my first question about testing it vanilla without additional mods wasn't a bad idea ...
