### ISSUE TITLE
ClothingFilter errors.

### ISSUE THREAD

**Issue by Cocaina-Ricky** [AsYetUntitled/Framework#724]
### Expected behaviour

Errors on client side > life_fnc_clothingFilter

### Actual behaviour

Filters work however getting some weird error...

`18:51:23 Error in expression <};};private"_pic";private"_details";{_x params[["_className","NONE",[""]],["_dis>
18:51:23   Error position: <params[["_className","NONE",[""]],["_dis>
18:51:23   Error Params: Type String, expected Number
18:51:23 File core\shops\fn_clothingFilter.sqf [life_fnc_clothingFilter], line 35`

### Steps to reproduce the behaviour

No idea what happened here honestly.

-------

Mission version: 5.X.X

Launcher version: Latest

Game version: Latest 

Branch: 5.X.X

**Comment by DomT602** [comment]
Have you double checked your config for the clothing shop which produces this error?

**Comment by imthatguyhere** [comment]
Based on the error, it seems there is a string instead of a number in one of the prices in the clothing store arrays in your config.

**Comment by Cocaina-Ricky** [comment]
I think I might be stupid.

Pastebin:
https://pastebin.com/UqXdrVL7

I can't see what's wrong, I'm missing something but god knows.

**Comment by DomT602** [comment]
Which shop have you been opening? @Cocaina-Ricky

**Comment by Cocaina-Ricky** [comment]
All of them, they are all showing prices of 1,000. I cannot figure out what's happening

**Comment by DomT602** [comment]
Can we see your fn_clothingFilter.sqf please.

**Comment by Cocaina-Ricky** [comment]
#include "..\..\script_macros.hpp"
/*
    File: fn_clothingFilter.sqf
    Author: Bryan "Tonic" Boardwine

    Description:
    Functionality for filtering clothing types in the menu.
*/

disableSerialization;

params [
    "", //Control
    ["_selection", 0, [0]]
];

life_clothing_filter = _selection;

switch (_selection) do {
    case 4: {
        life_shop_cam camSetTarget (player modelToWorld [0,-.15,1.3]);
        life_shop_cam camSetPos (player modelToWorld [1,-4,2]);
        life_shop_cam camCommit 1;
    };

    case 0: {
        life_shop_cam camSetTarget (player modelToWorld [0,0,1]);
        life_shop_cam camSetPos (player modelToWorld [1,4,2]);
        life_shop_cam camCommit 1;
    };

    case 3: {
        life_shop_cam camSetTarget (player modelToWorld [0,0,1.4]);
        life_shop_cam camSetPos (player modelToWorld [-.1,2,1.4]);
        life_shop_cam camCommit 1;
    };

    default {
        life_shop_cam camSetTarget (player modelToWorld [0,0,1.6]);
        life_shop_cam camSetPos (player modelToWorld [-.5,1,1.6]);
        life_shop_cam camCommit 1;
    };
};

if (isNull (findDisplay 3100)) exitWith {};

private _list = CONTROL(3100,3101);
lbClear _list;

private _configArray = switch (_selection) do {
    case 0: {M_CONFIG(getArray,"Clothing",life_clothing_store,"uniforms");};
    case 1: {M_CONFIG(getArray,"Clothing",life_clothing_store,"headgear");};
    case 2: {M_CONFIG(getArray,"Clothing",life_clothing_store,"goggles");};
    case 3: {M_CONFIG(getArray,"Clothing",life_clothing_store,"vests");};
    case 4: {M_CONFIG(getArray,"Clothing",life_clothing_store,"backpacks");};
};

private "_pic";
private "_details";

{
    _x params [
        ["_className", "NONE", [""]],
        ["_displayName", "", [""]],
        ["_price", 1000, [0]]
    ];

    if !(_className isEqualTo "NONE") then {
        _details = [_className] call life_fnc_fetchCfgDetails;
        _pic = (_details select 2);
    };

    if ([_x] call life_fnc_levelCheck) then {

        if (isNil "_details") then {
            _list lbAdd _displayName;
            _list lbSetData [(lbSize _list)-1,_className];
        } else {
            if (_displayName isEqualTo "") then {
                _list lbAdd (_details select 1);
            } else {
                _list lbAdd _displayName;
            };

            _list lbSetData [(lbSize _list)-1,_className];
            _list lbSetValue [(lbSize _list)-1,_price];
            _list lbSetPicture [(lbSize _list)-1,_pic];
        };
    };
    
    true

} count _configArray;

[] spawn {
    sleep 0.1;
    [] call life_fnc_playerSkins;
};

**Comment by Cocaina-Ricky** [comment]
https://pastebin.com/VSsLfSBH

**Comment by DomT602** [comment]
@Cocaina-Ricky your Config_Clothing is wrong in many ways, look at the one from the GitHub (https://github.com/AsYetUntitled/Framework/blob/v5.X.X/Altis_Life.Altis/config/Config_Clothing.hpp).
For example;
`{ "NONE", $STR_C_Remove_uniforms, 0},
            { "U_C_Poloshirt_stripped", 75},
            { "U_C_Poloshirt_redwhite", 75},`

comparing to
`{ "NONE", $STR_C_Remove_uniforms, 0, "" },
            { "U_C_Poloshirt_stripped", "", 125, "" },
            { "U_C_Poloshirt_redwhite", "", 150, "" },`
You're missing many elements, and they are in different orders resulting in errors - you need to sort your config, not an error with the framework.

**Comment by Cocaina-Ricky** [comment]
Hi,

Yeah this fixed it. Sorry for slow replies.
