### ISSUE TITLE
Gang Disband / Leave bug?

### ISSUE THREAD

**Issue by Cocaina-Ricky** [AsYetUntitled/Framework#725]
Expected behaviour
Leave / Disband gang

Actual behaviour

As soon as you leave / disband gang, it should update in the gangs table on database. It doesn't.

**Steps to reproduce the behaviour**
Just disband / leave. 

---------------------------------

Mission version: 5.X.X

Launcher version: Latest

Game version: Latest

Branch: 5.X.X

**Comment by DomT602** [comment]
This is intended behaviour - the gang will get set as inactive and deleted when the server next starts up.

**Comment by Cocaina-Ricky** [comment]
Hi,

Yeah when the server gets up, it doesn't delete.. It puts you back into the gang. This shouldn't be like this.

**Comment by imthatguyhere** [comment]
In your database, does it show as active = 0 on the row for that gang?

**Comment by BlackFisch** [comment]
> Yeah when the server gets up, it doesn't delete.. It puts you back into the gang. This shouldn't be like this.

This seems like an issue either with you installation (procedures not running - check extdb logs please) or ye ol problem with saving members as an array, which can't really be fixed other than reworking the db structure

**Comment by Cocaina-Ricky** [comment]
> 
> 
> In your database, does it show as active = 0 on the row for that gang?

No, it doesn't. It shows 1.



> 
> 
> > Yeah when the server gets up, it doesn't delete.. It puts you back into the gang. This shouldn't be like this.
> 
> This seems like an issue either with you installation (procedures not running - check extdb logs please) or ye ol problem with saving members as an array, which can't really be fixed other than reworking the db structure

Nothing on ExtDB logs. Just the usual 

`[17:50:18:940440 +01:00] [Thread 4300] extDB3: SQL: Initialized: Add Quotes around TEXT Datatypes mode: 2
[17:50:18:940729 +01:00] [Thread 4300] extDB3: SQL: Initialized: NULL = ""
[17:50:18:940749 +01:00] [Thread 4300] extDB3: Locked`

What do you mean saving members as an array? I'm sure it can be fixed - Which files would be corrupted?
