### ISSUE TITLE
SQL unaccesible

### ISSUE THREAD

**Issue by FlashModz** [AsYetUntitled/Framework#74]
### Expected behaviour
Connected and functionnal

### Actual behaviour

15:52:56 No speaker given for Patterson Newton
15:52:56 No speaker given for Greer Walker
15:52:56 Strange convex component70 in a3\structures_f_exp\commercial\multistorybuilding_01\multistorybuilding_01_f.p3d:geometryFire
15:52:56 Strange convex component75 in a3\structures_f_exp\commercial\multistorybuilding_01\multistorybuilding_01_f.p3d:geometryFire
15:52:56 Strange convex component76 in a3\structures_f_exp\commercial\multistorybuilding_01\multistorybuilding_01_f.p3d:geometryFire
15:52:56 Strange convex component77 in a3\structures_f_exp\commercial\multistorybuilding_01\multistorybuilding_01_f.p3d:geometryFire
15:52:56 Strange convex component78 in a3\structures_f_exp\commercial\multistorybuilding_01\multistorybuilding_01_f.p3d:geometryFire
15:52:57 Mission read.
15:52:57 Connected to Steam servers
Error: Object(2 : 750) not found
Error: Object(2 : 755) not found
Error: Object(2 : 757) not found
Error: Object(2 : 759) not found
Error: Object(2 : 761) not found
Error: Object(2 : 763) not found
Error: Object(2 : 765) not found
Error: Object(2 : 767) not found
Error: Object(2 : 769) not found
Error: Object(2 : 870) not found
15:52:57 ../lib/Network/networkServer.cpp OnClientStateChanged:NOT IMPLEMENTED - briefing!
15:52:57  Mission id: 4e048bf8faaed56716eb788f1f6e19b930a77379
15:52:57 Game started.
15:52:57 "extDB2: Connected to Database"
15:52:57 "----------------------------------------------------------------------------------------------------"
15:52:57 "---------------------------------- Starting Altis Life Server Init ---------------------------------"
15:52:57 "------------------------------------------ Version 4.5 -------------------------------------------"
15:52:57 "----------------------------------------------------------------------------------------------------"
15:52:57 "----------------------------------------------------------------------------------------------------"
15:52:57 "               End of Altis Life Server Init :: Total Execution Time 0.0330009 seconds "
15:52:57 "----------------------------------------------------------------------------------------------------"
15:59:12 Bob Jacky uses modified data file
15:59:12 Player Bob Jacky connecting.
15:59:14 Player Bob Jacky connected (id=76561198264021855).
Unaccessible

### Steps to reproduce the behaviour 
1. Download all branch github
2. install folder and activate mods
3. launch the server
4. players connect

### RPT and/or extDB2 logs (if applicable)
extDB2 and RPT Client and RPT Server  : 

----

Game version: 1.62

Branch: Main

**Comment by BoGuu** [comment]
So you've posted a log that has no problems whatsoever in your 'actual behaviour', what exactly is your problem?

**Comment by FlashModz** [comment]
the player gets to that connect to the server, but no information with the shop or else it shares with the database.

example:

I bought a car.
it is in the database.
I return to the garage and the error I can not retrieve it or anything.

the same for the other shop

**Comment by FlashModz** [comment]
you have a TeamSpeak or others to show you the results obtained by SQL or other?

**Comment by Jawshy** [comment]
Contributing to AsYetUntitled → [Contact](https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md#contact).

**Comment by FlashModz** [comment]
im connected

**Comment by Jawshy** [comment]
Closing due to Discord conversation.
