### ISSUE TITLE
Extended Cop Skins - Client Side error

### ISSUE THREAD

**Issue by DarkSilencerZA** [AsYetUntitled/Framework#75]
23:23:51 Error in expression <dedSkins") isEqualTo 1) then {
if((call life_coplevel) >= 1) then {
_skinName = >
23:23:51   Error position: <life_coplevel) >= 1) then {
_skinName = >
23:23:51   Error Undefined variable in expression: life_coplevel
23:23:51 File mpmissions\__CUR_MP.altis\core\functions\fn_playerSkins.sqf, line 41

**Comment by BoGuu** [comment]
Not an issue with this build

**Comment by Jawshy** [comment]
[Markdown](https://guides.github.com/features/mastering-markdown/). [Issue template](https://github.com/AsYetUntitled/Framework/blob/master/.github/ISSUE_TEMPLATE.md). 

![What are those?](https://i.ytimg.com/vi/2NSKl5ZjPYQ/maxresdefault.jpg)
