### ISSUE TITLE
Houses/Garages Not Saving to DB

### ISSUE THREAD

**Issue by RoguePA** [AsYetUntitled/Framework#77]
### Expected behaviour
Houses and Garages Saving to player

### Actual behaviour
They're not saving, not being stored on the database

### Steps to reproduce the behaviour 
1. Go into the game, buy a house.
2. Exit the server
3. Go back onto the server, no longer have access to house

### RPT and/or extDB2 logs (if applicable)
<If there are error messages in your RPT and/or extDB2 logs then you can either paste the error message(s) here or you can upload your RPT or extDB2 log file(s) to GitHub.>
<See https://community.bistudio.com/wiki/Crash_Files for where to find your Arma 3 RPT logs.>
<If your error messages are long, or you are posting a full RPT, please use paste/haste-bin!!>

----

Launcher version: 1.5.137506

Game version: 1.62.137494

Branch: Main

Extra Notes: I've just started Tanoa Life on a fresh server loaned to me by a friend, it could be specific to this server.

**Comment by Jawshy** [comment]
@RoguePA, please post your server RPT and extDB2 logs.

**Comment by Jawshy** [comment]
I tested with the latest files ([d46157d](https://github.com/AsYetUntitled/Framework/tree/d46157dcdce784d0a8d6fd8398ad982c3bbab1b8)) and on both [Altis and Tanoa](https://github.com/AsYetUntitled/Framework/tree/2bb56fac5f2d09b6603f1ec5397f7d27c32f41e8/SQMs). I had no issues with houses or garages saving to the database.

**Comment by setoy** [comment]
^ Me neither. Works flawlessly. However what I did notice is that when I put stuff in backpacks and store the backpack in a car, the stuff inside the backpack is gone once I retrieve the car from the garage.

**Comment by tkcjesse** [comment]
@setoy that's kinda to be expected. Since it's essentially an inventory within an inventory.

**Comment by RoguePA** [comment]
I don't have access to the server right now I'll get you the files when I do, but I can tell you I'm not the only person to have the problem.

**Comment by RoguePA** [comment]
Still don't have access, I did however recieve this message off this .rpt logs which the guy working with me sent.

13:19:41 Object id aae6764b (1611) not found in slot 206,343
13:19:41 Link cannot be resolved

He said it's happening everytime he does something with the houses.

**Comment by setoy** [comment]
@tkcjesse Haven't had much experience with SQF, but in "high level" languages you'd use something like recursion for that... Isn't this possible with SQF?

**Comment by tkcjesse** [comment]
yes, but don't think you can get the cargo of cargo.

**Comment by RoguePA** [comment]
I was waiting to test a few things before I posted my logs, you can close this issue, it was a serverside problem.
