### ISSUE TITLE
Air vehicles not spawning after being bought in the Tanoa server

### ISSUE THREAD

**Issue by Iceman997799** [AsYetUntitled/Framework#80]
The only error I get in the server rpt is this
Object(4 : 8) not found

and nothing in the client rpt

I did see in the map editor in the mission.sqm that the spawn points for the aircraft spawns uses the helipad marker. I seen that the land vehicles uses the empty system marker. So I changed the markers and now the aircraft spawn after being bought.

**Comment by BoGuu** [comment]
Known issue, thanks for the report though. Next time, please stick to the layout given to you on the issues.

**Comment by MJRamon** [comment]
Is it fixed?

**Comment by Jawshy** [comment]
Is the issue closed? Two questions; same answer.

**Comment by BoGuu** [comment]
Nope, still TODO, just needs the markers changed as OP said
