### ISSUE TITLE
Resetting of player entries.

### ISSUE THREAD

**Issue by SimZor** [AsYetUntitled/Framework#85]
When a player logs in sometimes, it always queries the DB for the player information. Sometimes, it resets and inserts a new entry and all licenses and money are gone. The money is reset to 5000 and the starting money is 150000. It's only the licenses, money and gear. Nothing else.

There has not been any errors in any RPT logs of this.
----

Launcher version:  <In the Arma 3 launcher go to OPTIONS and click the version info below to copy it to your clipboard>

Game version: 

Branch:

**Comment by Jawshy** [comment]
Please follow the layout in the [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md).

**Comment by tkcjesse** [comment]
EVERYTIME a player connects a query is ran.... it shouldn't be able able to insert a new record... this is more than likely happening because you have added vehicles to shops but not set the class information for it. When it uses the default class in the vehicle config it WILL reset player data.

**Comment by SimZor** [comment]
I know that everytime a player connects a query is ran, that was what I said.

But I think this is the same issue as https://github.com/AsYetUntitled/Framework/issues/81.

**Comment by BoGuu** [comment]
Was this game version 1.64? This is why the issue template exists.

**Comment by Jawshy** [comment]
@SimZor, 

> Was this game version 1.64?

**Comment by SimZor** [comment]
This is still an issue. When logging in to the server, pressing go back to lobby in spawn screen then logging back in, the player gets reset to 5000 and all licenses are gone.
