### ISSUE TITLE
BEFilters: Update addWeaponCargo with addItemCargo

### ISSUE THREAD

**Issue by DarkSilencerZA** [AsYetUntitled/Framework#87]
- addItemCargo is logged within addWeaponCargo and so the addWeaponCargo will need updating.

1.62.138239 new PROFILING branch with PERFORMANCE binaries, v18, server and client, windows/linux
+ fixed addWeaponCargo global BattlEye filter 
+ fixed info returned for AddItemCargo,AddMagazienCargo,AddBackpackCargo global BattlEye filters

**Comment by Jawshy** [comment]
I'll update the filter and will push it to PR https://github.com/AsYetUntitled/Framework/pull/86. Also, please follow the layout in the [issue template](https://raw.githubusercontent.com/AsYetUntitled/Framework/master/.github/ISSUE_TEMPLATE.md).

**Comment by DarkSilencerZA** [comment]
Since we're using DM on Discord to solve this, I didn't see the need to follow a layout.

**Comment by Jawshy** [comment]
It's to set an example for others.

**Comment by DarkSilencerZA** [comment]
I'm sorry daddy. I will try better next time.

**Comment by Jawshy** [comment]
@DarkSilencerZA's addWeaponCargo.log file shows that items listed on the following pages are being logged:  
1. [Weapons](https://community.bistudio.com/wiki/Arma_3_CfgWeapons_Weapons) *again, finally*
2. [Items](https://community.bistudio.com/wiki/Arma_3_CfgWeapons_Items) 
3. [Equipment](https://community.bistudio.com/wiki/Arma_3_CfgWeapons_Equipment)
