### ISSUE TITLE
Convert to GitHub Projects?

### ISSUE THREAD

**Issue by MightySCollins** [AsYetUntitled/Framework#93]
The new GitHub project system has very similar Kanban functionality to Trello. It it allows Pull Requests and Issues to be nativity managed without having to re-enter issues.

I am sure it will be easier to use and means people don't need to go to an external site.

Enable it here:
https://github.com/AsYetUntitled/Framework/projects

**Comment by Jawshy** [comment]
[In progress...](https://github.com/AsYetUntitled/Framework/projects)

**Comment by Jawshy** [comment]
Converted.

**Comment by MightySCollins** [comment]
Is it just me or is there only 'TODO'? Should there not be more or at least similar categorises to Trello?
