### ISSUE TITLE
Error in expression <ariable ["sellers",[],true];

### ISSUE THREAD

**Issue by setoy** [AsYetUntitled/Framework#99]
### Expected behaviour
No error should appear and it should reset the seller list of the dealers.

### Actual behaviour
An error occurs and it doesn't reset the list of sellers. Probably because the dealers aren't initialized.

### Steps to reproduce the behaviour 
1. Well, wait.

### RPT and/or extDB2 logs (if applicable)
    13:15:35   Error Undefined variable in expression: _x
    13:15:35 File life_server\init.sqf, line 149
    13:15:35 Error in expression <0 to 1 step 0 do {
    uiSleep (30 * 60);
    {
    _x setVariable ["sellers",[],true];
    } fo>
    13:15:35   Error position: <_x setVariable ["sellers",[],true];
    } fo>
    13:15:35   Error Undefined variable in expression: _x
    13:15:35 File life_server\init.sqf, line 149
    13:15:35 Error in expression <ariable ["sellers",[],true];
    } forEach [Dealer_1,Dealer_2,Dealer_3];
    };
    };
    
    [] s>
    13:15:35   Error position: <Dealer_1,Dealer_2,Dealer_3];
    };
    };
    
    [] s>
    13:15:35   Error Undefined variable in expression: dealer_1
    13:15:35 File life_server\init.sqf, line 150

----

Launcher version:  <In the Arma 3 launcher go to OPTIONS and click the version info below to copy it to your clipboard>
Currently not at home to start the game, will add later. However I think this is irrelevant.

Game version: 

Branch:

**Comment by fresqo** [comment]
are you 100% sure you have an npc var named Dealer_1 on map?

**Comment by setoy** [comment]
Yep, they have exactly the same name like the NPC on the map.

**Comment by fresqo** [comment]
@setoy , we are running latest tanoa build, no Dealer_1 errors server side. Waited well beyond the timer

**Comment by setoy** [comment]
>  Waited well beyond the timer

Yeah, that's what I can read from the logs. It doesn't happen on every "tick", just random... At least that's how it appears to me. I'll try to get a grasp around it.

**Comment by infiSTAR** [comment]
You could do it like this to get rid of the error

`[] spawn {
    for "_i" from 0 to 1 step 0 do {
        uiSleep (30 * 60);
        {
            if(isNull _x)then
			{
				diag_log format["life_server init.sqf - Dealer_%1 is objNull - mission runtime %2",_forEachIndex + 1,time];
			}
			else
			{
				_x setVariable ["sellers",[],true];
			};
        } forEach [
			missionNameSpace getVariable ["Dealer_1",objNull],
			missionNameSpace getVariable ["Dealer_2",objNull],
			missionNameSpace getVariable ["Dealer_3",objNull]
		];
    };
};`

full file:
https://pastebin.com/GbPv8EfB

**Comment by setoy** [comment]
Fixed it by changing the raw names to strings:

``forEach ["Dealer_1","Dealer_2","Dealer_3"];

**Comment by DardoTheMaster** [comment]
@setoy  this makes no sense

**Comment by setoy** [comment]
But it works :D

**Comment by BoGuu** [comment]
@infiSTAR 

Indeed. People have an obsession with removing the dealers.

Will commit, unless you'd like to PR.

**Comment by infiSTAR** [comment]
setoy, what you posted doesn't work - it just doesn't cause the error in the logs anymore - yes. But you create a new issue because your actual trader object would be missing the variable set to it's object

You can commit it BoGuu, I don't know what the shortcut PR means :P

**Comment by setoy** [comment]
PR = Pull Request.

@infiSTAR Thanks :P

**Comment by BoGuu** [comment]
@setoy 

Like what @infiSTAR said, replacing the objects with strings will **not** work. Tbh, you should be receiving another error `Received STRING, expected ...` etc.

@infiSTAR 

Pull request on GitHub ;) No problem, will do.

**Comment by setoy** [comment]
So, there's definitely a dealer named `Dealer_1` in my map, however:
`22:01:41 "life_server init.sqf - Dealer_1 is objNull - mission runtime 14374.9"`

**Comment by infiSTAR** [comment]
What map do you run? Changed the sqm file?
Can you upload your sqm file for us?

**Comment by setoy** [comment]
I'm running Tanoa using this file: https://github.com/AsYetUntitled/Framework/blob/master/SQMs/missionTanoa.sqm

A few parts changed, but still the `Dealer_1` entity is there.

**Comment by infiSTAR** [comment]
mhh that's strange.
what if you just change the init line from
`init="removeAllWeapons this; this allowDamage false; this enableSimulation false; this addAction[localize""STR_MAR_Drug_Dealer"",life_fnc_virt_menu,""drugdealer"",0,false,false,"""",' isNull objectParent player && player distance _target < 5 && playerSide isEqualTo civilian ']; this addAction[localize""STR_MAR_Question_Dealer"",life_fnc_questionDealer,"""",0,false,false,"""",' isNull objectParent player && player distance _target < 5 && playerSide isEqualTo west && !life_action_inUse '];";`

to

`init="Dealer_1 = this; removeAllWeapons this; this allowDamage false; this enableSimulation false; this addAction[localize""STR_MAR_Drug_Dealer"",life_fnc_virt_menu,""drugdealer"",0,false,false,"""",' isNull objectParent player && player distance _target < 5 && playerSide isEqualTo civilian ']; this addAction[localize""STR_MAR_Question_Dealer"",life_fnc_questionDealer,"""",0,false,false,"""",' isNull objectParent player && player distance _target < 5 && playerSide isEqualTo west && !life_action_inUse '];";`

like dirty assigning the object to a variable :p

**Comment by trinitynet** [comment]
rude >.<

**Comment by setoy** [comment]
Oh, sorry. Thought I'd have added a comment.

Yeah, it was my fault. The marker was named like the dealer, not the actual npc... Sorry.
